/**
 * Dungeon definitions — each dungeon has its own tileset, enemy pool, and floor count.
 */

export interface BossDef {
  speciesId: string;
  name: string;
  statMultiplier: number; // e.g. 2.5 means 2.5x base stats
  extraSkillIds?: string[];
}

export interface DungeonDef {
  id: string;
  name: string;
  tilesetPath: string;      // path to tileset PNG
  tilesetKey: string;        // Phaser asset key
  floors: number;            // total floors
  enemySpeciesIds: string[]; // species IDs from SPECIES record
  /** Per-floor enemy distribution: floorIndex (1-based) → species IDs */
  floorEnemies: Record<number, string[]>;
  /** Difficulty scaling: multiplier applied to enemy stats */
  difficulty: number;
  /** Items per floor */
  itemsPerFloor: number;
  /** Unlock requirement: min total clears */
  unlockClears: number;
  /** Description shown in hub */
  description: string;
  /** Boss on final floor (optional) */
  boss?: BossDef;
}

export const DUNGEONS: Record<string, DungeonDef> = {
  beachCave: {
    id: "beachCave",
    name: "Beach Cave",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 5,
    enemySpeciesIds: ["zubat", "shellos", "corsola", "geodude"],
    floorEnemies: {
      1: ["zubat"],
      2: ["zubat", "shellos"],
      3: ["zubat", "shellos", "corsola"],
      4: ["shellos", "corsola", "geodude"],
      5: ["corsola", "geodude"],
    },
    difficulty: 1.0,
    itemsPerFloor: 3,
    unlockClears: 0,
    description: "B1F~B5F. Water and Rock types.",
    boss: { speciesId: "corsola", name: "Giant Corsola", statMultiplier: 2.5 },
  },
  thunderwaveCave: {
    id: "thunderwaveCave",
    name: "Thunderwave Cave",
    tilesetPath: "tilesets/ThunderwaveCave/tileset_0.png",
    tilesetKey: "thunderwave-tiles",
    floors: 6,
    enemySpeciesIds: ["voltorb", "magnemite", "pikachu"],
    floorEnemies: {
      1: ["voltorb"],
      2: ["voltorb", "magnemite"],
      3: ["voltorb", "magnemite"],
      4: ["magnemite", "pikachu"],
      5: ["magnemite", "pikachu"],
      6: ["pikachu"],
    },
    difficulty: 1.3,
    itemsPerFloor: 3,
    unlockClears: 1,
    description: "B1F~B6F. Electric types. Harder!",
    boss: { speciesId: "pikachu", name: "Alpha Pikachu", statMultiplier: 3.0 },
  },
  tinyWoods: {
    id: "tinyWoods",
    name: "Tiny Woods",
    tilesetPath: "tilesets/TinyWoods/tileset_0.png",
    tilesetKey: "tinywoods-tiles",
    floors: 4,
    enemySpeciesIds: ["caterpie", "pidgey"],
    floorEnemies: {
      1: ["caterpie"],
      2: ["caterpie", "pidgey"],
      3: ["pidgey", "caterpie"],
      4: ["pidgey"],
    },
    difficulty: 0.8,
    itemsPerFloor: 4,
    unlockClears: 0,
    description: "B1F~B4F. Bug and Flying. Easy!",
    boss: { speciesId: "pidgey", name: "Fierce Pidgey", statMultiplier: 2.0 },
  },
  mtSteel: {
    id: "mtSteel",
    name: "Mt. Steel",
    tilesetPath: "tilesets/ThunderwaveCave/tileset_0.png",
    tilesetKey: "thunderwave-tiles",
    floors: 7,
    enemySpeciesIds: ["aron", "meditite", "machop"],
    floorEnemies: {
      1: ["aron"],
      2: ["aron", "meditite"],
      3: ["meditite", "aron"],
      4: ["meditite", "machop"],
      5: ["machop", "aron"],
      6: ["machop", "meditite"],
      7: ["machop"],
    },
    difficulty: 1.5,
    itemsPerFloor: 3,
    unlockClears: 2,
    description: "B1F~B7F. Steel and Fighting. Very tough!",
    boss: { speciesId: "machop", name: "Champion Machop", statMultiplier: 3.5 },
  },
  skyTower: {
    id: "skyTower",
    name: "Sky Tower",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 8,
    enemySpeciesIds: ["gastly", "drowzee", "snorunt"],
    floorEnemies: {
      1: ["gastly"],
      2: ["gastly", "drowzee"],
      3: ["drowzee", "gastly"],
      4: ["drowzee", "snorunt"],
      5: ["snorunt", "gastly"],
      6: ["gastly", "drowzee", "snorunt"],
      7: ["snorunt", "drowzee"],
      8: ["gastly", "snorunt"],
    },
    difficulty: 1.8,
    itemsPerFloor: 3,
    unlockClears: 3,
    description: "B1F~B8F. Ghost, Psychic, Ice. Dangerous!",
    boss: { speciesId: "gastly", name: "Phantom Gastly", statMultiplier: 4.0 },
  },
  frostyForest: {
    id: "frostyForest",
    name: "Frosty Forest",
    tilesetPath: "tilesets/TinyWoods/tileset_0.png",
    tilesetKey: "tinywoods-tiles",
    floors: 10,
    enemySpeciesIds: ["snorunt", "shellos", "zubat", "drowzee"],
    floorEnemies: {
      1: ["snorunt"],
      2: ["snorunt", "shellos"],
      3: ["shellos", "zubat"],
      4: ["zubat", "snorunt"],
      5: ["snorunt", "drowzee"],
      6: ["drowzee", "zubat"],
      7: ["drowzee", "snorunt", "zubat"],
      8: ["snorunt", "drowzee"],
      9: ["drowzee", "snorunt"],
      10: ["snorunt"],
    },
    difficulty: 2.0,
    itemsPerFloor: 4,
    unlockClears: 5,
    description: "B1F~B10F. Ice and Psychic. The ultimate challenge!",
    boss: { speciesId: "snorunt", name: "Frost King Snorunt", statMultiplier: 4.5 },
  },
  magmaCavern: {
    id: "magmaCavern",
    name: "Magma Cavern",
    tilesetPath: "tilesets/ThunderwaveCave/tileset_0.png",
    tilesetKey: "thunderwave-tiles",
    floors: 12,
    enemySpeciesIds: ["numel", "slugma", "torkoal", "geodude", "aron"],
    floorEnemies: {
      1: ["numel"],
      2: ["numel", "slugma"],
      3: ["slugma", "numel"],
      4: ["slugma", "geodude"],
      5: ["numel", "geodude", "slugma"],
      6: ["geodude", "torkoal"],
      7: ["torkoal", "slugma"],
      8: ["torkoal", "aron", "numel"],
      9: ["aron", "torkoal"],
      10: ["torkoal", "aron", "slugma"],
      11: ["torkoal", "numel"],
      12: ["torkoal"],
    },
    difficulty: 2.2,
    itemsPerFloor: 3,
    unlockClears: 7,
    description: "B1F~B12F. Fire and Ground. Volcanic inferno!",
    boss: { speciesId: "torkoal", name: "Volcanic Torkoal", statMultiplier: 5.0 },
  },
  sinisterWoods: {
    id: "sinisterWoods",
    name: "Sinister Woods",
    tilesetPath: "tilesets/TinyWoods/tileset_0.png",
    tilesetKey: "tinywoods-tiles",
    floors: 14,
    enemySpeciesIds: ["murkrow", "sableye", "absol", "gastly", "drowzee", "poochyena"],
    floorEnemies: {
      1: ["poochyena"],
      2: ["poochyena", "murkrow"],
      3: ["murkrow", "sableye"],
      4: ["sableye", "gastly"],
      5: ["poochyena", "gastly"],
      6: ["gastly", "sableye"],
      7: ["sableye", "drowzee", "murkrow"],
      8: ["drowzee", "gastly"],
      9: ["murkrow", "absol"],
      10: ["absol", "sableye"],
      11: ["absol", "gastly", "murkrow"],
      12: ["absol", "drowzee"],
      13: ["absol", "sableye"],
      14: ["absol"],
    },
    difficulty: 2.5,
    itemsPerFloor: 3,
    unlockClears: 8,
    description: "B1F~B14F. Dark and Ghost. The abyss awaits!",
    boss: { speciesId: "absol", name: "Shadow Absol", statMultiplier: 5.5 },
  },
  overgrownForest: {
    id: "overgrownForest",
    name: "Overgrown Forest",
    tilesetPath: "tilesets/TinyWoods/tileset_0.png",
    tilesetKey: "tinywoods-tiles",
    floors: 12,
    enemySpeciesIds: ["chikorita", "bellsprout", "shroomish", "caterpie", "pidgey"],
    floorEnemies: {
      1: ["chikorita"],
      2: ["chikorita", "bellsprout"],
      3: ["bellsprout", "caterpie"],
      4: ["caterpie", "chikorita"],
      5: ["bellsprout", "shroomish"],
      6: ["shroomish", "chikorita"],
      7: ["shroomish", "pidgey", "bellsprout"],
      8: ["pidgey", "shroomish"],
      9: ["shroomish", "bellsprout", "chikorita"],
      10: ["shroomish", "pidgey"],
      11: ["shroomish", "bellsprout"],
      12: ["shroomish"],
    },
    difficulty: 2.3,
    itemsPerFloor: 4,
    unlockClears: 9,
    description: "B1F~B12F. Grass and Bug. Nature's wrath!",
    boss: { speciesId: "shroomish", name: "Ancient Breloom", statMultiplier: 5.0 },
  },
  toxicSwamp: {
    id: "toxicSwamp",
    name: "Toxic Swamp",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 14,
    enemySpeciesIds: ["grimer", "nidoranM", "tentacool", "bellsprout", "zubat"],
    floorEnemies: {
      1: ["grimer"],
      2: ["grimer", "nidoranM"],
      3: ["nidoranM", "grimer"],
      4: ["nidoranM", "zubat"],
      5: ["grimer", "tentacool"],
      6: ["tentacool", "nidoranM"],
      7: ["tentacool", "bellsprout", "grimer"],
      8: ["bellsprout", "tentacool"],
      9: ["grimer", "nidoranM", "tentacool"],
      10: ["tentacool", "bellsprout"],
      11: ["nidoranM", "grimer"],
      12: ["grimer", "tentacool"],
      13: ["grimer", "nidoranM"],
      14: ["grimer"],
    },
    difficulty: 2.6,
    itemsPerFloor: 3,
    unlockClears: 10,
    description: "B1F~B14F. Poison and Water. Toxic miasma!",
    boss: { speciesId: "grimer", name: "Toxic Muk", statMultiplier: 5.5 },
  },
  moonlitCave: {
    id: "moonlitCave",
    name: "Moonlit Cave",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 10,
    enemySpeciesIds: ["clefairy", "jigglypuff", "ralts", "drowzee", "snorunt"],
    floorEnemies: {
      1: ["clefairy"],
      2: ["clefairy", "jigglypuff"],
      3: ["jigglypuff", "clefairy"],
      4: ["jigglypuff", "ralts"],
      5: ["ralts", "clefairy"],
      6: ["ralts", "drowzee", "jigglypuff"],
      7: ["drowzee", "ralts"],
      8: ["ralts", "snorunt", "clefairy"],
      9: ["snorunt", "ralts"],
      10: ["ralts"],
    },
    difficulty: 2.4,
    itemsPerFloor: 4,
    unlockClears: 11,
    description: "B1F~B10F. Fairy and Psychic. Enchanted moonlight!",
    boss: { speciesId: "ralts", name: "Mystic Gardevoir", statMultiplier: 5.5 },
  },
  dragonsLair: {
    id: "dragonsLair",
    name: "Dragon's Lair",
    tilesetPath: "tilesets/ThunderwaveCave/tileset_0.png",
    tilesetKey: "thunderwave-tiles",
    floors: 16,
    enemySpeciesIds: ["dratini", "bagon", "gible", "geodude", "aron"],
    floorEnemies: {
      1: ["dratini"],
      2: ["dratini", "bagon"],
      3: ["bagon", "dratini"],
      4: ["bagon", "geodude"],
      5: ["dratini", "gible"],
      6: ["gible", "bagon"],
      7: ["gible", "dratini", "geodude"],
      8: ["geodude", "gible"],
      9: ["gible", "aron", "bagon"],
      10: ["aron", "gible"],
      11: ["gible", "bagon", "dratini"],
      12: ["bagon", "gible"],
      13: ["gible", "aron"],
      14: ["gible", "bagon"],
      15: ["gible", "dratini"],
      16: ["gible"],
    },
    difficulty: 3.0,
    itemsPerFloor: 3,
    unlockClears: 12,
    description: "B1F~B16F. Dragon types. The ultimate trial!",
    boss: { speciesId: "gible", name: "Elder Garchomp", statMultiplier: 6.0, extraSkillIds: ["dracoMeteor", "earthPower"] },
  },
  steelFortress: {
    id: "steelFortress",
    name: "Steel Fortress",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 14,
    enemySpeciesIds: ["aron", "beldum", "skarmory", "magnemite", "geodude"],
    floorEnemies: {
      1: ["aron", "geodude"],
      2: ["aron", "magnemite"],
      3: ["magnemite", "geodude"],
      4: ["aron", "beldum"],
      5: ["beldum", "magnemite"],
      6: ["beldum", "skarmory"],
      7: ["skarmory", "aron"],
      8: ["skarmory", "beldum"],
      9: ["beldum", "skarmory", "aron"],
      10: ["skarmory", "beldum", "magnemite"],
      11: ["beldum", "skarmory"],
      12: ["skarmory", "beldum"],
      13: ["beldum", "skarmory"],
      14: ["skarmory"],
    },
    difficulty: 2.8,
    itemsPerFloor: 3,
    unlockClears: 13,
    description: "B1F~B14F. Steel types. Cold iron walls!",
    boss: { speciesId: "beldum", name: "Iron Metagross", statMultiplier: 6.0, extraSkillIds: ["flashCannon", "bulletPunch"] },
  },
  buriedRuins: {
    id: "buriedRuins",
    name: "Buried Ruins",
    tilesetPath: "tilesets/ThunderwaveCave/tileset_0.png",
    tilesetKey: "thunderwave-tiles",
    floors: 12,
    enemySpeciesIds: ["sandshrew", "trapinch", "phanpy", "geodude", "numel"],
    floorEnemies: {
      1: ["sandshrew", "geodude"],
      2: ["sandshrew", "phanpy"],
      3: ["geodude", "phanpy"],
      4: ["phanpy", "trapinch"],
      5: ["trapinch", "sandshrew"],
      6: ["trapinch", "numel"],
      7: ["numel", "sandshrew"],
      8: ["sandshrew", "trapinch", "phanpy"],
      9: ["trapinch", "phanpy", "numel"],
      10: ["trapinch", "phanpy"],
      11: ["trapinch", "sandshrew"],
      12: ["trapinch"],
    },
    difficulty: 2.5,
    itemsPerFloor: 3,
    unlockClears: 14,
    description: "B1F~B12F. Ground types. Ancient desert ruins!",
    boss: { speciesId: "trapinch", name: "Ancient Flygon", statMultiplier: 5.5, extraSkillIds: ["earthPower", "sandTomb"] },
  },
  stormySea: {
    id: "stormySea",
    name: "Stormy Sea",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 18,
    enemySpeciesIds: ["horsea", "lotad", "carvanha", "shellos", "corsola", "tentacool"],
    floorEnemies: {
      1: ["shellos", "lotad"],
      2: ["shellos", "horsea"],
      3: ["horsea", "lotad"],
      4: ["lotad", "corsola"],
      5: ["corsola", "horsea"],
      6: ["horsea", "tentacool"],
      7: ["tentacool", "carvanha"],
      8: ["carvanha", "horsea"],
      9: ["carvanha", "lotad"],
      10: ["carvanha", "tentacool", "horsea"],
      11: ["horsea", "carvanha", "corsola"],
      12: ["tentacool", "carvanha"],
      13: ["carvanha", "horsea"],
      14: ["horsea", "carvanha", "tentacool"],
      15: ["carvanha", "horsea"],
      16: ["carvanha", "tentacool"],
      17: ["carvanha", "horsea"],
      18: ["carvanha"],
    },
    difficulty: 2.7,
    itemsPerFloor: 3,
    unlockClears: 10,
    description: "B1F~B18F. Water/Dark. Raging ocean depths!",
    boss: { speciesId: "carvanha", name: "Abyssal Sharpedo", statMultiplier: 5.5, extraSkillIds: ["darkPulse", "brine"] },
  },
  ampPlains: {
    id: "ampPlains",
    name: "Amp Plains",
    tilesetPath: "tilesets/ThunderwaveCave/tileset_0.png",
    tilesetKey: "thunderwave-tiles",
    floors: 10,
    enemySpeciesIds: ["elekid", "mareep", "pikachu", "voltorb", "magnemite"],
    floorEnemies: {
      1: ["mareep", "voltorb"],
      2: ["mareep", "pikachu"],
      3: ["pikachu", "magnemite"],
      4: ["magnemite", "elekid"],
      5: ["elekid", "mareep"],
      6: ["elekid", "pikachu"],
      7: ["pikachu", "voltorb", "elekid"],
      8: ["elekid", "mareep", "magnemite"],
      9: ["elekid", "pikachu"],
      10: ["elekid"],
    },
    difficulty: 2.2,
    itemsPerFloor: 3,
    unlockClears: 6,
    description: "B1F~B10F. Electric types. Thunder crackles!",
    boss: { speciesId: "elekid", name: "Storm Electivire", statMultiplier: 5.0, extraSkillIds: ["thunderbolt", "thunderPunch"] },
  },
  verdantForest: {
    id: "verdantForest",
    name: "Verdant Forest",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 8,
    enemySpeciesIds: ["caterpie", "wurmple", "spinarak", "pidgey"],
    floorEnemies: {
      1: ["caterpie", "wurmple"],
      2: ["wurmple", "pidgey"],
      3: ["pidgey", "caterpie"],
      4: ["caterpie", "spinarak"],
      5: ["spinarak", "wurmple"],
      6: ["spinarak", "pidgey"],
      7: ["spinarak", "wurmple", "caterpie"],
      8: ["spinarak"],
    },
    difficulty: 1.6,
    itemsPerFloor: 4,
    unlockClears: 4,
    description: "B1F~B8F. Bug types. Creepy crawlies!",
    boss: { speciesId: "spinarak", name: "Matriarch Ariados", statMultiplier: 4.0, extraSkillIds: ["signalBeam"] },
  },
  mysticSanctum: {
    id: "mysticSanctum",
    name: "Mystic Sanctum",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 12,
    enemySpeciesIds: ["abra", "natu", "drowzee", "ralts"],
    floorEnemies: {
      1: ["natu", "drowzee"],
      2: ["drowzee", "abra"],
      3: ["abra", "natu"],
      4: ["natu", "ralts"],
      5: ["ralts", "abra"],
      6: ["abra", "drowzee"],
      7: ["drowzee", "natu", "abra"],
      8: ["abra", "ralts", "natu"],
      9: ["abra", "natu"],
      10: ["ralts", "abra"],
      11: ["abra", "natu"],
      12: ["abra"],
    },
    difficulty: 2.4,
    itemsPerFloor: 3,
    unlockClears: 11,
    description: "B1F~B12F. Psychic types. Mind-bending mazes!",
    boss: { speciesId: "abra", name: "Grand Alakazam", statMultiplier: 5.5, extraSkillIds: ["psychic", "hypnosis"] },
  },
  shadowForest: {
    id: "shadowForest",
    name: "Shadow Forest",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 14,
    enemySpeciesIds: ["houndour", "sneasel", "poochyena", "murkrow", "sableye", "absol"],
    floorEnemies: {
      1: ["poochyena", "murkrow"],
      2: ["murkrow", "houndour"],
      3: ["houndour", "poochyena"],
      4: ["poochyena", "sneasel"],
      5: ["sneasel", "sableye"],
      6: ["sableye", "houndour"],
      7: ["houndour", "murkrow", "sneasel"],
      8: ["sneasel", "sableye", "poochyena"],
      9: ["murkrow", "houndour", "sableye"],
      10: ["absol", "sneasel", "houndour"],
      11: ["absol", "sableye", "sneasel"],
      12: ["absol", "houndour"],
      13: ["absol", "sneasel"],
      14: ["absol"],
    },
    difficulty: 2.6,
    itemsPerFloor: 3,
    unlockClears: 12,
    description: "B1F~B14F. Dark types lurk in the shadows!",
    boss: { speciesId: "absol", name: "Dread Absol", statMultiplier: 5.5, extraSkillIds: ["darkPulse", "nightSlash", "crunch"] },
  },
  windySummit: {
    id: "windySummit",
    name: "Windy Summit",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 10,
    enemySpeciesIds: ["taillow", "starly", "pidgey", "zubat", "murkrow"],
    floorEnemies: {
      1: ["starly", "pidgey"],
      2: ["pidgey", "taillow"],
      3: ["taillow", "starly"],
      4: ["starly", "zubat"],
      5: ["zubat", "taillow", "pidgey"],
      6: ["taillow", "murkrow"],
      7: ["murkrow", "starly", "taillow"],
      8: ["taillow", "murkrow", "zubat"],
      9: ["taillow", "starly"],
      10: ["taillow"],
    },
    difficulty: 2.0,
    itemsPerFloor: 3,
    unlockClears: 5,
    description: "B1F~B10F. Flying types ride the wind!",
    boss: { speciesId: "taillow", name: "Storm Swellow", statMultiplier: 5.0, extraSkillIds: ["braveBird", "airSlash", "wingAttack"] },
  },
  battleArena: {
    id: "battleArena",
    name: "Battle Arena",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 12,
    enemySpeciesIds: ["makuhita", "riolu", "machop", "meditite"],
    floorEnemies: {
      1: ["machop", "meditite"],
      2: ["meditite", "makuhita"],
      3: ["makuhita", "machop"],
      4: ["machop", "riolu"],
      5: ["riolu", "makuhita"],
      6: ["makuhita", "meditite", "riolu"],
      7: ["riolu", "machop", "makuhita"],
      8: ["makuhita", "riolu", "meditite"],
      9: ["riolu", "machop"],
      10: ["riolu", "makuhita"],
      11: ["riolu", "machop"],
      12: ["riolu"],
    },
    difficulty: 2.3,
    itemsPerFloor: 3,
    unlockClears: 7,
    description: "B1F~B12F. Fighting types train here!",
    boss: { speciesId: "riolu", name: "Champion Lucario", statMultiplier: 5.5, extraSkillIds: ["auraSphere", "focusPunch", "drainPunch"] },
  },
  rockyCavern: {
    id: "rockyCavern",
    name: "Rocky Cavern",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 12,
    enemySpeciesIds: ["larvitar", "nosepass", "geodude", "aron"],
    floorEnemies: {
      1: ["geodude", "aron"],
      2: ["aron", "nosepass"],
      3: ["nosepass", "geodude"],
      4: ["geodude", "larvitar"],
      5: ["larvitar", "nosepass"],
      6: ["nosepass", "aron", "larvitar"],
      7: ["larvitar", "geodude", "nosepass"],
      8: ["nosepass", "larvitar", "aron"],
      9: ["larvitar", "geodude"],
      10: ["larvitar", "nosepass"],
      11: ["larvitar", "geodude"],
      12: ["larvitar"],
    },
    difficulty: 2.5,
    itemsPerFloor: 3,
    unlockClears: 9,
    description: "B1F~B12F. Rock types fortify the depths!",
    boss: { speciesId: "larvitar", name: "Ancient Tyranitar", statMultiplier: 6.0, extraSkillIds: ["stoneEdge", "rockSlide", "crunch"] },
  },
  frozenTundra: {
    id: "frozenTundra",
    name: "Frozen Tundra",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 14,
    enemySpeciesIds: ["swinub", "spheal", "snorunt"],
    floorEnemies: {
      1: ["snorunt", "spheal"],
      2: ["spheal", "swinub"],
      3: ["swinub", "snorunt"],
      4: ["snorunt", "spheal"],
      5: ["spheal", "swinub", "snorunt"],
      6: ["swinub", "spheal"],
      7: ["spheal", "snorunt", "swinub"],
      8: ["swinub", "snorunt"],
      9: ["swinub", "spheal"],
      10: ["spheal", "swinub"],
      11: ["swinub", "spheal"],
      12: ["swinub", "snorunt"],
      13: ["swinub", "spheal"],
      14: ["swinub"],
    },
    difficulty: 2.6,
    itemsPerFloor: 3,
    unlockClears: 10,
    description: "B1F~B14F. Ice types endure the cold!",
    boss: { speciesId: "swinub", name: "Frost Mamoswine", statMultiplier: 5.5, extraSkillIds: ["avalanche", "iceBeam", "earthPower"] },
  },
  meadowPath: {
    id: "meadowPath",
    name: "Meadow Path",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 8,
    enemySpeciesIds: ["zigzagoon", "whismur", "caterpie", "pidgey"],
    floorEnemies: {
      1: ["caterpie", "pidgey"],
      2: ["pidgey", "zigzagoon"],
      3: ["zigzagoon", "whismur"],
      4: ["whismur", "caterpie", "zigzagoon"],
      5: ["zigzagoon", "whismur", "pidgey"],
      6: ["whismur", "zigzagoon"],
      7: ["zigzagoon", "whismur"],
      8: ["whismur"],
    },
    difficulty: 1.4,
    itemsPerFloor: 3,
    unlockClears: 2,
    description: "B1F~B8F. A gentle stroll through the meadow!",
    boss: { speciesId: "whismur", name: "Booming Exploud", statMultiplier: 4.5, extraSkillIds: ["hyperVoice", "headbutt"] },
  },
  petalGarden: {
    id: "petalGarden",
    name: "Petal Garden",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 10,
    enemySpeciesIds: ["oddish", "budew", "bellsprout", "shroomish"],
    floorEnemies: {
      1: ["bellsprout", "budew"],
      2: ["budew", "oddish"],
      3: ["oddish", "shroomish"],
      4: ["shroomish", "bellsprout", "budew"],
      5: ["oddish", "budew", "shroomish"],
      6: ["shroomish", "oddish"],
      7: ["oddish", "budew", "bellsprout"],
      8: ["oddish", "shroomish"],
      9: ["oddish", "budew"],
      10: ["oddish"],
    },
    difficulty: 2.0,
    itemsPerFloor: 3,
    unlockClears: 4,
    description: "B1F~B10F. Grass types bloom in the garden!",
    boss: { speciesId: "oddish", name: "Blooming Vileplume", statMultiplier: 5.0, extraSkillIds: ["petalDance", "energyBall", "sleepPowder"] },
  },
  emberGrotto: {
    id: "emberGrotto",
    name: "Ember Grotto",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 12,
    enemySpeciesIds: ["vulpix", "ponyta", "charmander", "slugma"],
    floorEnemies: {
      1: ["charmander", "slugma"],
      2: ["slugma", "vulpix"],
      3: ["vulpix", "ponyta"],
      4: ["ponyta", "charmander", "vulpix"],
      5: ["vulpix", "slugma", "ponyta"],
      6: ["ponyta", "vulpix"],
      7: ["vulpix", "ponyta", "charmander"],
      8: ["ponyta", "vulpix"],
      9: ["vulpix", "ponyta"],
      10: ["ponyta", "vulpix"],
      11: ["vulpix", "ponyta"],
      12: ["ponyta"],
    },
    difficulty: 2.3,
    itemsPerFloor: 3,
    unlockClears: 6,
    description: "B1F~B12F. Fire types burn in the grotto!",
    boss: { speciesId: "ponyta", name: "Blazing Rapidash", statMultiplier: 5.5, extraSkillIds: ["fireBlast", "flameWheel", "bodySlam"] },
  },
  coralReef: {
    id: "coralReef",
    name: "Coral Reef",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 11,
    enemySpeciesIds: ["staryu", "clamperl", "tentacool", "horsea"],
    floorEnemies: {
      1: ["tentacool", "horsea"],
      2: ["horsea", "staryu"],
      3: ["staryu", "clamperl"],
      4: ["clamperl", "tentacool", "staryu"],
      5: ["staryu", "clamperl", "horsea"],
      6: ["clamperl", "staryu"],
      7: ["staryu", "tentacool", "clamperl"],
      8: ["clamperl", "staryu"],
      9: ["staryu", "clamperl"],
      10: ["clamperl", "staryu"],
      11: ["staryu"],
    },
    difficulty: 2.2,
    itemsPerFloor: 3,
    unlockClears: 5,
    description: "B1F~B11F. Water types swirl in the reef!",
    boss: { speciesId: "staryu", name: "Dazzling Starmie", statMultiplier: 5.0, extraSkillIds: ["surf", "aquaJet", "whirlpool"] },
  },
  voltageLab: {
    id: "voltageLab",
    name: "Voltage Lab",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 10,
    enemySpeciesIds: ["shinx", "electrike", "mareep", "elekid"],
    floorEnemies: {
      1: ["mareep", "elekid"],
      2: ["elekid", "shinx"],
      3: ["shinx", "electrike"],
      4: ["electrike", "mareep", "shinx"],
      5: ["shinx", "electrike", "elekid"],
      6: ["electrike", "shinx"],
      7: ["shinx", "electrike", "mareep"],
      8: ["electrike", "shinx"],
      9: ["shinx", "electrike"],
      10: ["electrike"],
    },
    difficulty: 2.1,
    itemsPerFloor: 3,
    unlockClears: 5,
    description: "B1F~B10F. Electric types spark in the lab!",
    boss: { speciesId: "electrike", name: "Storm Manectric", statMultiplier: 5.0, extraSkillIds: ["thunderbolt", "wildCharge", "bite"] },
  },
  venomDepths: {
    id: "venomDepths",
    name: "Venom Depths",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 11,
    enemySpeciesIds: ["gulpin", "ekans", "grimer", "tentacool"],
    floorEnemies: {
      1: ["grimer", "tentacool"],
      2: ["tentacool", "gulpin"],
      3: ["gulpin", "ekans"],
      4: ["ekans", "grimer", "gulpin"],
      5: ["gulpin", "ekans", "tentacool"],
      6: ["ekans", "gulpin"],
      7: ["gulpin", "grimer", "ekans"],
      8: ["ekans", "gulpin"],
      9: ["gulpin", "ekans"],
      10: ["ekans", "gulpin"],
      11: ["ekans"],
    },
    difficulty: 2.4,
    itemsPerFloor: 3,
    unlockClears: 7,
    description: "B1F~B11F. Poison types lurk in the depths!",
    boss: { speciesId: "ekans", name: "Viper Arbok", statMultiplier: 5.5, extraSkillIds: ["sludgeBomb", "venoshock", "bite"] },
  },
  quakeTunnel: {
    id: "quakeTunnel",
    name: "Quake Tunnel",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 12,
    enemySpeciesIds: ["cubone", "diglett", "sandshrew", "trapinch"],
    floorEnemies: {
      1: ["sandshrew", "trapinch"],
      2: ["trapinch", "cubone"],
      3: ["cubone", "diglett"],
      4: ["diglett", "sandshrew", "cubone"],
      5: ["cubone", "diglett", "trapinch"],
      6: ["diglett", "cubone"],
      7: ["cubone", "sandshrew", "diglett"],
      8: ["diglett", "cubone"],
      9: ["cubone", "diglett"],
      10: ["diglett", "cubone"],
      11: ["cubone", "diglett"],
      12: ["cubone"],
    },
    difficulty: 2.5,
    itemsPerFloor: 3,
    unlockClears: 8,
    description: "B1F~B12F. Ground types shake the tunnel!",
    boss: { speciesId: "cubone", name: "Skull Marowak", statMultiplier: 5.5, extraSkillIds: ["boneRush", "earthPower", "fireBlast"] },
  },
  mossBurrow: {
    id: "mossBurrow",
    name: "Moss Burrow",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 10,
    enemySpeciesIds: ["paras", "venonat", "caterpie", "spinarak"],
    floorEnemies: {
      1: ["caterpie", "spinarak"],
      2: ["spinarak", "paras"],
      3: ["paras", "venonat"],
      4: ["venonat", "caterpie", "paras"],
      5: ["paras", "venonat", "spinarak"],
      6: ["venonat", "paras"],
      7: ["paras", "spinarak", "venonat"],
      8: ["venonat", "paras"],
      9: ["paras", "venonat"],
      10: ["venonat"],
    },
    difficulty: 2.0,
    itemsPerFloor: 3,
    unlockClears: 4,
    description: "B1F~B10F. Bug types thrive in the moss!",
    boss: { speciesId: "venonat", name: "Toxic Venomoth", statMultiplier: 5.0, extraSkillIds: ["signalBeam", "sleepPowder", "sludgeBomb"] },
  },
  ironWorks: {
    id: "ironWorks",
    name: "Iron Works",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 13,
    enemySpeciesIds: ["shieldon", "bronzor", "aron", "magnemite"],
    floorEnemies: {
      1: ["aron", "magnemite"],
      2: ["magnemite", "shieldon"],
      3: ["shieldon", "bronzor"],
      4: ["bronzor", "aron", "shieldon"],
      5: ["shieldon", "bronzor", "magnemite"],
      6: ["bronzor", "shieldon"],
      7: ["shieldon", "aron", "bronzor"],
      8: ["bronzor", "shieldon"],
      9: ["shieldon", "bronzor"],
      10: ["bronzor", "shieldon"],
      11: ["shieldon", "bronzor"],
      12: ["bronzor", "shieldon"],
      13: ["shieldon"],
    },
    difficulty: 2.7,
    itemsPerFloor: 3,
    unlockClears: 11,
    description: "B1F~B13F. Steel types forge in the works!",
    boss: { speciesId: "shieldon", name: "Iron Bastiodon", statMultiplier: 6.0, extraSkillIds: ["flashCannon", "ironHead", "gyroBall"] },
  },
  phantomCrypt: {
    id: "phantomCrypt",
    name: "Phantom Crypt",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 12,
    enemySpeciesIds: ["misdreavus", "duskull", "gastly"],
    floorEnemies: {
      1: ["gastly"],
      2: ["gastly", "misdreavus"],
      3: ["misdreavus", "duskull"],
      4: ["duskull", "gastly", "misdreavus"],
      5: ["misdreavus", "duskull", "gastly"],
      6: ["duskull", "misdreavus"],
      7: ["misdreavus", "gastly", "duskull"],
      8: ["duskull", "misdreavus"],
      9: ["misdreavus", "duskull"],
      10: ["duskull", "misdreavus"],
      11: ["misdreavus", "duskull"],
      12: ["duskull"],
    },
    difficulty: 2.6,
    itemsPerFloor: 3,
    unlockClears: 10,
    description: "B1F~B12F. Ghost types haunt the crypt!",
    boss: { speciesId: "misdreavus", name: "Phantom Mismagius", statMultiplier: 5.5, extraSkillIds: ["shadowBall", "shadowSneak", "nightShade"] },
  },
  wyrmAbyss: {
    id: "wyrmAbyss",
    name: "Wyrm Abyss",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 13,
    enemySpeciesIds: ["axew", "deino", "bagon", "gible"],
    floorEnemies: {
      1: ["axew"],
      2: ["axew", "bagon"],
      3: ["bagon", "deino"],
      4: ["deino", "axew"],
      5: ["axew", "gible"],
      6: ["gible", "bagon"],
      7: ["bagon", "deino"],
      8: ["deino", "gible"],
      9: ["gible", "axew"],
      10: ["axew", "deino", "bagon"],
      11: ["deino", "gible", "axew"],
      12: ["gible", "bagon", "deino"],
      13: ["axew", "deino", "gible"],
    },
    difficulty: 2.8,
    itemsPerFloor: 3,
    unlockClears: 11,
    description: "B1F~B13F. Dragon types rule the abyss!",
    boss: { speciesId: "axew", name: "Titan Haxorus", statMultiplier: 6.5, extraSkillIds: ["dragonClaw", "dragonRush", "dragonPulse"] },
  },
  enchantedGlade: {
    id: "enchantedGlade",
    name: "Enchanted Glade",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 10,
    enemySpeciesIds: ["snubbull", "togepi", "ralts", "clefairy"],
    floorEnemies: {
      1: ["snubbull"],
      2: ["snubbull", "togepi"],
      3: ["togepi", "ralts"],
      4: ["ralts", "snubbull"],
      5: ["snubbull", "clefairy"],
      6: ["clefairy", "togepi"],
      7: ["togepi", "ralts"],
      8: ["ralts", "clefairy", "snubbull"],
      9: ["snubbull", "togepi", "clefairy"],
      10: ["togepi", "ralts", "snubbull"],
    },
    difficulty: 2.1,
    itemsPerFloor: 4,
    unlockClears: 8,
    description: "B1F~B10F. Fairy types frolic in the glade!",
    boss: { speciesId: "snubbull", name: "Radiant Granbull", statMultiplier: 5.5, extraSkillIds: ["playRough", "dazzlingGleam", "moonblast"] },
  },
  glacialCavern: {
    id: "glacialCavern",
    name: "Glacial Cavern",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 12,
    enemySpeciesIds: ["snover", "bergmite", "snorunt", "spheal"],
    floorEnemies: {
      1: ["snover"],
      2: ["snover", "bergmite"],
      3: ["bergmite", "snorunt"],
      4: ["snorunt", "snover"],
      5: ["snover", "spheal"],
      6: ["spheal", "bergmite"],
      7: ["bergmite", "snorunt"],
      8: ["snorunt", "spheal", "snover"],
      9: ["snover", "bergmite", "spheal"],
      10: ["spheal", "snorunt", "bergmite"],
      11: ["bergmite", "snover", "snorunt"],
      12: ["snover", "bergmite", "spheal", "snorunt"],
    },
    difficulty: 2.5,
    itemsPerFloor: 3,
    unlockClears: 10,
    description: "B1F~B12F. Ice types lurk in frozen depths!",
    boss: { speciesId: "snover", name: "Frost Abomasnow", statMultiplier: 6.0, extraSkillIds: ["iceBeam", "iceHammer", "avalanche"] },
  },
  astralSpire: {
    id: "astralSpire",
    name: "Astral Spire",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 11,
    enemySpeciesIds: ["natu", "spoink", "ralts", "abra"],
    floorEnemies: {
      1: ["natu"],
      2: ["natu", "spoink"],
      3: ["spoink", "ralts"],
      4: ["ralts", "natu"],
      5: ["natu", "abra"],
      6: ["abra", "spoink"],
      7: ["spoink", "ralts"],
      8: ["ralts", "abra", "natu"],
      9: ["natu", "spoink", "abra"],
      10: ["spoink", "ralts", "natu"],
      11: ["natu", "spoink", "ralts", "abra"],
    },
    difficulty: 2.3,
    itemsPerFloor: 3,
    unlockClears: 9,
    description: "B1F~B11F. Psychic types guard the spire!",
    boss: { speciesId: "spoink", name: "Cosmic Grumpig", statMultiplier: 5.5, extraSkillIds: ["psychic", "psyshock", "zenHeadbutt"] },
  },
  shadowAlley: {
    id: "shadowAlley",
    name: "Shadow Alley",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 11,
    enemySpeciesIds: ["stunky", "purrloin", "poochyena", "absol"],
    floorEnemies: {
      1: ["stunky"],
      2: ["stunky", "purrloin"],
      3: ["purrloin", "poochyena"],
      4: ["poochyena", "stunky"],
      5: ["stunky", "absol"],
      6: ["absol", "purrloin"],
      7: ["purrloin", "poochyena"],
      8: ["poochyena", "absol", "stunky"],
      9: ["stunky", "purrloin", "absol"],
      10: ["absol", "poochyena", "purrloin"],
      11: ["stunky", "purrloin", "poochyena", "absol"],
    },
    difficulty: 2.4,
    itemsPerFloor: 3,
    unlockClears: 10,
    description: "B1F~B11F. Dark types stalk the shadows!",
    boss: { speciesId: "stunky", name: "Shadow Skuntank", statMultiplier: 5.8, extraSkillIds: ["darkPulse", "foulPlay", "sludgeBomb"] },
  },
  galeCliffs: {
    id: "galeCliffs",
    name: "Gale Cliffs",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 11,
    enemySpeciesIds: ["pidove", "rufflet", "starly", "murkrow"],
    floorEnemies: {
      1: ["pidove"],
      2: ["pidove", "rufflet"],
      3: ["rufflet", "starly"],
      4: ["starly", "pidove"],
      5: ["pidove", "murkrow"],
      6: ["murkrow", "rufflet"],
      7: ["rufflet", "starly"],
      8: ["starly", "murkrow", "pidove"],
      9: ["pidove", "rufflet", "murkrow"],
      10: ["rufflet", "starly", "pidove"],
      11: ["pidove", "rufflet", "starly", "murkrow"],
    },
    difficulty: 2.2,
    itemsPerFloor: 3,
    unlockClears: 8,
    description: "B1F~B11F. Flying types soar above the cliffs!",
    boss: { speciesId: "rufflet", name: "Storm Braviary", statMultiplier: 5.5, extraSkillIds: ["bravebird", "hurricane", "aerialAce"] },
  },
  brawlDojo: {
    id: "brawlDojo",
    name: "Brawl Dojo",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 12,
    enemySpeciesIds: ["tyrogue", "crabrawler", "machop", "riolu"],
    floorEnemies: {
      1: ["tyrogue"],
      2: ["tyrogue", "crabrawler"],
      3: ["crabrawler", "machop"],
      4: ["machop", "tyrogue"],
      5: ["tyrogue", "riolu"],
      6: ["riolu", "crabrawler"],
      7: ["crabrawler", "machop"],
      8: ["machop", "riolu", "tyrogue"],
      9: ["tyrogue", "crabrawler", "riolu"],
      10: ["riolu", "machop", "crabrawler"],
      11: ["crabrawler", "tyrogue", "machop"],
      12: ["tyrogue", "crabrawler", "machop", "riolu"],
    },
    difficulty: 2.5,
    itemsPerFloor: 3,
    unlockClears: 10,
    description: "B1F~B12F. Fighting types train relentlessly!",
    boss: { speciesId: "crabrawler", name: "Grand Crabominable", statMultiplier: 6.0, extraSkillIds: ["hammerArm", "closeCombat", "drainPunch"] },
  },
  boulderPass: {
    id: "boulderPass",
    name: "Boulder Pass",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 12,
    enemySpeciesIds: ["roggenrola", "rockruff", "geodude", "larvitar"],
    floorEnemies: {
      1: ["roggenrola"],
      2: ["roggenrola", "rockruff"],
      3: ["rockruff", "geodude"],
      4: ["geodude", "roggenrola"],
      5: ["roggenrola", "larvitar"],
      6: ["larvitar", "rockruff"],
      7: ["rockruff", "geodude"],
      8: ["geodude", "larvitar", "roggenrola"],
      9: ["roggenrola", "rockruff", "larvitar"],
      10: ["larvitar", "geodude", "rockruff"],
      11: ["rockruff", "roggenrola", "geodude"],
      12: ["roggenrola", "rockruff", "geodude", "larvitar"],
    },
    difficulty: 2.6,
    itemsPerFloor: 3,
    unlockClears: 11,
    description: "B1F~B12F. Rock types block the pass!",
    boss: { speciesId: "rockruff", name: "Alpha Lycanroc", statMultiplier: 6.0, extraSkillIds: ["stoneEdge", "rockWrecker", "rockSlide"] },
  },
  tranquilGrove: {
    id: "tranquilGrove",
    name: "Tranquil Grove",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 10,
    enemySpeciesIds: ["lillipup", "minccino", "zigzagoon", "whismur"],
    floorEnemies: {
      1: ["lillipup"],
      2: ["lillipup", "minccino"],
      3: ["minccino", "zigzagoon"],
      4: ["zigzagoon", "lillipup"],
      5: ["lillipup", "whismur"],
      6: ["whismur", "minccino"],
      7: ["minccino", "zigzagoon"],
      8: ["zigzagoon", "whismur", "lillipup"],
      9: ["lillipup", "minccino", "whismur"],
      10: ["minccino", "zigzagoon", "lillipup", "whismur"],
    },
    difficulty: 1.8,
    itemsPerFloor: 4,
    unlockClears: 6,
    description: "B1F~B10F. Normal types roam the peaceful grove!",
    boss: { speciesId: "lillipup", name: "Noble Stoutland", statMultiplier: 5.0, extraSkillIds: ["triAttack", "hyperVoice", "headbutt"] },
  },
  fungalMarsh: {
    id: "fungalMarsh",
    name: "Fungal Marsh",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 13,
    enemySpeciesIds: ["foongus", "petilil", "oddish", "budew"],
    floorEnemies: {
      1: ["foongus"],
      2: ["foongus", "petilil"],
      3: ["petilil", "oddish"],
      4: ["oddish", "foongus"],
      5: ["foongus", "budew"],
      6: ["budew", "petilil"],
      7: ["petilil", "oddish"],
      8: ["oddish", "budew", "foongus"],
      9: ["foongus", "petilil", "budew"],
      10: ["budew", "oddish", "petilil"],
      11: ["petilil", "foongus", "oddish"],
      12: ["oddish", "budew", "foongus", "petilil"],
      13: ["foongus", "petilil", "oddish", "budew"],
    },
    difficulty: 2.7,
    itemsPerFloor: 3,
    unlockClears: 12,
    description: "B1F~B13F. Fungal spores fill the misty marsh!",
    boss: { speciesId: "foongus", name: "Spore Lord Amoonguss", statMultiplier: 6.0, extraSkillIds: ["energyBall", "grassKnot", "sludgeBomb"] },
  },
  destinyTower: {
    id: "destinyTower",
    name: "Destiny Tower",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 20,
    enemySpeciesIds: ["absol", "gible", "ralts", "machop", "torkoal", "tentacool", "gastly", "snorunt", "bagon", "grimer", "beldum", "skarmory"],
    floorEnemies: {
      1: ["machop", "geodude"],
      2: ["machop", "aron"],
      3: ["aron", "torkoal"],
      4: ["torkoal", "grimer"],
      5: ["grimer", "tentacool"],
      6: ["tentacool", "gastly"],
      7: ["gastly", "snorunt"],
      8: ["snorunt", "ralts"],
      9: ["ralts", "absol"],
      10: ["absol", "bagon"],
      11: ["bagon", "gible"],
      12: ["gible", "machop", "torkoal"],
      13: ["torkoal", "gastly", "absol"],
      14: ["absol", "ralts", "grimer"],
      15: ["gible", "bagon", "snorunt"],
      16: ["gible", "absol", "torkoal"],
      17: ["gible", "ralts", "gastly"],
      18: ["absol", "gible", "bagon"],
      19: ["gible", "absol"],
      20: ["gible"],
    },
    difficulty: 3.5,
    itemsPerFloor: 2,
    unlockClears: 15,
    description: "B1F~B20F. All types. The final challenge!",
    boss: { speciesId: "gible", name: "Apex Garchomp", statMultiplier: 7.0, extraSkillIds: ["dracoMeteor", "earthPower", "fireBlast"] },
  },
};

/** Get dungeon by ID */
export function getDungeon(id: string): DungeonDef {
  return DUNGEONS[id] ?? DUNGEONS.beachCave;
}

/** Get all unlocked dungeons given total clears */
export function getUnlockedDungeons(totalClears: number): DungeonDef[] {
  return Object.values(DUNGEONS).filter(d => d.unlockClears <= totalClears);
}

/** Get floor enemies for a specific dungeon+floor */
export function getDungeonFloorEnemies(dungeon: DungeonDef, floor: number): string[] {
  return dungeon.floorEnemies[floor] ?? dungeon.enemySpeciesIds;
}
