/**
 * Dungeon definitions — each dungeon has its own tileset, enemy pool, and floor count.
 */

export interface BossDef {
  speciesId: string;
  name: string;
  statMultiplier: number; // e.g. 2.5 means 2.5x base stats
  extraSkillIds?: string[];
}

export interface DungeonDef {
  id: string;
  name: string;
  tilesetPath: string;      // path to tileset PNG
  tilesetKey: string;        // Phaser asset key
  floors: number;            // total floors
  enemySpeciesIds: string[]; // species IDs from SPECIES record
  /** Per-floor enemy distribution: floorIndex (1-based) → species IDs */
  floorEnemies: Record<number, string[]>;
  /** Difficulty scaling: multiplier applied to enemy stats */
  difficulty: number;
  /** Items per floor */
  itemsPerFloor: number;
  /** Unlock requirement: min total clears */
  unlockClears: number;
  /** Description shown in hub */
  description: string;
  /** Boss on final floor (optional) */
  boss?: BossDef;
}

export const DUNGEONS: Record<string, DungeonDef> = {
  beachCave: {
    id: "beachCave",
    name: "Beach Cave",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 5,
    enemySpeciesIds: ["zubat", "shellos", "corsola", "geodude"],
    floorEnemies: {
      1: ["zubat"],
      2: ["zubat", "shellos"],
      3: ["zubat", "shellos", "corsola"],
      4: ["shellos", "corsola", "geodude"],
      5: ["corsola", "geodude"],
    },
    difficulty: 1.0,
    itemsPerFloor: 3,
    unlockClears: 0,
    description: "B1F~B5F. Water and Rock types.",
    boss: { speciesId: "corsola", name: "Giant Corsola", statMultiplier: 2.5 },
  },
  thunderwaveCave: {
    id: "thunderwaveCave",
    name: "Thunderwave Cave",
    tilesetPath: "tilesets/ThunderwaveCave/tileset_0.png",
    tilesetKey: "thunderwave-tiles",
    floors: 6,
    enemySpeciesIds: ["voltorb", "magnemite", "pikachu"],
    floorEnemies: {
      1: ["voltorb"],
      2: ["voltorb", "magnemite"],
      3: ["voltorb", "magnemite"],
      4: ["magnemite", "pikachu"],
      5: ["magnemite", "pikachu"],
      6: ["pikachu"],
    },
    difficulty: 1.3,
    itemsPerFloor: 3,
    unlockClears: 1,
    description: "B1F~B6F. Electric types. Harder!",
    boss: { speciesId: "pikachu", name: "Alpha Pikachu", statMultiplier: 3.0 },
  },
  tinyWoods: {
    id: "tinyWoods",
    name: "Tiny Woods",
    tilesetPath: "tilesets/TinyWoods/tileset_0.png",
    tilesetKey: "tinywoods-tiles",
    floors: 4,
    enemySpeciesIds: ["caterpie", "pidgey"],
    floorEnemies: {
      1: ["caterpie"],
      2: ["caterpie", "pidgey"],
      3: ["pidgey", "caterpie"],
      4: ["pidgey"],
    },
    difficulty: 0.8,
    itemsPerFloor: 4,
    unlockClears: 0,
    description: "B1F~B4F. Bug and Flying. Easy!",
    boss: { speciesId: "pidgey", name: "Fierce Pidgey", statMultiplier: 2.0 },
  },
  mtSteel: {
    id: "mtSteel",
    name: "Mt. Steel",
    tilesetPath: "tilesets/ThunderwaveCave/tileset_0.png",
    tilesetKey: "thunderwave-tiles",
    floors: 7,
    enemySpeciesIds: ["aron", "meditite", "machop"],
    floorEnemies: {
      1: ["aron"],
      2: ["aron", "meditite"],
      3: ["meditite", "aron"],
      4: ["meditite", "machop"],
      5: ["machop", "aron"],
      6: ["machop", "meditite"],
      7: ["machop"],
    },
    difficulty: 1.5,
    itemsPerFloor: 3,
    unlockClears: 2,
    description: "B1F~B7F. Steel and Fighting. Very tough!",
    boss: { speciesId: "machop", name: "Champion Machop", statMultiplier: 3.5 },
  },
  skyTower: {
    id: "skyTower",
    name: "Sky Tower",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 8,
    enemySpeciesIds: ["gastly", "drowzee", "snorunt"],
    floorEnemies: {
      1: ["gastly"],
      2: ["gastly", "drowzee"],
      3: ["drowzee", "gastly"],
      4: ["drowzee", "snorunt"],
      5: ["snorunt", "gastly"],
      6: ["gastly", "drowzee", "snorunt"],
      7: ["snorunt", "drowzee"],
      8: ["gastly", "snorunt"],
    },
    difficulty: 1.8,
    itemsPerFloor: 3,
    unlockClears: 3,
    description: "B1F~B8F. Ghost, Psychic, Ice. Dangerous!",
    boss: { speciesId: "gastly", name: "Phantom Gastly", statMultiplier: 4.0 },
  },
  frostyForest: {
    id: "frostyForest",
    name: "Frosty Forest",
    tilesetPath: "tilesets/TinyWoods/tileset_0.png",
    tilesetKey: "tinywoods-tiles",
    floors: 10,
    enemySpeciesIds: ["snorunt", "shellos", "zubat", "drowzee"],
    floorEnemies: {
      1: ["snorunt"],
      2: ["snorunt", "shellos"],
      3: ["shellos", "zubat"],
      4: ["zubat", "snorunt"],
      5: ["snorunt", "drowzee"],
      6: ["drowzee", "zubat"],
      7: ["drowzee", "snorunt", "zubat"],
      8: ["snorunt", "drowzee"],
      9: ["drowzee", "snorunt"],
      10: ["snorunt"],
    },
    difficulty: 2.0,
    itemsPerFloor: 4,
    unlockClears: 5,
    description: "B1F~B10F. Ice and Psychic. The ultimate challenge!",
    boss: { speciesId: "snorunt", name: "Frost King Snorunt", statMultiplier: 4.5 },
  },
  magmaCavern: {
    id: "magmaCavern",
    name: "Magma Cavern",
    tilesetPath: "tilesets/ThunderwaveCave/tileset_0.png",
    tilesetKey: "thunderwave-tiles",
    floors: 12,
    enemySpeciesIds: ["numel", "slugma", "torkoal", "geodude", "aron"],
    floorEnemies: {
      1: ["numel"],
      2: ["numel", "slugma"],
      3: ["slugma", "numel"],
      4: ["slugma", "geodude"],
      5: ["numel", "geodude", "slugma"],
      6: ["geodude", "torkoal"],
      7: ["torkoal", "slugma"],
      8: ["torkoal", "aron", "numel"],
      9: ["aron", "torkoal"],
      10: ["torkoal", "aron", "slugma"],
      11: ["torkoal", "numel"],
      12: ["torkoal"],
    },
    difficulty: 2.2,
    itemsPerFloor: 3,
    unlockClears: 7,
    description: "B1F~B12F. Fire and Ground. Volcanic inferno!",
    boss: { speciesId: "torkoal", name: "Volcanic Torkoal", statMultiplier: 5.0 },
  },
  sinisterWoods: {
    id: "sinisterWoods",
    name: "Sinister Woods",
    tilesetPath: "tilesets/TinyWoods/tileset_0.png",
    tilesetKey: "tinywoods-tiles",
    floors: 14,
    enemySpeciesIds: ["murkrow", "sableye", "absol", "gastly", "drowzee", "poochyena"],
    floorEnemies: {
      1: ["poochyena"],
      2: ["poochyena", "murkrow"],
      3: ["murkrow", "sableye"],
      4: ["sableye", "gastly"],
      5: ["poochyena", "gastly"],
      6: ["gastly", "sableye"],
      7: ["sableye", "drowzee", "murkrow"],
      8: ["drowzee", "gastly"],
      9: ["murkrow", "absol"],
      10: ["absol", "sableye"],
      11: ["absol", "gastly", "murkrow"],
      12: ["absol", "drowzee"],
      13: ["absol", "sableye"],
      14: ["absol"],
    },
    difficulty: 2.5,
    itemsPerFloor: 3,
    unlockClears: 8,
    description: "B1F~B14F. Dark and Ghost. The abyss awaits!",
    boss: { speciesId: "absol", name: "Shadow Absol", statMultiplier: 5.5 },
  },
  overgrownForest: {
    id: "overgrownForest",
    name: "Overgrown Forest",
    tilesetPath: "tilesets/TinyWoods/tileset_0.png",
    tilesetKey: "tinywoods-tiles",
    floors: 12,
    enemySpeciesIds: ["chikorita", "bellsprout", "shroomish", "caterpie", "pidgey"],
    floorEnemies: {
      1: ["chikorita"],
      2: ["chikorita", "bellsprout"],
      3: ["bellsprout", "caterpie"],
      4: ["caterpie", "chikorita"],
      5: ["bellsprout", "shroomish"],
      6: ["shroomish", "chikorita"],
      7: ["shroomish", "pidgey", "bellsprout"],
      8: ["pidgey", "shroomish"],
      9: ["shroomish", "bellsprout", "chikorita"],
      10: ["shroomish", "pidgey"],
      11: ["shroomish", "bellsprout"],
      12: ["shroomish"],
    },
    difficulty: 2.3,
    itemsPerFloor: 4,
    unlockClears: 9,
    description: "B1F~B12F. Grass and Bug. Nature's wrath!",
    boss: { speciesId: "shroomish", name: "Ancient Breloom", statMultiplier: 5.0 },
  },
  toxicSwamp: {
    id: "toxicSwamp",
    name: "Toxic Swamp",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 14,
    enemySpeciesIds: ["grimer", "nidoranM", "tentacool", "bellsprout", "zubat"],
    floorEnemies: {
      1: ["grimer"],
      2: ["grimer", "nidoranM"],
      3: ["nidoranM", "grimer"],
      4: ["nidoranM", "zubat"],
      5: ["grimer", "tentacool"],
      6: ["tentacool", "nidoranM"],
      7: ["tentacool", "bellsprout", "grimer"],
      8: ["bellsprout", "tentacool"],
      9: ["grimer", "nidoranM", "tentacool"],
      10: ["tentacool", "bellsprout"],
      11: ["nidoranM", "grimer"],
      12: ["grimer", "tentacool"],
      13: ["grimer", "nidoranM"],
      14: ["grimer"],
    },
    difficulty: 2.6,
    itemsPerFloor: 3,
    unlockClears: 10,
    description: "B1F~B14F. Poison and Water. Toxic miasma!",
    boss: { speciesId: "grimer", name: "Toxic Muk", statMultiplier: 5.5 },
  },
  moonlitCave: {
    id: "moonlitCave",
    name: "Moonlit Cave",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 10,
    enemySpeciesIds: ["clefairy", "jigglypuff", "ralts", "drowzee", "snorunt"],
    floorEnemies: {
      1: ["clefairy"],
      2: ["clefairy", "jigglypuff"],
      3: ["jigglypuff", "clefairy"],
      4: ["jigglypuff", "ralts"],
      5: ["ralts", "clefairy"],
      6: ["ralts", "drowzee", "jigglypuff"],
      7: ["drowzee", "ralts"],
      8: ["ralts", "snorunt", "clefairy"],
      9: ["snorunt", "ralts"],
      10: ["ralts"],
    },
    difficulty: 2.4,
    itemsPerFloor: 4,
    unlockClears: 11,
    description: "B1F~B10F. Fairy and Psychic. Enchanted moonlight!",
    boss: { speciesId: "ralts", name: "Mystic Gardevoir", statMultiplier: 5.5 },
  },
  dragonsLair: {
    id: "dragonsLair",
    name: "Dragon's Lair",
    tilesetPath: "tilesets/ThunderwaveCave/tileset_0.png",
    tilesetKey: "thunderwave-tiles",
    floors: 16,
    enemySpeciesIds: ["dratini", "bagon", "gible", "geodude", "aron"],
    floorEnemies: {
      1: ["dratini"],
      2: ["dratini", "bagon"],
      3: ["bagon", "dratini"],
      4: ["bagon", "geodude"],
      5: ["dratini", "gible"],
      6: ["gible", "bagon"],
      7: ["gible", "dratini", "geodude"],
      8: ["geodude", "gible"],
      9: ["gible", "aron", "bagon"],
      10: ["aron", "gible"],
      11: ["gible", "bagon", "dratini"],
      12: ["bagon", "gible"],
      13: ["gible", "aron"],
      14: ["gible", "bagon"],
      15: ["gible", "dratini"],
      16: ["gible"],
    },
    difficulty: 3.0,
    itemsPerFloor: 3,
    unlockClears: 12,
    description: "B1F~B16F. Dragon types. The ultimate trial!",
    boss: { speciesId: "gible", name: "Elder Garchomp", statMultiplier: 6.0, extraSkillIds: ["dracoMeteor", "earthPower"] },
  },
  steelFortress: {
    id: "steelFortress",
    name: "Steel Fortress",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 14,
    enemySpeciesIds: ["aron", "beldum", "skarmory", "magnemite", "geodude"],
    floorEnemies: {
      1: ["aron", "geodude"],
      2: ["aron", "magnemite"],
      3: ["magnemite", "geodude"],
      4: ["aron", "beldum"],
      5: ["beldum", "magnemite"],
      6: ["beldum", "skarmory"],
      7: ["skarmory", "aron"],
      8: ["skarmory", "beldum"],
      9: ["beldum", "skarmory", "aron"],
      10: ["skarmory", "beldum", "magnemite"],
      11: ["beldum", "skarmory"],
      12: ["skarmory", "beldum"],
      13: ["beldum", "skarmory"],
      14: ["skarmory"],
    },
    difficulty: 2.8,
    itemsPerFloor: 3,
    unlockClears: 13,
    description: "B1F~B14F. Steel types. Cold iron walls!",
    boss: { speciesId: "beldum", name: "Iron Metagross", statMultiplier: 6.0, extraSkillIds: ["flashCannon", "bulletPunch"] },
  },
  buriedRuins: {
    id: "buriedRuins",
    name: "Buried Ruins",
    tilesetPath: "tilesets/ThunderwaveCave/tileset_0.png",
    tilesetKey: "thunderwave-tiles",
    floors: 12,
    enemySpeciesIds: ["sandshrew", "trapinch", "phanpy", "geodude", "numel"],
    floorEnemies: {
      1: ["sandshrew", "geodude"],
      2: ["sandshrew", "phanpy"],
      3: ["geodude", "phanpy"],
      4: ["phanpy", "trapinch"],
      5: ["trapinch", "sandshrew"],
      6: ["trapinch", "numel"],
      7: ["numel", "sandshrew"],
      8: ["sandshrew", "trapinch", "phanpy"],
      9: ["trapinch", "phanpy", "numel"],
      10: ["trapinch", "phanpy"],
      11: ["trapinch", "sandshrew"],
      12: ["trapinch"],
    },
    difficulty: 2.5,
    itemsPerFloor: 3,
    unlockClears: 14,
    description: "B1F~B12F. Ground types. Ancient desert ruins!",
    boss: { speciesId: "trapinch", name: "Ancient Flygon", statMultiplier: 5.5, extraSkillIds: ["earthPower", "sandTomb"] },
  },
  stormySea: {
    id: "stormySea",
    name: "Stormy Sea",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 18,
    enemySpeciesIds: ["horsea", "lotad", "carvanha", "shellos", "corsola", "tentacool"],
    floorEnemies: {
      1: ["shellos", "lotad"],
      2: ["shellos", "horsea"],
      3: ["horsea", "lotad"],
      4: ["lotad", "corsola"],
      5: ["corsola", "horsea"],
      6: ["horsea", "tentacool"],
      7: ["tentacool", "carvanha"],
      8: ["carvanha", "horsea"],
      9: ["carvanha", "lotad"],
      10: ["carvanha", "tentacool", "horsea"],
      11: ["horsea", "carvanha", "corsola"],
      12: ["tentacool", "carvanha"],
      13: ["carvanha", "horsea"],
      14: ["horsea", "carvanha", "tentacool"],
      15: ["carvanha", "horsea"],
      16: ["carvanha", "tentacool"],
      17: ["carvanha", "horsea"],
      18: ["carvanha"],
    },
    difficulty: 2.7,
    itemsPerFloor: 3,
    unlockClears: 10,
    description: "B1F~B18F. Water/Dark. Raging ocean depths!",
    boss: { speciesId: "carvanha", name: "Abyssal Sharpedo", statMultiplier: 5.5, extraSkillIds: ["darkPulse", "brine"] },
  },
  ampPlains: {
    id: "ampPlains",
    name: "Amp Plains",
    tilesetPath: "tilesets/ThunderwaveCave/tileset_0.png",
    tilesetKey: "thunderwave-tiles",
    floors: 10,
    enemySpeciesIds: ["elekid", "mareep", "pikachu", "voltorb", "magnemite"],
    floorEnemies: {
      1: ["mareep", "voltorb"],
      2: ["mareep", "pikachu"],
      3: ["pikachu", "magnemite"],
      4: ["magnemite", "elekid"],
      5: ["elekid", "mareep"],
      6: ["elekid", "pikachu"],
      7: ["pikachu", "voltorb", "elekid"],
      8: ["elekid", "mareep", "magnemite"],
      9: ["elekid", "pikachu"],
      10: ["elekid"],
    },
    difficulty: 2.2,
    itemsPerFloor: 3,
    unlockClears: 6,
    description: "B1F~B10F. Electric types. Thunder crackles!",
    boss: { speciesId: "elekid", name: "Storm Electivire", statMultiplier: 5.0, extraSkillIds: ["thunderbolt", "thunderPunch"] },
  },
  destinyTower: {
    id: "destinyTower",
    name: "Destiny Tower",
    tilesetPath: "tilesets/BeachCave/tileset_0.png",
    tilesetKey: "beachcave-tiles",
    floors: 20,
    enemySpeciesIds: ["absol", "gible", "ralts", "machop", "torkoal", "tentacool", "gastly", "snorunt", "bagon", "grimer", "beldum", "skarmory"],
    floorEnemies: {
      1: ["machop", "geodude"],
      2: ["machop", "aron"],
      3: ["aron", "torkoal"],
      4: ["torkoal", "grimer"],
      5: ["grimer", "tentacool"],
      6: ["tentacool", "gastly"],
      7: ["gastly", "snorunt"],
      8: ["snorunt", "ralts"],
      9: ["ralts", "absol"],
      10: ["absol", "bagon"],
      11: ["bagon", "gible"],
      12: ["gible", "machop", "torkoal"],
      13: ["torkoal", "gastly", "absol"],
      14: ["absol", "ralts", "grimer"],
      15: ["gible", "bagon", "snorunt"],
      16: ["gible", "absol", "torkoal"],
      17: ["gible", "ralts", "gastly"],
      18: ["absol", "gible", "bagon"],
      19: ["gible", "absol"],
      20: ["gible"],
    },
    difficulty: 3.5,
    itemsPerFloor: 2,
    unlockClears: 15,
    description: "B1F~B20F. All types. The final challenge!",
    boss: { speciesId: "gible", name: "Apex Garchomp", statMultiplier: 7.0, extraSkillIds: ["dracoMeteor", "earthPower", "fireBlast"] },
  },
};

/** Get dungeon by ID */
export function getDungeon(id: string): DungeonDef {
  return DUNGEONS[id] ?? DUNGEONS.beachCave;
}

/** Get all unlocked dungeons given total clears */
export function getUnlockedDungeons(totalClears: number): DungeonDef[] {
  return Object.values(DUNGEONS).filter(d => d.unlockClears <= totalClears);
}

/** Get floor enemies for a specific dungeon+floor */
export function getDungeonFloorEnemies(dungeon: DungeonDef, floor: number): string[] {
  return dungeon.floorEnemies[floor] ?? dungeon.enemySpeciesIds;
}
