/**
 * Evolution system — certain Pokemon can evolve at specific levels.
 * Evolution grants stat bonuses and may add new skills.
 */

export interface EvolutionDef {
  from: string;       // species ID
  to: string;         // evolved species ID (reuses from or new key)
  level: number;      // minimum level to evolve
  newName: string;    // display name after evolution
  hpBonus: number;    // bonus HP on evolution
  atkBonus: number;   // bonus ATK
  defBonus: number;   // bonus DEF
  newSkillId?: string; // optional new skill learned
}

export const EVOLUTIONS: EvolutionDef[] = [
  { from: "mudkip", to: "marshtomp", level: 16, newName: "Marshtomp", hpBonus: 15, atkBonus: 4, defBonus: 3, newSkillId: "surf" },
  { from: "pikachu", to: "raichu", level: 16, newName: "Raichu", hpBonus: 10, atkBonus: 5, defBonus: 2, newSkillId: "thunderShock" },
  { from: "machop", to: "machoke", level: 16, newName: "Machoke", hpBonus: 15, atkBonus: 5, defBonus: 3, newSkillId: "focusPunch" },
  { from: "geodude", to: "graveler", level: 16, newName: "Graveler", hpBonus: 12, atkBonus: 3, defBonus: 5, newSkillId: "rockThrow" },
  { from: "gastly", to: "haunter", level: 16, newName: "Haunter", hpBonus: 8, atkBonus: 6, defBonus: 2, newSkillId: "shadowBall" },
  { from: "caterpie", to: "butterfree", level: 10, newName: "Butterfree", hpBonus: 12, atkBonus: 4, defBonus: 3, newSkillId: "gust" },
  { from: "pidgey", to: "pidgeotto", level: 14, newName: "Pidgeotto", hpBonus: 10, atkBonus: 4, defBonus: 3, newSkillId: "wingAttack" },
  { from: "aron", to: "lairon", level: 16, newName: "Lairon", hpBonus: 15, atkBonus: 4, defBonus: 6, newSkillId: "ironDefense" },
  { from: "drowzee", to: "hypno", level: 16, newName: "Hypno", hpBonus: 12, atkBonus: 5, defBonus: 4, newSkillId: "psybeam" },
  { from: "charmander", to: "charmeleon", level: 16, newName: "Charmeleon", hpBonus: 12, atkBonus: 5, defBonus: 3, newSkillId: "flamethrower" },
  { from: "eevee", to: "espeon", level: 16, newName: "Espeon", hpBonus: 10, atkBonus: 5, defBonus: 4, newSkillId: "confusion" },
  { from: "slugma", to: "magcargo", level: 16, newName: "Magcargo", hpBonus: 15, atkBonus: 4, defBonus: 6, newSkillId: "lavaSurf" },
  { from: "numel", to: "camerupt", level: 16, newName: "Camerupt", hpBonus: 15, atkBonus: 5, defBonus: 4, newSkillId: "earthPower" },
  { from: "chikorita", to: "bayleef", level: 16, newName: "Bayleef", hpBonus: 12, atkBonus: 3, defBonus: 4, newSkillId: "razorLeaf" },
  { from: "bellsprout", to: "weepinbell", level: 16, newName: "Weepinbell", hpBonus: 10, atkBonus: 5, defBonus: 2, newSkillId: "seedBomb" },
  { from: "shroomish", to: "breloom", level: 16, newName: "Breloom", hpBonus: 12, atkBonus: 6, defBonus: 3, newSkillId: "focusPunch" },
  { from: "snorunt", to: "glalie", level: 16, newName: "Glalie", hpBonus: 12, atkBonus: 5, defBonus: 5, newSkillId: "iceBeam" },
  { from: "grimer", to: "muk", level: 16, newName: "Muk", hpBonus: 15, atkBonus: 5, defBonus: 4, newSkillId: "venoshock" },
  { from: "nidoranM", to: "nidorino", level: 16, newName: "Nidorino", hpBonus: 12, atkBonus: 6, defBonus: 3, newSkillId: "sludgeBomb" },
  { from: "tentacool", to: "tentacruel", level: 16, newName: "Tentacruel", hpBonus: 14, atkBonus: 5, defBonus: 5, newSkillId: "venoshock" },
  { from: "clefairy", to: "clefable", level: 16, newName: "Clefable", hpBonus: 15, atkBonus: 4, defBonus: 5, newSkillId: "moonblast" },
  { from: "jigglypuff", to: "wigglytuff", level: 16, newName: "Wigglytuff", hpBonus: 18, atkBonus: 3, defBonus: 4, newSkillId: "dazzlingGleam" },
  { from: "ralts", to: "kirlia", level: 16, newName: "Kirlia", hpBonus: 10, atkBonus: 7, defBonus: 3, newSkillId: "moonblast" },
  { from: "dratini", to: "dragonair", level: 16, newName: "Dragonair", hpBonus: 12, atkBonus: 6, defBonus: 4, newSkillId: "dragonPulse" },
  { from: "bagon", to: "shelgon", level: 16, newName: "Shelgon", hpBonus: 15, atkBonus: 5, defBonus: 6, newSkillId: "dracoMeteor" },
  { from: "gible", to: "gabite", level: 16, newName: "Gabite", hpBonus: 14, atkBonus: 7, defBonus: 4, newSkillId: "dracoMeteor" },
  { from: "poochyena", to: "mightyena", level: 16, newName: "Mightyena", hpBonus: 14, atkBonus: 6, defBonus: 4, newSkillId: "darkPulse" },
  { from: "beldum", to: "metang", level: 16, newName: "Metang", hpBonus: 16, atkBonus: 5, defBonus: 7, newSkillId: "flashCannon" },
  { from: "aron", to: "lairon", level: 16, newName: "Lairon", hpBonus: 18, atkBonus: 5, defBonus: 8, newSkillId: "ironHead" },
  { from: "sandshrew", to: "sandslash", level: 16, newName: "Sandslash", hpBonus: 14, atkBonus: 6, defBonus: 6, newSkillId: "earthPower" },
  { from: "trapinch", to: "vibrava", level: 16, newName: "Vibrava", hpBonus: 12, atkBonus: 7, defBonus: 4, newSkillId: "earthPower" },
  { from: "phanpy", to: "donphan", level: 16, newName: "Donphan", hpBonus: 16, atkBonus: 6, defBonus: 6, newSkillId: "earthPower" },
  { from: "horsea", to: "seadra", level: 16, newName: "Seadra", hpBonus: 12, atkBonus: 7, defBonus: 5, newSkillId: "brine" },
  { from: "lotad", to: "lombre", level: 16, newName: "Lombre", hpBonus: 14, atkBonus: 5, defBonus: 5, newSkillId: "waterPulse" },
  { from: "carvanha", to: "sharpedo", level: 16, newName: "Sharpedo", hpBonus: 12, atkBonus: 8, defBonus: 3, newSkillId: "darkPulse" },
  { from: "elekid", to: "electabuzz", level: 16, newName: "Electabuzz", hpBonus: 14, atkBonus: 7, defBonus: 4, newSkillId: "thunderbolt" },
  { from: "mareep", to: "flaaffy", level: 16, newName: "Flaaffy", hpBonus: 14, atkBonus: 6, defBonus: 5, newSkillId: "thunderbolt" },
  { from: "wurmple", to: "silcoon", level: 10, newName: "Silcoon", hpBonus: 8, atkBonus: 3, defBonus: 5, newSkillId: "signalBeam" },
  { from: "spinarak", to: "ariados", level: 16, newName: "Ariados", hpBonus: 14, atkBonus: 6, defBonus: 5, newSkillId: "signalBeam" },
  { from: "abra", to: "kadabra", level: 14, newName: "Kadabra", hpBonus: 10, atkBonus: 8, defBonus: 4, newSkillId: "psychic" },
  { from: "natu", to: "xatu", level: 16, newName: "Xatu", hpBonus: 14, atkBonus: 6, defBonus: 5, newSkillId: "psychic" },
  { from: "houndour", to: "houndoom", level: 16, newName: "Houndoom", hpBonus: 14, atkBonus: 6, defBonus: 4, newSkillId: "flamethrower" },
  { from: "sneasel", to: "weavile", level: 16, newName: "Weavile", hpBonus: 12, atkBonus: 8, defBonus: 4, newSkillId: "darkPulse" },
  { from: "taillow", to: "swellow", level: 16, newName: "Swellow", hpBonus: 12, atkBonus: 7, defBonus: 4, newSkillId: "braveBird" },
  { from: "starly", to: "staravia", level: 14, newName: "Staravia", hpBonus: 10, atkBonus: 6, defBonus: 4, newSkillId: "airSlash" },
  { from: "makuhita", to: "hariyama", level: 16, newName: "Hariyama", hpBonus: 18, atkBonus: 6, defBonus: 4, newSkillId: "focusPunch" },
  { from: "riolu", to: "lucario", level: 14, newName: "Lucario", hpBonus: 12, atkBonus: 8, defBonus: 5, newSkillId: "auraSphere" },
  { from: "larvitar", to: "pupitar", level: 16, newName: "Pupitar", hpBonus: 15, atkBonus: 5, defBonus: 7, newSkillId: "stoneEdge" },
  { from: "swinub", to: "piloswine", level: 16, newName: "Piloswine", hpBonus: 16, atkBonus: 5, defBonus: 5, newSkillId: "avalanche" },
  { from: "spheal", to: "sealeo", level: 16, newName: "Sealeo", hpBonus: 15, atkBonus: 5, defBonus: 6, newSkillId: "iceBeam" },
  { from: "zigzagoon", to: "linoone", level: 14, newName: "Linoone", hpBonus: 12, atkBonus: 6, defBonus: 4, newSkillId: "headbutt" },
  { from: "whismur", to: "loudred", level: 16, newName: "Loudred", hpBonus: 14, atkBonus: 6, defBonus: 4, newSkillId: "hyperVoice" },
  { from: "oddish", to: "gloom", level: 14, newName: "Gloom", hpBonus: 12, atkBonus: 5, defBonus: 5, newSkillId: "petalDance" },
  { from: "budew", to: "roselia", level: 14, newName: "Roselia", hpBonus: 10, atkBonus: 7, defBonus: 4, newSkillId: "energyBall" },
  { from: "vulpix", to: "ninetales", level: 14, newName: "Ninetales", hpBonus: 12, atkBonus: 8, defBonus: 5, newSkillId: "flamethrower" },
  { from: "ponyta", to: "rapidash", level: 14, newName: "Rapidash", hpBonus: 14, atkBonus: 9, defBonus: 4, newSkillId: "fireBlast" },
  { from: "staryu", to: "starmie", level: 14, newName: "Starmie", hpBonus: 10, atkBonus: 8, defBonus: 5, newSkillId: "surf" },
  { from: "clamperl", to: "huntail", level: 14, newName: "Huntail", hpBonus: 12, atkBonus: 9, defBonus: 5, newSkillId: "surf" },
  { from: "shinx", to: "luxio", level: 14, newName: "Luxio", hpBonus: 12, atkBonus: 8, defBonus: 4, newSkillId: "wildCharge" },
  { from: "electrike", to: "manectric", level: 14, newName: "Manectric", hpBonus: 10, atkBonus: 9, defBonus: 4, newSkillId: "thunderbolt" },
  { from: "gulpin", to: "swalot", level: 14, newName: "Swalot", hpBonus: 15, atkBonus: 7, defBonus: 6, newSkillId: "sludgeBomb" },
  { from: "ekans", to: "arbok", level: 14, newName: "Arbok", hpBonus: 12, atkBonus: 9, defBonus: 4, newSkillId: "venoshock" },
  { from: "cubone", to: "marowak", level: 14, newName: "Marowak", hpBonus: 12, atkBonus: 9, defBonus: 5, newSkillId: "earthPower" },
  { from: "diglett", to: "dugtrio", level: 14, newName: "Dugtrio", hpBonus: 8, atkBonus: 10, defBonus: 3, newSkillId: "earthPower" },
  { from: "paras", to: "parasect", level: 14, newName: "Parasect", hpBonus: 12, atkBonus: 8, defBonus: 6, newSkillId: "xScissor" },
  { from: "venonat", to: "venomoth", level: 14, newName: "Venomoth", hpBonus: 10, atkBonus: 8, defBonus: 4, newSkillId: "signalBeam" },
  { from: "shieldon", to: "bastiodon", level: 14, newName: "Bastiodon", hpBonus: 15, atkBonus: 5, defBonus: 10, newSkillId: "flashCannon" },
  { from: "bronzor", to: "bronzong", level: 14, newName: "Bronzong", hpBonus: 12, atkBonus: 7, defBonus: 8, newSkillId: "flashCannon" },
  { from: "misdreavus", to: "mismagius", level: 14, newName: "Mismagius", hpBonus: 10, atkBonus: 9, defBonus: 4, newSkillId: "shadowBall" },
  { from: "duskull", to: "dusclops", level: 14, newName: "Dusclops", hpBonus: 14, atkBonus: 6, defBonus: 8, newSkillId: "shadowBall" },
  { from: "axew", to: "fraxure", level: 14, newName: "Fraxure", hpBonus: 12, atkBonus: 10, defBonus: 4, newSkillId: "dragonRush" },
  { from: "deino", to: "zweilous", level: 14, newName: "Zweilous", hpBonus: 14, atkBonus: 8, defBonus: 6, newSkillId: "dragonPulse" },
  { from: "snubbull", to: "granbull", level: 14, newName: "Granbull", hpBonus: 12, atkBonus: 10, defBonus: 5, newSkillId: "playRough" },
  { from: "togepi", to: "togetic", level: 14, newName: "Togetic", hpBonus: 10, atkBonus: 7, defBonus: 7, newSkillId: "moonblast" },
  { from: "snover", to: "abomasnow", level: 14, newName: "Abomasnow", hpBonus: 14, atkBonus: 8, defBonus: 6, newSkillId: "iceBeam" },
  { from: "bergmite", to: "avalugg", level: 14, newName: "Avalugg", hpBonus: 16, atkBonus: 6, defBonus: 10, newSkillId: "iceHammer" },
  { from: "spoink", to: "grumpig", level: 14, newName: "Grumpig", hpBonus: 12, atkBonus: 7, defBonus: 7, newSkillId: "psychic" },
  { from: "stunky", to: "skuntank", level: 14, newName: "Skuntank", hpBonus: 14, atkBonus: 8, defBonus: 6, newSkillId: "darkPulse" },
  { from: "purrloin", to: "liepard", level: 14, newName: "Liepard", hpBonus: 10, atkBonus: 10, defBonus: 4, newSkillId: "foulPlay" },
  { from: "pidove", to: "tranquill", level: 14, newName: "Tranquill", hpBonus: 10, atkBonus: 8, defBonus: 6, newSkillId: "hurricane" },
  { from: "rufflet", to: "braviary", level: 14, newName: "Braviary", hpBonus: 14, atkBonus: 10, defBonus: 4, newSkillId: "bravebird" },
  { from: "tyrogue", to: "hitmonchan", level: 14, newName: "Hitmonchan", hpBonus: 10, atkBonus: 10, defBonus: 6, newSkillId: "closeCombat" },
  { from: "crabrawler", to: "crabominable", level: 14, newName: "Crabominable", hpBonus: 16, atkBonus: 10, defBonus: 4, newSkillId: "hammerArm" },
  { from: "roggenrola", to: "boldore", level: 14, newName: "Boldore", hpBonus: 14, atkBonus: 8, defBonus: 8, newSkillId: "rockWrecker" },
  { from: "rockruff", to: "lycanroc", level: 14, newName: "Lycanroc", hpBonus: 10, atkBonus: 12, defBonus: 4, newSkillId: "stoneEdge" },
  { from: "lillipup", to: "herdier", level: 14, newName: "Herdier", hpBonus: 12, atkBonus: 8, defBonus: 6, newSkillId: "triAttack" },
  { from: "minccino", to: "cinccino", level: 14, newName: "Cinccino", hpBonus: 10, atkBonus: 8, defBonus: 6, newSkillId: "hyperVoice" },
  { from: "foongus", to: "amoonguss", level: 14, newName: "Amoonguss", hpBonus: 16, atkBonus: 6, defBonus: 8, newSkillId: "energyBall" },
  { from: "petilil", to: "lilligant", level: 14, newName: "Lilligant", hpBonus: 10, atkBonus: 10, defBonus: 4, newSkillId: "petalDance" },
  { from: "feebas", to: "milotic", level: 14, newName: "Milotic", hpBonus: 12, atkBonus: 8, defBonus: 8, newSkillId: "dive" },
  { from: "wailmer", to: "wailord", level: 14, newName: "Wailord", hpBonus: 20, atkBonus: 6, defBonus: 6, newSkillId: "brine" },
  { from: "litwick", to: "lampent", level: 14, newName: "Lampent", hpBonus: 10, atkBonus: 10, defBonus: 4, newSkillId: "heatWave" },
  { from: "growlithe", to: "arcanine", level: 14, newName: "Arcanine", hpBonus: 14, atkBonus: 10, defBonus: 6, newSkillId: "fireBlast" },
  { from: "joltik", to: "galvantula", level: 14, newName: "Galvantula", hpBonus: 10, atkBonus: 10, defBonus: 4, newSkillId: "wildCharge" },
  { from: "tynamo", to: "eelektrik", level: 14, newName: "Eelektrik", hpBonus: 12, atkBonus: 8, defBonus: 6, newSkillId: "wildCharge" },
  { from: "trubbish", to: "garbodor", level: 14, newName: "Garbodor", hpBonus: 16, atkBonus: 8, defBonus: 6, newSkillId: "gunkShot" },
  { from: "skorupi", to: "drapion", level: 14, newName: "Drapion", hpBonus: 12, atkBonus: 10, defBonus: 6, newSkillId: "sludgeBomb" },
  { from: "mudbray", to: "mudsdale", level: 14, newName: "Mudsdale", hpBonus: 14, atkBonus: 10, defBonus: 6, newSkillId: "highHorsepower" },
  { from: "hippopotas", to: "hippowdon", level: 14, newName: "Hippowdon", hpBonus: 16, atkBonus: 8, defBonus: 8, newSkillId: "earthPower" },
  { from: "dwebble", to: "crustle", level: 14, newName: "Crustle", hpBonus: 12, atkBonus: 8, defBonus: 10, newSkillId: "rockWrecker" },
  { from: "binacle", to: "barbaracle", level: 14, newName: "Barbaracle", hpBonus: 10, atkBonus: 12, defBonus: 6, newSkillId: "stoneEdge" },
  { from: "nincada", to: "ninjask", level: 14, newName: "Ninjask", hpBonus: 8, atkBonus: 12, defBonus: 4, newSkillId: "megahorn" },
  { from: "venipede", to: "whirlipede", level: 14, newName: "Whirlipede", hpBonus: 12, atkBonus: 8, defBonus: 8, newSkillId: "sludgeBomb" },
  { from: "mienfoo", to: "mienshao", level: 14, newName: "Mienshao", hpBonus: 10, atkBonus: 12, defBonus: 4, newSkillId: "superpower" },
  { from: "timburr", to: "gurdurr", level: 14, newName: "Gurdurr", hpBonus: 14, atkBonus: 10, defBonus: 6, newSkillId: "superpower" },
  { from: "klink", to: "klang", level: 14, newName: "Klang", hpBonus: 12, atkBonus: 8, defBonus: 8, newSkillId: "gearGrind" },
  { from: "ferroseed", to: "ferrothorn", level: 14, newName: "Ferrothorn", hpBonus: 14, atkBonus: 6, defBonus: 12, newSkillId: "flashCannon" },
  { from: "phantump", to: "trevenant", level: 14, newName: "Trevenant", hpBonus: 14, atkBonus: 10, defBonus: 6, newSkillId: "phantomForce" },
  { from: "honedge", to: "doublade", level: 14, newName: "Doublade", hpBonus: 10, atkBonus: 12, defBonus: 8, newSkillId: "shadowBall" },
  { from: "solosis", to: "duosion", level: 14, newName: "Duosion", hpBonus: 12, atkBonus: 10, defBonus: 4, newSkillId: "futuresight" },
  { from: "elgyem", to: "beheeyem", level: 14, newName: "Beheeyem", hpBonus: 14, atkBonus: 8, defBonus: 8, newSkillId: "futuresight" },
  { from: "cubchoo", to: "beartic", level: 14, newName: "Beartic", hpBonus: 16, atkBonus: 10, defBonus: 6, newSkillId: "iceBeam" },
  { from: "sandile", to: "krokorok", level: 14, newName: "Krokorok", hpBonus: 12, atkBonus: 10, defBonus: 8, newSkillId: "crunch" },
  { from: "inkay", to: "malamar", level: 14, newName: "Malamar", hpBonus: 12, atkBonus: 8, defBonus: 10, newSkillId: "knockOff" },
  { from: "spritzee", to: "aromatisse", level: 14, newName: "Aromatisse", hpBonus: 14, atkBonus: 6, defBonus: 10, newSkillId: "dazzlingGleam" },
  { from: "swirlix", to: "slurpuff", level: 14, newName: "Slurpuff", hpBonus: 12, atkBonus: 10, defBonus: 8, newSkillId: "dazzlingGleam" },
  { from: "goomy", to: "sliggoo", level: 14, newName: "Sliggoo", hpBonus: 14, atkBonus: 6, defBonus: 10, newSkillId: "outrage" },
  { from: "jangmoo", to: "hakamoo", level: 14, newName: "Hakamo-o", hpBonus: 12, atkBonus: 10, defBonus: 8, newSkillId: "dragonClaw" },
  { from: "noibat", to: "noivern", level: 14, newName: "Noivern", hpBonus: 10, atkBonus: 12, defBonus: 6, newSkillId: "airSlash" },
  { from: "vullaby", to: "mandibuzz", level: 14, newName: "Mandibuzz", hpBonus: 16, atkBonus: 4, defBonus: 10, newSkillId: "aerialAce" },
  { from: "stufful", to: "bewear", level: 14, newName: "Bewear", hpBonus: 16, atkBonus: 10, defBonus: 6, newSkillId: "bodySlam" },
  { from: "wimpod", to: "golisopod", level: 14, newName: "Golisopod", hpBonus: 14, atkBonus: 12, defBonus: 8, newSkillId: "waterfall" },
  { from: "tympole", to: "palpitoad", level: 14, newName: "Palpitoad", hpBonus: 14, atkBonus: 8, defBonus: 8, newSkillId: "surf" },
  { from: "salandit", to: "salazzle", level: 14, newName: "Salazzle", hpBonus: 10, atkBonus: 14, defBonus: 4, newSkillId: "fireWhip" },
  { from: "larvesta", to: "volcarona", level: 14, newName: "Volcarona", hpBonus: 12, atkBonus: 12, defBonus: 6, newSkillId: "heatWave" },
  { from: "fomantis", to: "lurantis", level: 14, newName: "Lurantis", hpBonus: 12, atkBonus: 12, defBonus: 6, newSkillId: "leafBlade" },
  { from: "morelull", to: "shiinotic", level: 14, newName: "Shiinotic", hpBonus: 14, atkBonus: 6, defBonus: 10, newSkillId: "leafStorm" },
  { from: "charjabug", to: "vikavolt", level: 14, newName: "Vikavolt", hpBonus: 12, atkBonus: 14, defBonus: 4, newSkillId: "thunderbolt" },
  { from: "helioptile", to: "heliolisk", level: 14, newName: "Heliolisk", hpBonus: 10, atkBonus: 14, defBonus: 4, newSkillId: "electricTerrain" },
  { from: "mareanie", to: "toxapex", level: 14, newName: "Toxapex", hpBonus: 14, atkBonus: 4, defBonus: 14, newSkillId: "poisonJab" },
  { from: "croagunk", to: "toxicroak", level: 14, newName: "Toxicroak", hpBonus: 12, atkBonus: 12, defBonus: 6, newSkillId: "drainPunch" },
  { from: "sandygast", to: "palossand", level: 14, newName: "Palossand", hpBonus: 14, atkBonus: 8, defBonus: 10, newSkillId: "scorchingSand" },
  { from: "silicobra", to: "sandaconda", level: 14, newName: "Sandaconda", hpBonus: 14, atkBonus: 10, defBonus: 8, newSkillId: "earthPower" },
  { from: "dewpider", to: "araquanid", level: 14, newName: "Araquanid", hpBonus: 14, atkBonus: 8, defBonus: 10, newSkillId: "lunge" },
  { from: "sizzlipede", to: "centiskorch", level: 14, newName: "Centiskorch", hpBonus: 12, atkBonus: 12, defBonus: 6, newSkillId: "fireWhip" },
  { from: "pancham", to: "pangoro", level: 14, newName: "Pangoro", hpBonus: 14, atkBonus: 12, defBonus: 4, newSkillId: "skyUppercut" },
  // Phase 106-108: Steel/Ghost/Psychic 4th
  { from: "drifloon", to: "drifblim", level: 14, newName: "Drifblim", hpBonus: 18, atkBonus: 6, defBonus: 4, newSkillId: "shadowBall" },
  { from: "golett", to: "golurk", level: 16, newName: "Golurk", hpBonus: 16, atkBonus: 10, defBonus: 8, newSkillId: "phantomForce" },
  { from: "hatenna", to: "hattrem", level: 14, newName: "Hattrem", hpBonus: 12, atkBonus: 8, defBonus: 6, newSkillId: "expandingForce" },
  // Phase 109-111: Ice/Dark/Fairy 4th
  { from: "vanillite", to: "vanillish", level: 14, newName: "Vanillish", hpBonus: 12, atkBonus: 8, defBonus: 4, newSkillId: "iceBeam" },
  { from: "snom", to: "frosmoth", level: 14, newName: "Frosmoth", hpBonus: 14, atkBonus: 10, defBonus: 6, newSkillId: "auroraBeam" },
  { from: "nickit", to: "thievul", level: 14, newName: "Thievul", hpBonus: 12, atkBonus: 8, defBonus: 6, newSkillId: "throatChop" },
  { from: "impidimp", to: "morgrem", level: 14, newName: "Morgrem", hpBonus: 12, atkBonus: 10, defBonus: 4, newSkillId: "throatChop" },
  { from: "milcery", to: "alcremie", level: 14, newName: "Alcremie", hpBonus: 14, atkBonus: 8, defBonus: 8, newSkillId: "playRough" },
  // Phase 112-114: Dragon/Flying/Normal 4th
  { from: "rookidee", to: "corvisquire", level: 14, newName: "Corvisquire", hpBonus: 12, atkBonus: 8, defBonus: 6, newSkillId: "braveBird" },
  { from: "archen", to: "archeops", level: 16, newName: "Archeops", hpBonus: 14, atkBonus: 12, defBonus: 4, newSkillId: "rockSlide" },
  { from: "wooloo", to: "dubwool", level: 14, newName: "Dubwool", hpBonus: 14, atkBonus: 6, defBonus: 10, newSkillId: "facade" },
  { from: "skwovet", to: "greedent", level: 14, newName: "Greedent", hpBonus: 16, atkBonus: 8, defBonus: 8, newSkillId: "facade" },
  // Phase 118-120: Water/Fire/Grass 5th
  { from: "chewtle", to: "drednaw", level: 14, newName: "Drednaw", hpBonus: 14, atkBonus: 10, defBonus: 8, newSkillId: "liquidation" },
  { from: "litleo", to: "pyroar", level: 14, newName: "Pyroar", hpBonus: 14, atkBonus: 10, defBonus: 4, newSkillId: "flamethrower" },
  { from: "torchic", to: "combusken", level: 14, newName: "Combusken", hpBonus: 12, atkBonus: 10, defBonus: 6, newSkillId: "blazeKick" },
  { from: "gossifleur", to: "eldegoss", level: 14, newName: "Eldegoss", hpBonus: 14, atkBonus: 6, defBonus: 10, newSkillId: "energyBall" },
  { from: "bounsweet", to: "steenee", level: 14, newName: "Steenee", hpBonus: 12, atkBonus: 10, defBonus: 6, newSkillId: "tropicalKick" },
  // Phase 121-123: Electric/Poison/Ground 5th
  { from: "yamper", to: "boltund", level: 14, newName: "Boltund", hpBonus: 12, atkBonus: 10, defBonus: 6, newSkillId: "wildCharge" },
  { from: "toxel", to: "toxtricity", level: 14, newName: "Toxtricity", hpBonus: 14, atkBonus: 12, defBonus: 4, newSkillId: "nuzzle" },
  { from: "skrelp", to: "dragalge", level: 14, newName: "Dragalge", hpBonus: 14, atkBonus: 10, defBonus: 8, newSkillId: "sludgeBomb" },
  { from: "drilbur", to: "excadrill", level: 14, newName: "Excadrill", hpBonus: 14, atkBonus: 12, defBonus: 8, newSkillId: "earthquake" },
  // Phase 124-126: Rock/Bug/Fighting 5th
  { from: "nacli", to: "naclstack", level: 24, newName: "Naclstack", hpBonus: 14, atkBonus: 8, defBonus: 10, newSkillId: "stoneEdge" },
  { from: "tyrunt", to: "tyrantrum", level: 39, newName: "Tyrantrum", hpBonus: 16, atkBonus: 12, defBonus: 8, newSkillId: "rockSlide" },
  { from: "blipbug", to: "dottler", level: 10, newName: "Dottler", hpBonus: 10, atkBonus: 6, defBonus: 8, newSkillId: "psychic" },
  { from: "cutiefly", to: "ribombee", level: 25, newName: "Ribombee", hpBonus: 12, atkBonus: 8, defBonus: 6, newSkillId: "dazzlingGleam" },
  { from: "clobbopus", to: "grapploct", level: 35, newName: "Grapploct", hpBonus: 14, atkBonus: 10, defBonus: 8, newSkillId: "superpower" },
  // Phase 127-129: Steel/Ghost/Psychic 5th
  { from: "tinkatink", to: "tinkatuff", level: 24, newName: "Tinkatuff", hpBonus: 12, atkBonus: 8, defBonus: 6, newSkillId: "flashCannon" },
  { from: "varoom", to: "revavroom", level: 40, newName: "Revavroom", hpBonus: 16, atkBonus: 12, defBonus: 8, newSkillId: "gearGrind" },
  { from: "greavard", to: "houndstone", level: 30, newName: "Houndstone", hpBonus: 14, atkBonus: 10, defBonus: 8, newSkillId: "phantomForce" },
  { from: "sinistea", to: "polteageist", level: 30, newName: "Polteageist", hpBonus: 12, atkBonus: 10, defBonus: 4, newSkillId: "shadowBall" },
  { from: "flittle", to: "espathra", level: 35, newName: "Espathra", hpBonus: 14, atkBonus: 10, defBonus: 6, newSkillId: "futuresight" },
  { from: "espurr", to: "meowstic", level: 25, newName: "Meowstic", hpBonus: 12, atkBonus: 8, defBonus: 8, newSkillId: "expandingForce" },
  // Phase 130-132: Ice/Dark/Fairy 5th
  { from: "cetoddle", to: "cetitan", level: 38, newName: "Cetitan", hpBonus: 20, atkBonus: 10, defBonus: 8, newSkillId: "iceBeam" },
  { from: "frigibax", to: "arctibax", level: 35, newName: "Arctibax", hpBonus: 16, atkBonus: 12, defBonus: 6, newSkillId: "dragonClaw" },
  { from: "zorua", to: "zoroark", level: 30, newName: "Zoroark", hpBonus: 14, atkBonus: 12, defBonus: 6, newSkillId: "nightSlash" },
  { from: "pawniard", to: "bisharp", level: 52, newName: "Bisharp", hpBonus: 16, atkBonus: 12, defBonus: 10, newSkillId: "ironHead" },
  { from: "fidough", to: "dachsbun", level: 26, newName: "Dachsbun", hpBonus: 14, atkBonus: 8, defBonus: 10, newSkillId: "playRough" },
  // Phase 133-135: Dragon/Flying/Normal 5th
  { from: "wingull", to: "pelipper", level: 25, newName: "Pelipper", hpBonus: 14, atkBonus: 8, defBonus: 10, newSkillId: "hurricane" },
  { from: "swablu", to: "altaria", level: 35, newName: "Altaria", hpBonus: 16, atkBonus: 10, defBonus: 8, newSkillId: "moonblast" },
  { from: "lechonk", to: "oinkologne", level: 18, newName: "Oinkologne", hpBonus: 12, atkBonus: 8, defBonus: 6, newSkillId: "hyperVoice" },
  { from: "tandemaus", to: "maushold", level: 25, newName: "Maushold", hpBonus: 14, atkBonus: 10, defBonus: 6, newSkillId: "hyperVoice" },
  // Phase 137-139: Water/Fire/Grass/Electric/Poison/Ground 6th
  { from: "buizel", to: "floatzel", level: 26, newName: "Floatzel", hpBonus: 14, atkBonus: 10, defBonus: 6, newSkillId: "liquidation" },
  { from: "finizen", to: "palafin", level: 38, newName: "Palafin", hpBonus: 18, atkBonus: 12, defBonus: 8, newSkillId: "liquidation" },
  { from: "fletchinder", to: "talonflame", level: 35, newName: "Talonflame", hpBonus: 14, atkBonus: 12, defBonus: 6, newSkillId: "braveBird" },
  { from: "smoliv", to: "dolliv", level: 25, newName: "Dolliv", hpBonus: 12, atkBonus: 8, defBonus: 6, newSkillId: "energyBall" },
  { from: "deerling", to: "sawsbuck", level: 34, newName: "Sawsbuck", hpBonus: 16, atkBonus: 10, defBonus: 8, newSkillId: "bodySlam" },
  { from: "glimmet", to: "glimmora", level: 35, newName: "Glimmora", hpBonus: 14, atkBonus: 10, defBonus: 8, newSkillId: "sludgeBomb" },
  { from: "koffing", to: "weezing", level: 35, newName: "Weezing", hpBonus: 16, atkBonus: 8, defBonus: 12, newSkillId: "sludgeBomb" },
  { from: "wooper", to: "quagsire", level: 20, newName: "Quagsire", hpBonus: 16, atkBonus: 8, defBonus: 8, newSkillId: "earthquake" },
  { from: "baltoy", to: "claydol", level: 36, newName: "Claydol", hpBonus: 14, atkBonus: 8, defBonus: 12, newSkillId: "psychic" },
  // Phase 140-142: Rock/Bug/Fighting/Steel/Ghost/Psychic 6th
  { from: "anorith", to: "armaldo", level: 40, newName: "Armaldo", hpBonus: 16, atkBonus: 12, defBonus: 8, newSkillId: "rockSlide" },
  { from: "surskit", to: "masquerain", level: 22, newName: "Masquerain", hpBonus: 12, atkBonus: 8, defBonus: 6, newSkillId: "silverWind" },
  { from: "scraggy", to: "scrafty", level: 39, newName: "Scrafty", hpBonus: 16, atkBonus: 10, defBonus: 10, newSkillId: "closeCombat" },
  { from: "mankey", to: "primeape", level: 28, newName: "Primeape", hpBonus: 14, atkBonus: 12, defBonus: 6, newSkillId: "closeCombat" },
  { from: "dreepy", to: "drakloak", level: 50, newName: "Drakloak", hpBonus: 14, atkBonus: 10, defBonus: 8, newSkillId: "dragonPulse" },
  { from: "munna", to: "musharna", level: 30, newName: "Musharna", hpBonus: 16, atkBonus: 8, defBonus: 10, newSkillId: "futuresight" },
  { from: "chingling", to: "chimecho", level: 20, newName: "Chimecho", hpBonus: 12, atkBonus: 8, defBonus: 6, newSkillId: "psychic" },
  // Phase 143-145: Ice/Dark/Fairy/Dragon/Flying/Normal 6th
  { from: "smoochum", to: "jynx", level: 30, newName: "Jynx", hpBonus: 16, atkBonus: 10, defBonus: 6, newSkillId: "iceBeam" },
  { from: "nuzleaf", to: "shiftry", level: 36, newName: "Shiftry", hpBonus: 14, atkBonus: 12, defBonus: 8, newSkillId: "leafStorm" },
  { from: "marill", to: "azumarill", level: 18, newName: "Azumarill", hpBonus: 18, atkBonus: 8, defBonus: 10, newSkillId: "waterPulse" },
  { from: "cleffa", to: "clefairy", level: 16, newName: "Clefairy", hpBonus: 12, atkBonus: 6, defBonus: 8, newSkillId: "dazzlingGleam" },
  { from: "applin", to: "flapple", level: 28, newName: "Flapple", hpBonus: 14, atkBonus: 12, defBonus: 6, newSkillId: "dragonPulse" },
  { from: "hoppip", to: "skiploom", level: 18, newName: "Skiploom", hpBonus: 12, atkBonus: 8, defBonus: 6, newSkillId: "hurricane" },
  { from: "aipom", to: "ambipom", level: 32, newName: "Ambipom", hpBonus: 14, atkBonus: 10, defBonus: 8, newSkillId: "hyperVoice" },
  // Phase 148-150: Water/Fire/Grass/Electric/Poison/Ground 7th
  { from: "poliwag", to: "poliwhirl", level: 25, newName: "Poliwhirl", hpBonus: 16, atkBonus: 10, defBonus: 8, newSkillId: "hydroPump" },
  { from: "corphish", to: "crawdaunt", level: 30, newName: "Crawdaunt", hpBonus: 14, atkBonus: 14, defBonus: 6, newSkillId: "hydroPump" },
  { from: "magby", to: "magmar", level: 30, newName: "Magmar", hpBonus: 16, atkBonus: 12, defBonus: 6, newSkillId: "eruption" },
  { from: "darumaka", to: "darmanitan", level: 35, newName: "Darmanitan", hpBonus: 18, atkBonus: 14, defBonus: 6, newSkillId: "eruption" },
  { from: "sewaddle", to: "swadloon", level: 20, newName: "Swadloon", hpBonus: 14, atkBonus: 8, defBonus: 10, newSkillId: "powerWhip" },
  { from: "pumpkaboo", to: "gourgeist", level: 32, newName: "Gourgeist", hpBonus: 16, atkBonus: 10, defBonus: 10, newSkillId: "powerWhip" },
  { from: "nidoranF", to: "nidorina", level: 16, newName: "Nidorina", hpBonus: 14, atkBonus: 10, defBonus: 8, newSkillId: "gunkShot" },
  { from: "gligar", to: "gliscor", level: 35, newName: "Gliscor", hpBonus: 16, atkBonus: 10, defBonus: 12, newSkillId: "drillRun" },
  { from: "rhyhorn", to: "rhydon", level: 42, newName: "Rhydon", hpBonus: 18, atkBonus: 12, defBonus: 10, newSkillId: "drillRun" },
];

/** Check if a species can evolve at a given level */
export function getEvolution(speciesId: string, level: number): EvolutionDef | null {
  return EVOLUTIONS.find(e => e.from === speciesId && level >= e.level) ?? null;
}
