/**
 * Pokemon species data — defines stats, types, sprites, skills for each species.
 */

import { PokemonType } from "./type-chart";
import { SKILL_DB, createSkill, Skill } from "./skill";

export interface PokemonSpecies {
  id: string;
  name: string;
  spriteKey: string;
  types: PokemonType[];
  attackType: PokemonType;
  /** Base stats at level 1 */
  baseStats: { hp: number; atk: number; def: number };
  /** Sprite dimensions */
  walkFrameWidth: number;
  walkFrameHeight: number;
  idleFrameWidth: number;
  idleFrameHeight: number;
  walkFrames: number;
  idleFrames: number;
  /** Skill IDs for this species */
  skillIds: string[];
  /** Which floors this enemy appears on (1-indexed) */
  floors: number[];
}

export const SPECIES: Record<string, PokemonSpecies> = {
  mudkip: {
    id: "mudkip",
    name: "Mudkip",
    spriteKey: "mudkip",
    types: [PokemonType.Water],
    attackType: PokemonType.Water,
    baseStats: { hp: 50, atk: 12, def: 6 },
    walkFrameWidth: 32, walkFrameHeight: 40,
    idleFrameWidth: 24, idleFrameHeight: 40,
    walkFrames: 6, idleFrames: 7,
    skillIds: ["tackle", "waterGun", "waterPulse", "swordsDance"],
    floors: [],
  },
  zubat: {
    id: "zubat",
    name: "Zubat",
    spriteKey: "zubat",
    types: [PokemonType.Poison, PokemonType.Flying],
    attackType: PokemonType.Flying,
    baseStats: { hp: 20, atk: 8, def: 3 },
    walkFrameWidth: 32, walkFrameHeight: 56,
    idleFrameWidth: 32, idleFrameHeight: 56,
    walkFrames: 8, idleFrames: 8,
    skillIds: ["wingAttack", "leechLife", "poisonSting", "supersonic"],
    floors: [1, 2, 3],
  },
  shellos: {
    id: "shellos",
    name: "Shellos",
    spriteKey: "shellos",
    types: [PokemonType.Water],
    attackType: PokemonType.Water,
    baseStats: { hp: 25, atk: 7, def: 5 },
    walkFrameWidth: 32, walkFrameHeight: 32,
    idleFrameWidth: 24, idleFrameHeight: 24,
    walkFrames: 6, idleFrames: 3,
    skillIds: ["waterGun", "tackle"],
    floors: [2, 3, 4],
  },
  corsola: {
    id: "corsola",
    name: "Corsola",
    spriteKey: "corsola",
    types: [PokemonType.Water, PokemonType.Rock],
    attackType: PokemonType.Water,
    baseStats: { hp: 30, atk: 9, def: 7 },
    walkFrameWidth: 24, walkFrameHeight: 32,
    idleFrameWidth: 24, idleFrameHeight: 32,
    walkFrames: 4, idleFrames: 3,
    skillIds: ["tackle", "waterGun"],
    floors: [3, 4, 5],
  },
  geodude: {
    id: "geodude",
    name: "Geodude",
    spriteKey: "geodude",
    types: [PokemonType.Rock, PokemonType.Ground],
    attackType: PokemonType.Rock,
    baseStats: { hp: 28, atk: 11, def: 8 },
    walkFrameWidth: 32, walkFrameHeight: 32,
    idleFrameWidth: 32, idleFrameHeight: 24,
    walkFrames: 4, idleFrames: 4,
    skillIds: ["tackle", "rockThrow"],
    floors: [4, 5],
  },
  // ── Thunderwave Cave ──
  pikachu: {
    id: "pikachu",
    name: "Pikachu",
    spriteKey: "pikachu",
    types: [PokemonType.Electric],
    attackType: PokemonType.Electric,
    baseStats: { hp: 28, atk: 12, def: 5 },
    walkFrameWidth: 32, walkFrameHeight: 40,
    idleFrameWidth: 40, idleFrameHeight: 56,
    walkFrames: 4, idleFrames: 6,
    skillIds: ["spark", "thunderShock", "quickAttack"],
    floors: [],
  },
  voltorb: {
    id: "voltorb",
    name: "Voltorb",
    spriteKey: "voltorb",
    types: [PokemonType.Electric],
    attackType: PokemonType.Electric,
    baseStats: { hp: 22, atk: 8, def: 4 },
    walkFrameWidth: 32, walkFrameHeight: 40,
    idleFrameWidth: 24, idleFrameHeight: 32,
    walkFrames: 8, idleFrames: 5,
    skillIds: ["tackle", "sonicBoom", "selfDestruct"],
    floors: [],
  },
  magnemite: {
    id: "magnemite",
    name: "Magnemite",
    spriteKey: "magnemite",
    types: [PokemonType.Electric],
    attackType: PokemonType.Electric,
    baseStats: { hp: 22, atk: 10, def: 7 },
    walkFrameWidth: 24, walkFrameHeight: 32,
    idleFrameWidth: 24, idleFrameHeight: 32,
    walkFrames: 6, idleFrames: 4,
    skillIds: ["thunderShock", "thunderWave", "tackle"],
    floors: [],
  },
  // ── Tiny Woods ──
  caterpie: {
    id: "caterpie",
    name: "Caterpie",
    spriteKey: "caterpie",
    types: [PokemonType.Bug],
    attackType: PokemonType.Bug,
    baseStats: { hp: 18, atk: 6, def: 3 },
    walkFrameWidth: 32, walkFrameHeight: 32,
    idleFrameWidth: 32, idleFrameHeight: 32,
    walkFrames: 3, idleFrames: 10,
    skillIds: ["tackle", "stringShot", "bugBite"],
    floors: [],
  },
  pidgey: {
    id: "pidgey",
    name: "Pidgey",
    spriteKey: "pidgey",
    types: [PokemonType.Normal, PokemonType.Flying],
    attackType: PokemonType.Flying,
    baseStats: { hp: 20, atk: 8, def: 4 },
    walkFrameWidth: 32, walkFrameHeight: 32,
    idleFrameWidth: 24, idleFrameHeight: 40,
    walkFrames: 5, idleFrames: 5,
    skillIds: ["gust", "quickAttack", "tackle"],
    floors: [],
  },
  // ── Mt. Steel ──
  aron: {
    id: "aron",
    name: "Aron",
    spriteKey: "aron",
    types: [PokemonType.Steel, PokemonType.Rock],
    attackType: PokemonType.Steel,
    baseStats: { hp: 30, atk: 10, def: 10 },
    walkFrameWidth: 24, walkFrameHeight: 24,
    idleFrameWidth: 24, idleFrameHeight: 32,
    walkFrames: 4, idleFrames: 4,
    skillIds: ["metalClaw", "headbutt", "ironDefense"],
    floors: [],
  },
  beldum: {
    id: "beldum",
    name: "Beldum",
    spriteKey: "beldum",
    types: [PokemonType.Steel, PokemonType.Psychic],
    attackType: PokemonType.Steel,
    baseStats: { hp: 26, atk: 10, def: 11 },
    walkFrameWidth: 32, walkFrameHeight: 48,
    idleFrameWidth: 32, idleFrameHeight: 40,
    walkFrames: 8, idleFrames: 8,
    skillIds: ["ironHead", "bulletPunch", "ironDefense"],
    floors: [],
  },
  skarmory: {
    id: "skarmory",
    name: "Skarmory",
    spriteKey: "skarmory",
    types: [PokemonType.Steel, PokemonType.Flying],
    attackType: PokemonType.Steel,
    baseStats: { hp: 28, atk: 9, def: 12 },
    walkFrameWidth: 40, walkFrameHeight: 72,
    idleFrameWidth: 40, idleFrameHeight: 64,
    walkFrames: 9, idleFrames: 7,
    skillIds: ["metalClaw", "airSlash", "ironDefense"],
    floors: [],
  },
  sandshrew: {
    id: "sandshrew",
    name: "Sandshrew",
    spriteKey: "sandshrew",
    types: [PokemonType.Ground],
    attackType: PokemonType.Ground,
    baseStats: { hp: 28, atk: 9, def: 10 },
    walkFrameWidth: 32, walkFrameHeight: 32,
    idleFrameWidth: 32, idleFrameHeight: 40,
    walkFrames: 4, idleFrames: 4,
    skillIds: ["sandAttack", "dig", "mudShot"],
    floors: [],
  },
  trapinch: {
    id: "trapinch",
    name: "Trapinch",
    spriteKey: "trapinch",
    types: [PokemonType.Ground],
    attackType: PokemonType.Ground,
    baseStats: { hp: 24, atk: 12, def: 6 },
    walkFrameWidth: 32, walkFrameHeight: 32,
    idleFrameWidth: 32, idleFrameHeight: 32,
    walkFrames: 4, idleFrames: 4,
    skillIds: ["sandTomb", "dig", "mudShot"],
    floors: [],
  },
  phanpy: {
    id: "phanpy",
    name: "Phanpy",
    spriteKey: "phanpy",
    types: [PokemonType.Ground],
    attackType: PokemonType.Ground,
    baseStats: { hp: 30, atk: 9, def: 9 },
    walkFrameWidth: 32, walkFrameHeight: 32,
    idleFrameWidth: 32, idleFrameHeight: 40,
    walkFrames: 4, idleFrames: 4,
    skillIds: ["tackle", "earthPower", "dig"],
    floors: [],
  },
  horsea: {
    id: "horsea",
    name: "Horsea",
    spriteKey: "horsea",
    types: [PokemonType.Water],
    attackType: PokemonType.Water,
    baseStats: { hp: 22, atk: 11, def: 7 },
    walkFrameWidth: 24, walkFrameHeight: 48,
    idleFrameWidth: 24, idleFrameHeight: 48,
    walkFrames: 4, idleFrames: 4,
    skillIds: ["waterGun", "brine", "aquaJet"],
    floors: [],
  },
  lotad: {
    id: "lotad",
    name: "Lotad",
    spriteKey: "lotad",
    types: [PokemonType.Water, PokemonType.Grass],
    attackType: PokemonType.Water,
    baseStats: { hp: 26, atk: 8, def: 8 },
    walkFrameWidth: 24, walkFrameHeight: 24,
    idleFrameWidth: 24, idleFrameHeight: 24,
    walkFrames: 4, idleFrames: 4,
    skillIds: ["waterGun", "absorb", "tackle"],
    floors: [],
  },
  carvanha: {
    id: "carvanha",
    name: "Carvanha",
    spriteKey: "carvanha",
    types: [PokemonType.Water, PokemonType.Dark],
    attackType: PokemonType.Water,
    baseStats: { hp: 24, atk: 12, def: 5 },
    walkFrameWidth: 32, walkFrameHeight: 48,
    idleFrameWidth: 32, idleFrameHeight: 48,
    walkFrames: 4, idleFrames: 4,
    skillIds: ["bite", "aquaJet", "brine"],
    floors: [],
  },
  elekid: {
    id: "elekid",
    name: "Elekid",
    spriteKey: "elekid",
    types: [PokemonType.Electric],
    attackType: PokemonType.Electric,
    baseStats: { hp: 24, atk: 11, def: 7 },
    walkFrameWidth: 32, walkFrameHeight: 48,
    idleFrameWidth: 32, idleFrameHeight: 56,
    walkFrames: 4, idleFrames: 4,
    skillIds: ["thunderPunch", "spark", "thunderShock"],
    floors: [],
  },
  mareep: {
    id: "mareep",
    name: "Mareep",
    spriteKey: "mareep",
    types: [PokemonType.Electric],
    attackType: PokemonType.Electric,
    baseStats: { hp: 26, atk: 9, def: 8 },
    walkFrameWidth: 32, walkFrameHeight: 32,
    idleFrameWidth: 32, idleFrameHeight: 40,
    walkFrames: 4, idleFrames: 6,
    skillIds: ["thunderShock", "thunderWave", "tackle"],
    floors: [],
  },
  wurmple: {
    id: "wurmple",
    name: "Wurmple",
    spriteKey: "wurmple",
    types: [PokemonType.Bug],
    attackType: PokemonType.Bug,
    baseStats: { hp: 20, atk: 8, def: 6 },
    walkFrameWidth: 32, walkFrameHeight: 48,
    idleFrameWidth: 24, idleFrameHeight: 32,
    walkFrames: 6, idleFrames: 8,
    skillIds: ["stringShot", "bugBite", "pinMissile"],
    floors: [],
  },
  spinarak: {
    id: "spinarak",
    name: "Spinarak",
    spriteKey: "spinarak",
    types: [PokemonType.Bug, PokemonType.Poison],
    attackType: PokemonType.Bug,
    baseStats: { hp: 24, atk: 10, def: 7 },
    walkFrameWidth: 32, walkFrameHeight: 24,
    idleFrameWidth: 24, idleFrameHeight: 24,
    walkFrames: 3, idleFrames: 4,
    skillIds: ["poisonSting", "signalBeam", "stringShot"],
    floors: [],
  },
  abra: {
    id: "abra",
    name: "Abra",
    spriteKey: "abra",
    types: [PokemonType.Psychic],
    attackType: PokemonType.Psychic,
    baseStats: { hp: 20, atk: 12, def: 5 },
    walkFrameWidth: 32, walkFrameHeight: 48,
    idleFrameWidth: 24, idleFrameHeight: 48,
    walkFrames: 8, idleFrames: 6,
    skillIds: ["confusion", "psybeam", "hypnosis"],
    floors: [],
  },
  natu: {
    id: "natu",
    name: "Natu",
    spriteKey: "natu",
    types: [PokemonType.Psychic, PokemonType.Flying],
    attackType: PokemonType.Psychic,
    baseStats: { hp: 24, atk: 10, def: 7 },
    walkFrameWidth: 24, walkFrameHeight: 24,
    idleFrameWidth: 24, idleFrameHeight: 32,
    walkFrames: 4, idleFrames: 4,
    skillIds: ["confusion", "nightShade", "psybeam"],
    floors: [],
  },
  meditite: {
    id: "meditite",
    name: "Meditite",
    spriteKey: "meditite",
    types: [PokemonType.Fighting],
    attackType: PokemonType.Fighting,
    baseStats: { hp: 22, atk: 11, def: 5 },
    walkFrameWidth: 32, walkFrameHeight: 40,
    idleFrameWidth: 24, idleFrameHeight: 32,
    walkFrames: 6, idleFrames: 4,
    skillIds: ["karateChop", "meditate", "tackle"],
    floors: [],
  },
  machop: {
    id: "machop",
    name: "Machop",
    spriteKey: "machop",
    types: [PokemonType.Fighting],
    attackType: PokemonType.Fighting,
    baseStats: { hp: 35, atk: 14, def: 6 },
    walkFrameWidth: 24, walkFrameHeight: 32,
    idleFrameWidth: 24, idleFrameHeight: 40,
    walkFrames: 4, idleFrames: 4,
    skillIds: ["karateChop", "lowKick", "focusPunch"],
    floors: [],
  },
  // ── Sky Tower ──
  gastly: {
    id: "gastly",
    name: "Gastly",
    spriteKey: "gastly",
    types: [PokemonType.Ghost, PokemonType.Poison],
    attackType: PokemonType.Ghost,
    baseStats: { hp: 18, atk: 12, def: 3 },
    walkFrameWidth: 64, walkFrameHeight: 64,
    idleFrameWidth: 72, idleFrameHeight: 56,
    walkFrames: 9, idleFrames: 4,
    skillIds: ["lick", "nightShade", "hypnosis"],
    floors: [],
  },
  drowzee: {
    id: "drowzee",
    name: "Drowzee",
    spriteKey: "drowzee",
    types: [PokemonType.Psychic],
    attackType: PokemonType.Psychic,
    baseStats: { hp: 30, atk: 10, def: 6 },
    walkFrameWidth: 32, walkFrameHeight: 40,
    idleFrameWidth: 32, idleFrameHeight: 40,
    walkFrames: 4, idleFrames: 4,
    skillIds: ["confusion", "hypnosis", "headbutt"],
    floors: [],
  },
  snorunt: {
    id: "snorunt",
    name: "Snorunt",
    spriteKey: "snorunt",
    types: [PokemonType.Ice],
    attackType: PokemonType.Ice,
    baseStats: { hp: 25, atk: 9, def: 5 },
    walkFrameWidth: 32, walkFrameHeight: 32,
    idleFrameWidth: 32, idleFrameHeight: 40,
    walkFrames: 3, idleFrames: 3,
    skillIds: ["iceShard", "iceBeam", "headbutt"],
    floors: [],
  },
  // ── Starters ──
  charmander: {
    id: "charmander",
    name: "Charmander",
    spriteKey: "charmander",
    types: [PokemonType.Fire],
    attackType: PokemonType.Fire,
    baseStats: { hp: 45, atk: 13, def: 5 },
    walkFrameWidth: 32, walkFrameHeight: 32,
    idleFrameWidth: 32, idleFrameHeight: 40,
    walkFrames: 4, idleFrames: 4,
    skillIds: ["scratch", "ember", "flamethrower", "swordsDance"],
    floors: [],
  },
  eevee: {
    id: "eevee",
    name: "Eevee",
    spriteKey: "eevee",
    types: [PokemonType.Normal],
    attackType: PokemonType.Normal,
    baseStats: { hp: 48, atk: 11, def: 7 },
    walkFrameWidth: 56, walkFrameHeight: 48,
    idleFrameWidth: 24, idleFrameHeight: 32,
    walkFrames: 5, idleFrames: 2,
    skillIds: ["tackle", "bite", "swift", "quickAttack"],
    floors: [],
  },
  // ── Magma Cavern ──
  numel: {
    id: "numel",
    name: "Numel",
    spriteKey: "numel",
    types: [PokemonType.Fire, PokemonType.Ground],
    attackType: PokemonType.Fire,
    baseStats: { hp: 32, atk: 10, def: 6 },
    walkFrameWidth: 32, walkFrameHeight: 32,
    idleFrameWidth: 40, idleFrameHeight: 40,
    walkFrames: 4, idleFrames: 4,
    skillIds: ["ember", "mudShot", "bodySlam"],
    floors: [],
  },
  slugma: {
    id: "slugma",
    name: "Slugma",
    spriteKey: "slugma",
    types: [PokemonType.Fire],
    attackType: PokemonType.Fire,
    baseStats: { hp: 25, atk: 12, def: 4 },
    walkFrameWidth: 32, walkFrameHeight: 40,
    idleFrameWidth: 32, idleFrameHeight: 40,
    walkFrames: 4, idleFrames: 4,
    skillIds: ["ember", "rockThrow", "bodySlam"],
    floors: [],
  },
  torkoal: {
    id: "torkoal",
    name: "Torkoal",
    spriteKey: "torkoal",
    types: [PokemonType.Fire],
    attackType: PokemonType.Fire,
    baseStats: { hp: 40, atk: 11, def: 10 },
    walkFrameWidth: 40, walkFrameHeight: 32,
    idleFrameWidth: 32, idleFrameHeight: 40,
    walkFrames: 4, idleFrames: 4,
    skillIds: ["flamethrower", "bodySlam", "ironDefense"],
    floors: [],
  },
  // ── Sinister Woods ──
  murkrow: {
    id: "murkrow",
    name: "Murkrow",
    spriteKey: "murkrow",
    types: [PokemonType.Dark, PokemonType.Flying],
    attackType: PokemonType.Dark,
    baseStats: { hp: 28, atk: 13, def: 4 },
    walkFrameWidth: 32, walkFrameHeight: 48,
    idleFrameWidth: 32, idleFrameHeight: 40,
    walkFrames: 6, idleFrames: 3,
    skillIds: ["feintAttack", "pursuit", "wingAttack"],
    floors: [],
  },
  sableye: {
    id: "sableye",
    name: "Sableye",
    spriteKey: "sableye",
    types: [PokemonType.Dark, PokemonType.Ghost],
    attackType: PokemonType.Dark,
    baseStats: { hp: 30, atk: 11, def: 7 },
    walkFrameWidth: 24, walkFrameHeight: 40,
    idleFrameWidth: 32, idleFrameHeight: 40,
    walkFrames: 4, idleFrames: 2,
    skillIds: ["nightSlash", "lick", "snarl"],
    floors: [],
  },
  absol: {
    id: "absol",
    name: "Absol",
    spriteKey: "absol",
    types: [PokemonType.Dark],
    attackType: PokemonType.Dark,
    baseStats: { hp: 35, atk: 15, def: 5 },
    walkFrameWidth: 40, walkFrameHeight: 48,
    idleFrameWidth: 40, idleFrameHeight: 48,
    walkFrames: 4, idleFrames: 2,
    skillIds: ["nightSlash", "darkPulse", "quickAttack"],
    floors: [],
  },
  // ── Overgrown Forest ──
  chikorita: {
    id: "chikorita",
    name: "Chikorita",
    spriteKey: "chikorita",
    types: [PokemonType.Grass],
    attackType: PokemonType.Grass,
    baseStats: { hp: 45, atk: 10, def: 7 },
    walkFrameWidth: 24, walkFrameHeight: 32,
    idleFrameWidth: 24, idleFrameHeight: 48,
    walkFrames: 4, idleFrames: 6,
    skillIds: ["vineWhip", "razorLeaf", "tackle"],
    floors: [],
  },
  bellsprout: {
    id: "bellsprout",
    name: "Bellsprout",
    spriteKey: "bellsprout",
    types: [PokemonType.Grass, PokemonType.Poison],
    attackType: PokemonType.Grass,
    baseStats: { hp: 25, atk: 12, def: 3 },
    walkFrameWidth: 24, walkFrameHeight: 32,
    idleFrameWidth: 24, idleFrameHeight: 32,
    walkFrames: 4, idleFrames: 2,
    skillIds: ["vineWhip", "absorb", "sleepPowder"],
    floors: [],
  },
  shroomish: {
    id: "shroomish",
    name: "Shroomish",
    spriteKey: "shroomish",
    types: [PokemonType.Grass],
    attackType: PokemonType.Grass,
    baseStats: { hp: 30, atk: 9, def: 6 },
    walkFrameWidth: 24, walkFrameHeight: 24,
    idleFrameWidth: 24, idleFrameHeight: 24,
    walkFrames: 4, idleFrames: 5,
    skillIds: ["absorb", "seedBomb", "tackle"],
    floors: [],
  },
  grimer: {
    id: "grimer",
    name: "Grimer",
    spriteKey: "grimer",
    types: [PokemonType.Poison],
    attackType: PokemonType.Poison,
    baseStats: { hp: 35, atk: 10, def: 6 },
    walkFrameWidth: 32, walkFrameHeight: 32,
    idleFrameWidth: 24, idleFrameHeight: 32,
    walkFrames: 6, idleFrames: 4,
    skillIds: ["poisonSting", "sludgeBomb", "tackle"],
    floors: [],
  },
  nidoranM: {
    id: "nidoranM",
    name: "Nidoran♂",
    spriteKey: "nidoranM",
    types: [PokemonType.Poison],
    attackType: PokemonType.Poison,
    baseStats: { hp: 28, atk: 12, def: 5 },
    walkFrameWidth: 40, walkFrameHeight: 48,
    idleFrameWidth: 32, idleFrameHeight: 48,
    walkFrames: 6, idleFrames: 5,
    skillIds: ["poisonSting", "acidSpray", "tackle"],
    floors: [],
  },
  tentacool: {
    id: "tentacool",
    name: "Tentacool",
    spriteKey: "tentacool",
    types: [PokemonType.Water, PokemonType.Poison],
    attackType: PokemonType.Poison,
    baseStats: { hp: 30, atk: 11, def: 5 },
    walkFrameWidth: 24, walkFrameHeight: 40,
    idleFrameWidth: 24, idleFrameHeight: 48,
    walkFrames: 4, idleFrames: 7,
    skillIds: ["poisonSting", "waterPulse", "acidSpray"],
    floors: [],
  },
  clefairy: {
    id: "clefairy",
    name: "Clefairy",
    spriteKey: "clefairy",
    types: [PokemonType.Fairy],
    attackType: PokemonType.Fairy,
    baseStats: { hp: 35, atk: 9, def: 7 },
    walkFrameWidth: 24, walkFrameHeight: 40,
    idleFrameWidth: 32, idleFrameHeight: 40,
    walkFrames: 8, idleFrames: 6,
    skillIds: ["fairyWind", "disarmingVoice", "tackle"],
    floors: [],
  },
  jigglypuff: {
    id: "jigglypuff",
    name: "Jigglypuff",
    spriteKey: "jigglypuff",
    types: [PokemonType.Fairy, PokemonType.Normal],
    attackType: PokemonType.Fairy,
    baseStats: { hp: 40, atk: 8, def: 5 },
    walkFrameWidth: 32, walkFrameHeight: 40,
    idleFrameWidth: 24, idleFrameHeight: 32,
    walkFrames: 5, idleFrames: 5,
    skillIds: ["disarmingVoice", "drainingKiss", "tackle"],
    floors: [],
  },
  ralts: {
    id: "ralts",
    name: "Ralts",
    spriteKey: "ralts",
    types: [PokemonType.Psychic, PokemonType.Fairy],
    attackType: PokemonType.Fairy,
    baseStats: { hp: 25, atk: 13, def: 4 },
    walkFrameWidth: 24, walkFrameHeight: 32,
    idleFrameWidth: 32, idleFrameHeight: 32,
    walkFrames: 4, idleFrames: 2,
    skillIds: ["confusion", "disarmingVoice", "tackle"],
    floors: [],
  },
  dratini: {
    id: "dratini",
    name: "Dratini",
    spriteKey: "dratini",
    types: [PokemonType.Dragon],
    attackType: PokemonType.Dragon,
    baseStats: { hp: 30, atk: 12, def: 5 },
    walkFrameWidth: 32, walkFrameHeight: 40,
    idleFrameWidth: 32, idleFrameHeight: 40,
    walkFrames: 5, idleFrames: 4,
    skillIds: ["dragonBreath", "twister", "tackle"],
    floors: [],
  },
  bagon: {
    id: "bagon",
    name: "Bagon",
    spriteKey: "bagon",
    types: [PokemonType.Dragon],
    attackType: PokemonType.Dragon,
    baseStats: { hp: 32, atk: 14, def: 6 },
    walkFrameWidth: 24, walkFrameHeight: 40,
    idleFrameWidth: 24, idleFrameHeight: 40,
    walkFrames: 4, idleFrames: 4,
    skillIds: ["dragonClaw", "dragonBreath", "tackle"],
    floors: [],
  },
  gible: {
    id: "gible",
    name: "Gible",
    spriteKey: "gible",
    types: [PokemonType.Dragon, PokemonType.Ground],
    attackType: PokemonType.Dragon,
    baseStats: { hp: 35, atk: 15, def: 5 },
    walkFrameWidth: 24, walkFrameHeight: 40,
    idleFrameWidth: 24, idleFrameHeight: 40,
    walkFrames: 4, idleFrames: 4,
    skillIds: ["dragonClaw", "mudShot", "tackle"],
    floors: [],
  },
  poochyena: {
    id: "poochyena",
    name: "Poochyena",
    spriteKey: "poochyena",
    types: [PokemonType.Dark],
    attackType: PokemonType.Dark,
    baseStats: { hp: 28, atk: 11, def: 5 },
    walkFrameWidth: 32, walkFrameHeight: 48,
    idleFrameWidth: 24, idleFrameHeight: 40,
    walkFrames: 5, idleFrames: 6,
    skillIds: ["bite", "pursuit", "tackle"],
    floors: [],
  },
  // ── Shadow Forest ──
  houndour: {
    id: "houndour",
    name: "Houndour",
    spriteKey: "houndour",
    types: [PokemonType.Dark, PokemonType.Fire],
    attackType: PokemonType.Dark,
    baseStats: { hp: 28, atk: 12, def: 6 },
    walkFrameWidth: 32, walkFrameHeight: 40,
    idleFrameWidth: 32, idleFrameHeight: 48,
    walkFrames: 4, idleFrames: 4,
    skillIds: ["crunch", "ember", "pursuit"],
    floors: [],
  },
  sneasel: {
    id: "sneasel",
    name: "Sneasel",
    spriteKey: "sneasel",
    types: [PokemonType.Dark, PokemonType.Ice],
    attackType: PokemonType.Dark,
    baseStats: { hp: 26, atk: 14, def: 5 },
    walkFrameWidth: 32, walkFrameHeight: 48,
    idleFrameWidth: 32, idleFrameHeight: 56,
    walkFrames: 4, idleFrames: 4,
    skillIds: ["nightSlash", "icePunch", "pursuit"],
    floors: [],
  },
  // ── Windy Summit ──
  taillow: {
    id: "taillow",
    name: "Taillow",
    spriteKey: "taillow",
    types: [PokemonType.Normal, PokemonType.Flying],
    attackType: PokemonType.Flying,
    baseStats: { hp: 24, atk: 11, def: 5 },
    walkFrameWidth: 32, walkFrameHeight: 32,
    idleFrameWidth: 32, idleFrameHeight: 32,
    walkFrames: 5, idleFrames: 5,
    skillIds: ["wingAttack", "quickAttack", "gust"],
    floors: [],
  },
  starly: {
    id: "starly",
    name: "Starly",
    spriteKey: "starly",
    types: [PokemonType.Normal, PokemonType.Flying],
    attackType: PokemonType.Flying,
    baseStats: { hp: 22, atk: 10, def: 5 },
    walkFrameWidth: 32, walkFrameHeight: 40,
    idleFrameWidth: 24, idleFrameHeight: 40,
    walkFrames: 5, idleFrames: 5,
    skillIds: ["gust", "quickAttack", "tackle"],
    floors: [],
  },
  // ── Battle Arena ──
  makuhita: {
    id: "makuhita",
    name: "Makuhita",
    spriteKey: "makuhita",
    types: [PokemonType.Fighting],
    attackType: PokemonType.Fighting,
    baseStats: { hp: 35, atk: 12, def: 5 },
    walkFrameWidth: 32, walkFrameHeight: 40,
    idleFrameWidth: 32, idleFrameHeight: 48,
    walkFrames: 4, idleFrames: 4,
    skillIds: ["karateChop", "drainPunch", "tackle"],
    floors: [],
  },
  riolu: {
    id: "riolu",
    name: "Riolu",
    spriteKey: "riolu",
    types: [PokemonType.Fighting],
    attackType: PokemonType.Fighting,
    baseStats: { hp: 26, atk: 13, def: 6 },
    walkFrameWidth: 24, walkFrameHeight: 40,
    idleFrameWidth: 32, idleFrameHeight: 40,
    walkFrames: 4, idleFrames: 4,
    skillIds: ["auraSphere", "quickAttack", "focusPunch"],
    floors: [],
  },
  // ── Rocky Cavern ──
  larvitar: {
    id: "larvitar",
    name: "Larvitar",
    spriteKey: "larvitar",
    types: [PokemonType.Rock, PokemonType.Ground],
    attackType: PokemonType.Rock,
    baseStats: { hp: 30, atk: 12, def: 8 },
    walkFrameWidth: 24, walkFrameHeight: 32,
    idleFrameWidth: 24, idleFrameHeight: 48,
    walkFrames: 4, idleFrames: 4,
    skillIds: ["rockThrow", "bite", "rockSlide"],
    floors: [],
  },
  nosepass: {
    id: "nosepass",
    name: "Nosepass",
    spriteKey: "nosepass",
    types: [PokemonType.Rock],
    attackType: PokemonType.Rock,
    baseStats: { hp: 32, atk: 8, def: 12 },
    walkFrameWidth: 32, walkFrameHeight: 40,
    idleFrameWidth: 32, idleFrameHeight: 56,
    walkFrames: 4, idleFrames: 4,
    skillIds: ["rockThrow", "ironDefense", "stoneEdge"],
    floors: [],
  },
};

/** Get enemy species that appear on a given floor */
export function getFloorEnemies(floor: number): PokemonSpecies[] {
  return Object.values(SPECIES).filter(s => s.floors.includes(floor));
}

/** Create skills from species skill IDs */
export function createSpeciesSkills(species: PokemonSpecies): Skill[] {
  return species.skillIds
    .filter(id => SKILL_DB[id])
    .map(id => createSkill(SKILL_DB[id]));
}

/** Level-up skill learning: speciesId → { level: skillId } */
export const LEVELUP_SKILLS: Record<string, Record<number, string>> = {
  mudkip: { 8: "rockThrow", 12: "ironDefense" },
  pikachu: { 7: "quickAttack", 10: "thunderWave" },
  machop: { 8: "lowKick", 12: "focusPunch" },
  caterpie: { 6: "stringShot", 9: "bugBite" },
  geodude: { 7: "rockThrow", 11: "ironDefense" },
  magnemite: { 8: "thunderWave", 11: "sonicBoom" },
  zubat: { 7: "poisonSting", 10: "wingAttack" },
  shellos: { 7: "waterPulse" },
  corsola: { 8: "waterPulse", 12: "ironDefense" },
  voltorb: { 8: "sonicBoom", 11: "selfDestruct" },
  pidgey: { 7: "gust", 10: "quickAttack" },
  aron: { 8: "metalClaw", 11: "ironDefense" },
  meditite: { 8: "meditate", 11: "focusPunch" },
  gastly: { 7: "nightShade", 10: "hypnosis" },
  drowzee: { 7: "confusion", 10: "hypnosis" },
  snorunt: { 7: "iceBeam", 10: "iceShard" },
  charmander: { 7: "ember", 10: "flamethrower" },
  eevee: { 7: "bite", 10: "swift" },
  numel: { 7: "mudShot", 10: "earthPower" },
  slugma: { 7: "ember", 10: "flamethrower" },
  torkoal: { 8: "fireBlast", 12: "lavaSurf" },
  murkrow: { 7: "pursuit", 10: "darkPulse" },
  sableye: { 7: "snarl", 10: "nightSlash" },
  absol: { 7: "nightSlash", 10: "darkPulse" },
  chikorita: { 7: "vineWhip", 10: "razorLeaf" },
  bellsprout: { 7: "absorb", 10: "sleepPowder" },
  shroomish: { 7: "seedBomb", 10: "absorb" },
  grimer: { 7: "sludgeBomb", 10: "toxicSpikes" },
  nidoranM: { 7: "acidSpray", 10: "venoshock" },
  tentacool: { 7: "acidSpray", 10: "sludgeBomb" },
  clefairy: { 7: "drainingKiss", 10: "moonblast" },
  jigglypuff: { 7: "fairyWind", 10: "dazzlingGleam" },
  ralts: { 7: "drainingKiss", 10: "moonblast" },
  dratini: { 7: "twister", 10: "dragonPulse" },
  bagon: { 7: "dragonBreath", 10: "dragonPulse" },
  gible: { 7: "dragonBreath", 10: "dracoMeteor" },
  poochyena: { 7: "snarl", 10: "darkPulse" },
  beldum: { 8: "bulletPunch", 11: "flashCannon" },
  skarmory: { 8: "ironHead", 11: "flashCannon" },
  sandshrew: { 7: "dig", 10: "earthPower" },
  trapinch: { 7: "dig", 10: "earthPower" },
  phanpy: { 7: "dig", 10: "earthPower" },
  horsea: { 7: "brine", 10: "waterPulse" },
  lotad: { 7: "waterPulse", 10: "absorb" },
  carvanha: { 7: "brine", 10: "darkPulse" },
  elekid: { 7: "thunderPunch", 10: "thunderbolt" },
  mareep: { 7: "spark", 10: "thunderbolt" },
  wurmple: { 6: "pinMissile", 9: "signalBeam" },
  spinarak: { 7: "signalBeam", 10: "pinMissile" },
  abra: { 7: "psybeam", 10: "psychic" },
  natu: { 7: "psybeam", 10: "psychic" },
  houndour: { 7: "crunch", 10: "flamethrower" },
  sneasel: { 7: "icePunch", 10: "darkPulse" },
  taillow: { 7: "airSlash", 10: "braveBird" },
  starly: { 7: "wingAttack", 10: "airSlash" },
  makuhita: { 7: "drainPunch", 10: "focusPunch" },
  riolu: { 7: "auraSphere", 10: "focusPunch" },
  larvitar: { 7: "rockSlide", 10: "stoneEdge" },
  nosepass: { 7: "rockSlide", 10: "stoneEdge" },
};

/** Check if a species learns a new skill at this level */
export function getLearnableSkill(speciesId: string, level: number): string | null {
  const map = LEVELUP_SKILLS[speciesId];
  if (!map) return null;
  return map[level] ?? null;
}
