/**
 * Skill (Move) system — PMD-style 4-skill slot system.
 * PP is consumed on use. 1 PP recovered per movement turn.
 */

import { PokemonType } from "./type-chart";

/** Targeting range of a skill */
export enum SkillRange {
  /** Adjacent 1 tile in facing direction */
  Front1 = "front1",
  /** 2 tiles in facing direction */
  Front2 = "front2",
  /** Straight line in facing direction (up to 10 tiles, piercing) */
  FrontLine = "frontLine",
  /** All 8 adjacent tiles around self */
  Around = "around",
  /** Entire room (or radius 3 in corridor) */
  Room = "room",
  /** Self only (buff/heal) */
  Self = "self",
}

/** Effect applied on hit */
export enum SkillEffect {
  None = "none",
  AtkUp = "atkUp",         // +50% ATK for 5 turns
  DefUp = "defUp",         // +50% DEF for 5 turns
  Heal = "heal",           // Restore HP
  Burn = "burn",           // DoT: 5 dmg/turn for 3 turns
  Paralyze = "paralyze",   // 50% chance to skip turn for 3 turns
}

export interface Skill {
  id: string;
  name: string;
  type: PokemonType;
  power: number;          // 0 = non-damaging (buff/heal)
  pp: number;             // max PP
  currentPp: number;      // current PP
  range: SkillRange;
  accuracy: number;       // 0-100, percentage
  effect?: SkillEffect;
  effectChance?: number;  // 0-100, percentage to apply effect
  description: string;
}

/** Create a fresh skill instance from a template */
export function createSkill(template: Omit<Skill, "currentPp">): Skill {
  return { ...template, currentPp: template.pp };
}

// ─── Skill Database ───

export const SKILL_DB: Record<string, Omit<Skill, "currentPp">> = {
  tackle: {
    id: "tackle",
    name: "Tackle",
    type: PokemonType.Normal,
    power: 8,
    pp: 25,
    range: SkillRange.Front1,
    accuracy: 95,
    description: "A basic charge attack.",
  },
  waterGun: {
    id: "waterGun",
    name: "Water Gun",
    type: PokemonType.Water,
    power: 12,
    pp: 18,
    range: SkillRange.FrontLine,
    accuracy: 90,
    description: "Shoots a stream of water in a line.",
  },
  waterPulse: {
    id: "waterPulse",
    name: "Water Pulse",
    type: PokemonType.Water,
    power: 15,
    pp: 12,
    range: SkillRange.Front2,
    accuracy: 85,
    description: "Sends out a pulse of water. 2-tile range.",
  },
  surf: {
    id: "surf",
    name: "Surf",
    type: PokemonType.Water,
    power: 18,
    pp: 8,
    range: SkillRange.Room,
    accuracy: 90,
    description: "Hits all enemies in the room with a wave.",
  },
  swordsDance: {
    id: "swordsDance",
    name: "Swords Dance",
    type: PokemonType.Normal,
    power: 0,
    pp: 10,
    range: SkillRange.Self,
    accuracy: 100,
    effect: SkillEffect.AtkUp,
    description: "Raises ATK by 50% for 5 turns.",
  },
  // Zubat skills
  wingAttack: {
    id: "wingAttack",
    name: "Wing Attack",
    type: PokemonType.Flying,
    power: 12,
    pp: 20,
    range: SkillRange.Front1,
    accuracy: 95,
    description: "Strikes with wings.",
  },
  leechLife: {
    id: "leechLife",
    name: "Leech Life",
    type: PokemonType.Bug,
    power: 10,
    pp: 12,
    range: SkillRange.Front1,
    accuracy: 90,
    description: "Drains HP from the target.",
  },
  poisonSting: {
    id: "poisonSting",
    name: "Poison Sting",
    type: PokemonType.Poison,
    power: 8,
    pp: 20,
    range: SkillRange.Front1,
    accuracy: 95,
    effect: SkillEffect.Burn,
    effectChance: 40,
    description: "Stings with toxic barb. May poison.",
  },
  supersonic: {
    id: "supersonic",
    name: "Supersonic",
    type: PokemonType.Normal,
    power: 0,
    pp: 15,
    range: SkillRange.FrontLine,
    accuracy: 70,
    effect: SkillEffect.Paralyze,
    effectChance: 100,
    description: "Confusing sound waves. May paralyze.",
  },
  // Rock
  rockThrow: {
    id: "rockThrow",
    name: "Rock Throw",
    type: PokemonType.Rock,
    power: 12,
    pp: 15,
    range: SkillRange.Front2,
    accuracy: 85,
    description: "Hurls a rock at the target.",
  },
  // Electric
  thunderShock: {
    id: "thunderShock",
    name: "ThunderShock",
    type: PokemonType.Electric,
    power: 10,
    pp: 20,
    range: SkillRange.FrontLine,
    accuracy: 90,
    effect: SkillEffect.Paralyze,
    effectChance: 30,
    description: "Shoots electricity. May paralyze.",
  },
  spark: {
    id: "spark",
    name: "Spark",
    type: PokemonType.Electric,
    power: 14,
    pp: 15,
    range: SkillRange.Front1,
    accuracy: 90,
    effect: SkillEffect.Paralyze,
    effectChance: 30,
    description: "Charges and tackles with electricity.",
  },
  thunderWave: {
    id: "thunderWave",
    name: "Thunder Wave",
    type: PokemonType.Electric,
    power: 0,
    pp: 15,
    range: SkillRange.Front2,
    accuracy: 80,
    effect: SkillEffect.Paralyze,
    effectChance: 100,
    description: "Sends a jolt to paralyze the target.",
  },
  sonicBoom: {
    id: "sonicBoom",
    name: "SonicBoom",
    type: PokemonType.Normal,
    power: 10,
    pp: 18,
    range: SkillRange.FrontLine,
    accuracy: 85,
    description: "Shockwave attack in a line.",
  },
  selfDestruct: {
    id: "selfDestruct",
    name: "Selfdestruct",
    type: PokemonType.Normal,
    power: 30,
    pp: 3,
    range: SkillRange.Around,
    accuracy: 100,
    description: "Explodes, hitting everything nearby.",
  },
  // Bug
  stringShot: {
    id: "stringShot",
    name: "String Shot",
    type: PokemonType.Bug,
    power: 0,
    pp: 20,
    range: SkillRange.Front2,
    accuracy: 85,
    effect: SkillEffect.Paralyze,
    effectChance: 100,
    description: "Slows down the target with silk.",
  },
  bugBite: {
    id: "bugBite",
    name: "Bug Bite",
    type: PokemonType.Bug,
    power: 10,
    pp: 18,
    range: SkillRange.Front1,
    accuracy: 95,
    description: "Bites the target with mandibles.",
  },
  // Flying
  gust: {
    id: "gust",
    name: "Gust",
    type: PokemonType.Flying,
    power: 10,
    pp: 20,
    range: SkillRange.Front2,
    accuracy: 90,
    description: "Whips up a gust of wind.",
  },
  quickAttack: {
    id: "quickAttack",
    name: "Quick Attack",
    type: PokemonType.Normal,
    power: 8,
    pp: 25,
    range: SkillRange.Front1,
    accuracy: 100,
    description: "A swift, sure-hit attack.",
  },
  // Fighting
  karateChop: {
    id: "karateChop",
    name: "Karate Chop",
    type: PokemonType.Fighting,
    power: 12,
    pp: 18,
    range: SkillRange.Front1,
    accuracy: 95,
    description: "A precise chopping attack.",
  },
  lowKick: {
    id: "lowKick",
    name: "Low Kick",
    type: PokemonType.Fighting,
    power: 10,
    pp: 20,
    range: SkillRange.Front1,
    accuracy: 90,
    description: "A low sweeping kick.",
  },
  focusPunch: {
    id: "focusPunch",
    name: "Focus Punch",
    type: PokemonType.Fighting,
    power: 22,
    pp: 6,
    range: SkillRange.Front1,
    accuracy: 80,
    description: "A devastating focused punch.",
  },
  meditate: {
    id: "meditate",
    name: "Meditate",
    type: PokemonType.Fighting,
    power: 0,
    pp: 15,
    range: SkillRange.Self,
    accuracy: 100,
    effect: SkillEffect.AtkUp,
    description: "Meditates to raise ATK.",
  },
  // Steel
  metalClaw: {
    id: "metalClaw",
    name: "Metal Claw",
    type: PokemonType.Steel,
    power: 12,
    pp: 20,
    range: SkillRange.Front1,
    accuracy: 90,
    description: "Slashes with metal claws.",
  },
  ironDefense: {
    id: "ironDefense",
    name: "Iron Defense",
    type: PokemonType.Steel,
    power: 0,
    pp: 10,
    range: SkillRange.Self,
    accuracy: 100,
    effect: SkillEffect.DefUp,
    description: "Hardens the body to raise DEF.",
  },
  headbutt: {
    id: "headbutt",
    name: "Headbutt",
    type: PokemonType.Normal,
    power: 14,
    pp: 15,
    range: SkillRange.Front1,
    accuracy: 90,
    description: "A charging headbutt attack.",
  },
  // Ghost
  shadowBall: {
    id: "shadowBall",
    name: "Shadow Ball",
    type: PokemonType.Ghost,
    power: 16,
    pp: 12,
    range: SkillRange.Front2,
    accuracy: 90,
    description: "Hurls a shadowy blob. 2-tile range.",
  },
  lick: {
    id: "lick",
    name: "Lick",
    type: PokemonType.Ghost,
    power: 8,
    pp: 20,
    range: SkillRange.Front1,
    accuracy: 90,
    effect: SkillEffect.Paralyze,
    effectChance: 30,
    description: "Licks the target. May paralyze.",
  },
  nightShade: {
    id: "nightShade",
    name: "Night Shade",
    type: PokemonType.Ghost,
    power: 12,
    pp: 15,
    range: SkillRange.FrontLine,
    accuracy: 85,
    description: "Eerie shadows strike in a line.",
  },
  // Psychic
  confusion: {
    id: "confusion",
    name: "Confusion",
    type: PokemonType.Psychic,
    power: 12,
    pp: 18,
    range: SkillRange.Front2,
    accuracy: 90,
    description: "Psychic attack. 2-tile range.",
  },
  psybeam: {
    id: "psybeam",
    name: "Psybeam",
    type: PokemonType.Psychic,
    power: 16,
    pp: 12,
    range: SkillRange.FrontLine,
    accuracy: 85,
    description: "Fires a peculiar ray in a line.",
  },
  hypnosis: {
    id: "hypnosis",
    name: "Hypnosis",
    type: PokemonType.Psychic,
    power: 0,
    pp: 12,
    range: SkillRange.Front2,
    accuracy: 70,
    effect: SkillEffect.Paralyze,
    effectChance: 100,
    description: "Puts the target to sleep (paralyze).",
  },
  // Ice
  iceBeam: {
    id: "iceBeam",
    name: "Ice Beam",
    type: PokemonType.Ice,
    power: 16,
    pp: 10,
    range: SkillRange.FrontLine,
    accuracy: 90,
    description: "Fires an icy beam in a line.",
  },
  iceShard: {
    id: "iceShard",
    name: "Ice Shard",
    type: PokemonType.Ice,
    power: 10,
    pp: 20,
    range: SkillRange.Front1,
    accuracy: 100,
    description: "An icy priority attack.",
  },
  // Fire
  ember: {
    id: "ember",
    name: "Ember",
    type: PokemonType.Fire,
    power: 10,
    pp: 20,
    range: SkillRange.Front2,
    accuracy: 90,
    effect: SkillEffect.Burn,
    effectChance: 20,
    description: "Spits flames. May burn.",
  },
  flamethrower: {
    id: "flamethrower",
    name: "Flamethrower",
    type: PokemonType.Fire,
    power: 18,
    pp: 10,
    range: SkillRange.FrontLine,
    accuracy: 90,
    description: "A powerful fire stream in a line.",
  },
  scratch: {
    id: "scratch",
    name: "Scratch",
    type: PokemonType.Normal,
    power: 8,
    pp: 25,
    range: SkillRange.Front1,
    accuracy: 100,
    description: "A basic scratching attack.",
  },
  bite: {
    id: "bite",
    name: "Bite",
    type: PokemonType.Normal,
    power: 12,
    pp: 18,
    range: SkillRange.Front1,
    accuracy: 95,
    description: "Bites the target with sharp fangs.",
  },
  swift: {
    id: "swift",
    name: "Swift",
    type: PokemonType.Normal,
    power: 12,
    pp: 15,
    range: SkillRange.Room,
    accuracy: 100,
    description: "Star-shaped rays hit all enemies in the room.",
  },
  sandAttack: {
    id: "sandAttack",
    name: "Sand Attack",
    type: PokemonType.Ground,
    power: 0,
    pp: 15,
    range: SkillRange.Front2,
    accuracy: 100,
    effect: SkillEffect.Paralyze,
    effectChance: 40,
    description: "Kicks up sand to reduce accuracy.",
  },
  // ── Ground Skills ──
  mudShot: {
    id: "mudShot",
    name: "Mud Shot",
    type: PokemonType.Ground,
    power: 12,
    pp: 15,
    range: SkillRange.Front2,
    accuracy: 85,
    description: "Hurls a blob of mud. 2-tile range.",
  },
  earthPower: {
    id: "earthPower",
    name: "Earth Power",
    type: PokemonType.Ground,
    power: 18,
    pp: 8,
    range: SkillRange.Around,
    accuracy: 90,
    description: "The earth erupts around the user.",
  },
  dig: {
    id: "dig",
    name: "Dig",
    type: PokemonType.Ground,
    power: 16,
    pp: 12,
    range: SkillRange.Front1,
    accuracy: 95,
    description: "Digs underground then strikes.",
  },
  sandTomb: {
    id: "sandTomb",
    name: "Sand Tomb",
    type: PokemonType.Ground,
    power: 10,
    pp: 18,
    range: SkillRange.Around,
    accuracy: 85,
    effect: SkillEffect.Burn,
    effectChance: 30,
    description: "Traps the foe in a sand vortex.",
  },
  // ── Additional Fire Skills ──
  fireBlast: {
    id: "fireBlast",
    name: "Fire Blast",
    type: PokemonType.Fire,
    power: 22,
    pp: 5,
    range: SkillRange.Front2,
    accuracy: 80,
    effect: SkillEffect.Burn,
    effectChance: 30,
    description: "A massive blast of fire.",
  },
  lavaSurf: {
    id: "lavaSurf",
    name: "Lava Plume",
    type: PokemonType.Fire,
    power: 16,
    pp: 10,
    range: SkillRange.Around,
    accuracy: 90,
    effect: SkillEffect.Burn,
    effectChance: 30,
    description: "Scorching lava hits all adjacent foes.",
  },
  bodySlam: {
    id: "bodySlam",
    name: "Body Slam",
    type: PokemonType.Normal,
    power: 16,
    pp: 12,
    range: SkillRange.Front1,
    accuracy: 90,
    effect: SkillEffect.Paralyze,
    effectChance: 30,
    description: "A heavy slam that may paralyze.",
  },
  // ── Dark Skills ──
  darkPulse: {
    id: "darkPulse",
    name: "Dark Pulse",
    type: PokemonType.Dark,
    power: 16,
    pp: 12,
    range: SkillRange.FrontLine,
    accuracy: 90,
    description: "A wave of dark energy in a line.",
  },
  feintAttack: {
    id: "feintAttack",
    name: "Feint Attack",
    type: PokemonType.Dark,
    power: 12,
    pp: 18,
    range: SkillRange.Front1,
    accuracy: 100,
    description: "A sneaky attack that never misses.",
  },
  nightSlash: {
    id: "nightSlash",
    name: "Night Slash",
    type: PokemonType.Dark,
    power: 14,
    pp: 15,
    range: SkillRange.Front1,
    accuracy: 95,
    description: "Slashes with dark energy.",
  },
  snarl: {
    id: "snarl",
    name: "Snarl",
    type: PokemonType.Dark,
    power: 10,
    pp: 15,
    range: SkillRange.Around,
    accuracy: 90,
    description: "A growling attack hitting all nearby foes.",
  },
  pursuit: {
    id: "pursuit",
    name: "Pursuit",
    type: PokemonType.Dark,
    power: 10,
    pp: 20,
    range: SkillRange.Front2,
    accuracy: 95,
    description: "Chases and hits with dark energy.",
  },
  // ── Grass Skills ──
  vineWhip: {
    id: "vineWhip",
    name: "Vine Whip",
    type: PokemonType.Grass,
    power: 10,
    pp: 20,
    range: SkillRange.Front2,
    accuracy: 90,
    description: "Strikes with vines. 2-tile range.",
  },
  razorLeaf: {
    id: "razorLeaf",
    name: "Razor Leaf",
    type: PokemonType.Grass,
    power: 14,
    pp: 15,
    range: SkillRange.FrontLine,
    accuracy: 90,
    description: "Launches sharp leaves in a line.",
  },
  seedBomb: {
    id: "seedBomb",
    name: "Seed Bomb",
    type: PokemonType.Grass,
    power: 16,
    pp: 10,
    range: SkillRange.Front2,
    accuracy: 85,
    description: "Explosive seeds. 2-tile range.",
  },
  absorb: {
    id: "absorb",
    name: "Absorb",
    type: PokemonType.Grass,
    power: 8,
    pp: 20,
    range: SkillRange.Front1,
    accuracy: 95,
    description: "Drains HP from the target.",
  },
  sleepPowder: {
    id: "sleepPowder",
    name: "Sleep Powder",
    type: PokemonType.Grass,
    power: 0,
    pp: 10,
    range: SkillRange.Front2,
    accuracy: 70,
    effect: SkillEffect.Paralyze,
    effectChance: 100,
    description: "Scatters powder to put foes to sleep.",
  },
  // ── Poison skills ──
  sludgeBomb: {
    id: "sludgeBomb",
    name: "Sludge Bomb",
    type: PokemonType.Poison,
    power: 16,
    pp: 12,
    range: SkillRange.Front2,
    accuracy: 85,
    effect: SkillEffect.Burn,
    effectChance: 30,
    description: "Hurls sludge. May poison the foe.",
  },
  acidSpray: {
    id: "acidSpray",
    name: "Acid Spray",
    type: PokemonType.Poison,
    power: 12,
    pp: 14,
    range: SkillRange.Front2,
    accuracy: 90,
    description: "Sprays corrosive acid at the foe.",
  },
  toxicSpikes: {
    id: "toxicSpikes",
    name: "Toxic Spikes",
    type: PokemonType.Poison,
    power: 10,
    pp: 15,
    range: SkillRange.Around,
    accuracy: 80,
    effect: SkillEffect.Burn,
    effectChance: 50,
    description: "Scatters toxic spikes around self.",
  },
  venoshock: {
    id: "venoshock",
    name: "Venoshock",
    type: PokemonType.Poison,
    power: 18,
    pp: 10,
    range: SkillRange.FrontLine,
    accuracy: 80,
    description: "Fires poison beam in a line.",
  },
  // ── Fairy skills ──
  moonblast: {
    id: "moonblast",
    name: "Moonblast",
    type: PokemonType.Fairy,
    power: 18,
    pp: 10,
    range: SkillRange.Front2,
    accuracy: 85,
    description: "Moonlight blast. High power fairy move.",
  },
  disarmingVoice: {
    id: "disarmingVoice",
    name: "Disarming Voice",
    type: PokemonType.Fairy,
    power: 10,
    pp: 18,
    range: SkillRange.FrontLine,
    accuracy: 100,
    description: "Charming cry that never misses.",
  },
  drainingKiss: {
    id: "drainingKiss",
    name: "Draining Kiss",
    type: PokemonType.Fairy,
    power: 12,
    pp: 14,
    range: SkillRange.Front1,
    accuracy: 90,
    effect: SkillEffect.Heal,
    effectChance: 100,
    description: "Drains HP with a kiss.",
  },
  fairyWind: {
    id: "fairyWind",
    name: "Fairy Wind",
    type: PokemonType.Fairy,
    power: 8,
    pp: 20,
    range: SkillRange.Around,
    accuracy: 90,
    description: "Stirs up fairy wind around self.",
  },
  dazzlingGleam: {
    id: "dazzlingGleam",
    name: "Dazzling Gleam",
    type: PokemonType.Fairy,
    power: 14,
    pp: 12,
    range: SkillRange.Room,
    accuracy: 80,
    description: "Dazzling light fills the room.",
  },
  // ── Dragon skills ──
  dragonBreath: {
    id: "dragonBreath",
    name: "Dragon Breath",
    type: PokemonType.Dragon,
    power: 12,
    pp: 16,
    range: SkillRange.Front2,
    accuracy: 90,
    effect: SkillEffect.Paralyze,
    effectChance: 30,
    description: "Exhales dragon breath. May paralyze.",
  },
  dragonClaw: {
    id: "dragonClaw",
    name: "Dragon Claw",
    type: PokemonType.Dragon,
    power: 16,
    pp: 12,
    range: SkillRange.Front1,
    accuracy: 90,
    description: "Slashes with sharp dragon claws.",
  },
  dragonPulse: {
    id: "dragonPulse",
    name: "Dragon Pulse",
    type: PokemonType.Dragon,
    power: 18,
    pp: 10,
    range: SkillRange.FrontLine,
    accuracy: 85,
    description: "Fires a shockwave of draconic energy.",
  },
  dracoMeteor: {
    id: "dracoMeteor",
    name: "Draco Meteor",
    type: PokemonType.Dragon,
    power: 24,
    pp: 5,
    range: SkillRange.Room,
    accuracy: 75,
    description: "Summons meteors to strike the room!",
  },
  twister: {
    id: "twister",
    name: "Twister",
    type: PokemonType.Dragon,
    power: 10,
    pp: 18,
    range: SkillRange.Around,
    accuracy: 90,
    description: "Whips up a vicious twister around self.",
  },

  // ── Steel Skills ──
  ironHead: {
    id: "ironHead",
    name: "Iron Head",
    type: PokemonType.Steel,
    power: 16,
    pp: 15,
    range: SkillRange.Front1,
    accuracy: 90,
    effect: SkillEffect.Paralyze,
    effectChance: 30,
    description: "Rams with a steel-hard head. May paralyze.",
  },
  flashCannon: {
    id: "flashCannon",
    name: "Flash Cannon",
    type: PokemonType.Steel,
    power: 16,
    pp: 12,
    range: SkillRange.FrontLine,
    accuracy: 90,
    description: "Fires a flash of light energy in a line.",
  },
  bulletPunch: {
    id: "bulletPunch",
    name: "Bullet Punch",
    type: PokemonType.Steel,
    power: 10,
    pp: 22,
    range: SkillRange.Front2,
    accuracy: 100,
    description: "Strikes with a quick punch of steel.",
  },

  // ── Additional Water Skills ──
  brine: {
    id: "brine",
    name: "Brine",
    type: PokemonType.Water,
    power: 14,
    pp: 15,
    range: SkillRange.Front2,
    accuracy: 90,
    description: "Attacks with salty water. 2-tile range.",
  },
  aquaJet: {
    id: "aquaJet",
    name: "Aqua Jet",
    type: PokemonType.Water,
    power: 10,
    pp: 22,
    range: SkillRange.Front2,
    accuracy: 100,
    description: "Strikes with a jet of water at priority.",
  },

  // ── Additional Electric Skills ──
  thunderbolt: {
    id: "thunderbolt",
    name: "Thunderbolt",
    type: PokemonType.Electric,
    power: 18,
    pp: 10,
    range: SkillRange.FrontLine,
    accuracy: 90,
    effect: SkillEffect.Paralyze,
    effectChance: 20,
    description: "Fires a strong bolt of electricity.",
  },
  thunderPunch: {
    id: "thunderPunch",
    name: "Thunder Punch",
    type: PokemonType.Electric,
    power: 15,
    pp: 14,
    range: SkillRange.Front1,
    accuracy: 90,
    effect: SkillEffect.Paralyze,
    effectChance: 20,
    description: "Punches with electrically charged fist.",
  },

  // ── Additional Bug Skills ──
  signalBeam: {
    id: "signalBeam",
    name: "Signal Beam",
    type: PokemonType.Bug,
    power: 15,
    pp: 12,
    range: SkillRange.FrontLine,
    accuracy: 90,
    description: "Fires a peculiar beam of light.",
  },
  pinMissile: {
    id: "pinMissile",
    name: "Pin Missile",
    type: PokemonType.Bug,
    power: 8,
    pp: 20,
    range: SkillRange.Front2,
    accuracy: 85,
    description: "Fires sharp pins rapidly.",
  },

  // ── Additional Dark Skills ──
  crunch: {
    id: "crunch",
    name: "Crunch",
    type: PokemonType.Dark,
    power: 16,
    pp: 12,
    range: SkillRange.Front1,
    accuracy: 90,
    description: "Bites down hard. May lower DEF.",
    effect: SkillEffect.None,
  },
  icePunch: {
    id: "icePunch",
    name: "Ice Punch",
    type: PokemonType.Ice,
    power: 15,
    pp: 12,
    range: SkillRange.Front1,
    accuracy: 90,
    description: "An ice-cold punch.",
    effect: SkillEffect.Paralyze,
    effectChance: 20,
  },

  // ── Additional Psychic Skills ──
  psychic: {
    id: "psychic",
    name: "Psychic",
    type: PokemonType.Psychic,
    power: 18,
    pp: 8,
    range: SkillRange.Around,
    accuracy: 90,
    description: "Powerful psychic force hits all around.",
  },

  // ── Additional Flying Skills ──
  braveBird: {
    id: "braveBird",
    name: "Brave Bird",
    type: PokemonType.Flying,
    power: 20,
    pp: 8,
    range: SkillRange.Front2,
    accuracy: 85,
    description: "A powerful diving attack.",
  },
  airSlash: {
    id: "airSlash",
    name: "Air Slash",
    type: PokemonType.Flying,
    power: 15,
    pp: 12,
    range: SkillRange.FrontLine,
    accuracy: 90,
    description: "Slices with blades of air.",
  },

  // ── Additional Fighting Skills ──
  auraSphere: {
    id: "auraSphere",
    name: "Aura Sphere",
    type: PokemonType.Fighting,
    power: 16,
    pp: 10,
    range: SkillRange.FrontLine,
    accuracy: 100,
    description: "Never misses. A sphere of aura energy.",
  },
  drainPunch: {
    id: "drainPunch",
    name: "Drain Punch",
    type: PokemonType.Fighting,
    power: 14,
    pp: 12,
    range: SkillRange.Front1,
    accuracy: 90,
    effect: SkillEffect.Heal,
    description: "Drains HP from the target.",
  },

  // ── Additional Rock Skills ──
  rockSlide: {
    id: "rockSlide",
    name: "Rock Slide",
    type: PokemonType.Rock,
    power: 16,
    pp: 10,
    range: SkillRange.Around,
    accuracy: 85,
    description: "Hurls rocks at all nearby foes.",
  },
  stoneEdge: {
    id: "stoneEdge",
    name: "Stone Edge",
    type: PokemonType.Rock,
    power: 20,
    pp: 6,
    range: SkillRange.Front2,
    accuracy: 80,
    description: "Launches sharp stones with high power.",
  },

  // ── Additional Ice Skills ──
  avalanche: {
    id: "avalanche",
    name: "Avalanche",
    type: PokemonType.Ice,
    power: 16,
    pp: 10,
    range: SkillRange.Around,
    accuracy: 85,
    description: "Crashes down ice on all nearby foes.",
  },
  icyWind: {
    id: "icyWind",
    name: "Icy Wind",
    type: PokemonType.Ice,
    power: 12,
    pp: 14,
    range: SkillRange.FrontLine,
    accuracy: 90,
    description: "Chills foes in a line.",
  },

  // ── Additional Normal Skills ──
  hyperVoice: {
    id: "hyperVoice",
    name: "Hyper Voice",
    type: PokemonType.Normal,
    power: 16,
    pp: 10,
    range: SkillRange.Around,
    accuracy: 90,
    description: "Loud shout damages all around.",
  },

  // ── Additional Grass Skills ──
  petalDance: {
    id: "petalDance",
    name: "Petal Dance",
    type: PokemonType.Grass,
    power: 16,
    pp: 10,
    range: SkillRange.Around,
    accuracy: 85,
    description: "Scatters petals that hit all around.",
  },
  energyBall: {
    id: "energyBall",
    name: "Energy Ball",
    type: PokemonType.Grass,
    power: 16,
    pp: 10,
    range: SkillRange.FrontLine,
    accuracy: 90,
    description: "Launches a ball of natural energy.",
  },
  // ── Phase 44 Fire Skills ──
  flameWheel: {
    id: "flameWheel",
    name: "Flame Wheel",
    type: PokemonType.Fire,
    power: 14,
    pp: 15,
    range: SkillRange.Front2,
    accuracy: 95,
    effect: SkillEffect.Burn,
    effectChance: 10,
    description: "Charges forward cloaked in flames.",
  },
  fireSpin: {
    id: "fireSpin",
    name: "Fire Spin",
    type: PokemonType.Fire,
    power: 12,
    pp: 12,
    range: SkillRange.Around,
    accuracy: 85,
    effect: SkillEffect.Burn,
    effectChance: 20,
    description: "Traps foes in a vortex of fire.",
  },
  // ── Phase 45 Water Skills ──
  whirlpool: {
    id: "whirlpool",
    name: "Whirlpool",
    type: PokemonType.Water,
    power: 14,
    pp: 12,
    range: SkillRange.Around,
    accuracy: 85,
    description: "Traps foes in a fierce vortex of water.",
  },
  // ── Phase 47 Electric Skills ──
  sparkCharge: {
    id: "sparkCharge",
    name: "Spark",
    type: PokemonType.Electric,
    power: 12,
    pp: 15,
    range: SkillRange.Front1,
    accuracy: 95,
    effect: SkillEffect.Paralyze,
    effectChance: 30,
    description: "A jolt of electricity. May paralyze.",
  },
  wildCharge: {
    id: "wildCharge",
    name: "Wild Charge",
    type: PokemonType.Electric,
    power: 18,
    pp: 8,
    range: SkillRange.Front2,
    accuracy: 90,
    description: "Charges with electricity at full force.",
  },
  // ── Phase 49 Ground Skills ──
  boneRush: {
    id: "boneRush",
    name: "Bone Rush",
    type: PokemonType.Ground,
    power: 14,
    pp: 12,
    range: SkillRange.Front2,
    accuracy: 90,
    description: "Strikes with a bone thrown forward.",
  },
  bulldoze: {
    id: "bulldoze",
    name: "Bulldoze",
    type: PokemonType.Ground,
    power: 12,
    pp: 15,
    range: SkillRange.Around,
    accuracy: 95,
    description: "Stomps the ground, hitting all nearby.",
  },
  // ── Phase 51 Bug Skills ──
  xScissor: {
    id: "xScissor",
    name: "X-Scissor",
    type: PokemonType.Bug,
    power: 16,
    pp: 10,
    range: SkillRange.Front1,
    accuracy: 95,
    description: "Slashes the foe in an X pattern.",
  },
  // ── Phase 52 Steel Skills ──
  gyroBall: {
    id: "gyroBall",
    name: "Gyro Ball",
    type: PokemonType.Steel,
    power: 14,
    pp: 12,
    range: SkillRange.Around,
    accuracy: 90,
    description: "Spins rapidly, hitting all nearby foes.",
  },
  // ── Phase 53 Ghost Skills ──
  shadowSneak: {
    id: "shadowSneak",
    name: "Shadow Sneak",
    type: PokemonType.Ghost,
    power: 10,
    pp: 20,
    range: SkillRange.Front2,
    accuracy: 100,
    description: "Strikes from the shadows with priority.",
  },

  // ── Phase 55 Dragon Skills ──
  dragonRush: {
    id: "dragonRush",
    name: "Dragon Rush",
    type: PokemonType.Dragon,
    power: 18,
    pp: 8,
    range: SkillRange.Front2,
    accuracy: 85,
    description: "Charges the foe with overwhelming draconic force.",
  },

  // ── Phase 56 Fairy Skills ──
  playRough: {
    id: "playRough",
    name: "Play Rough",
    type: PokemonType.Fairy,
    power: 16,
    pp: 10,
    range: SkillRange.Front1,
    accuracy: 90,
    description: "Plays rough with the target. High contact damage.",
  },

  // ── Phase 57 Ice Skills ──
  iceHammer: {
    id: "iceHammer",
    name: "Ice Hammer",
    type: PokemonType.Ice,
    power: 18,
    pp: 8,
    range: SkillRange.Front1,
    accuracy: 85,
    description: "Swings a heavy ice fist down on the foe.",
  },

  // ── Phase 59 Psychic Skills ──
  psyshock: {
    id: "psyshock",
    name: "Psyshock",
    type: PokemonType.Psychic,
    power: 14,
    pp: 12,
    range: SkillRange.Front2,
    accuracy: 90,
    description: "Materializes psychic power into a shockwave.",
  },

  // ── Phase 60 Dark Skills ──
  foulPlay: {
    id: "foulPlay",
    name: "Foul Play",
    type: PokemonType.Dark,
    power: 16,
    pp: 10,
    range: SkillRange.Front1,
    accuracy: 90,
    description: "Turns the foe's power against it.",
  },

  // ── Phase 61 Flying Skills ──
  hurricane: {
    id: "hurricane",
    name: "Hurricane",
    type: PokemonType.Flying,
    power: 18,
    pp: 8,
    range: SkillRange.Room,
    accuracy: 70,
    description: "Summons a devastating hurricane in the room.",
  },

  // ── Phase 63 Fighting Skills ──
  hammerArm: {
    id: "hammerArm",
    name: "Hammer Arm",
    type: PokemonType.Fighting,
    power: 18,
    pp: 8,
    range: SkillRange.Front1,
    accuracy: 85,
    description: "Smashes down with a heavy fist.",
  },

  // ── Phase 64 Rock Skills ──
  rockWrecker: {
    id: "rockWrecker",
    name: "Rock Wrecker",
    type: PokemonType.Rock,
    power: 20,
    pp: 6,
    range: SkillRange.Front2,
    accuracy: 80,
    description: "Hurls a massive boulder at the foe.",
  },

  // ── Phase 65 Normal Skills ──
  triAttack: {
    id: "triAttack",
    name: "Tri Attack",
    type: PokemonType.Normal,
    power: 14,
    pp: 12,
    range: SkillRange.Front2,
    accuracy: 90,
    description: "Fires three beams of energy at the foe.",
  },

  // ── Phase 67 Grass Skills ──
  grassKnot: {
    id: "grassKnot",
    name: "Grass Knot",
    type: PokemonType.Grass,
    power: 14,
    pp: 12,
    range: SkillRange.Front2,
    accuracy: 90,
    description: "Trips the target with a grass snare.",
  },

  // ── Phase 68 Water Skills ──
  dive: {
    id: "dive",
    name: "Dive",
    type: PokemonType.Water,
    power: 16,
    pp: 10,
    range: SkillRange.Front2,
    accuracy: 90,
    description: "Dives underwater and strikes the target.",
  },

  // ── Phase 69 Fire Skills ──
  heatWave: {
    id: "heatWave",
    name: "Heat Wave",
    type: PokemonType.Fire,
    power: 16,
    pp: 10,
    range: SkillRange.Around,
    accuracy: 85,
    description: "Blasts searing heat at all surrounding foes.",
  },

  // ── Phase 71 Electric Skills ──
  voltSwitch: {
    id: "voltSwitch",
    name: "Volt Switch",
    type: PokemonType.Electric,
    power: 14,
    pp: 14,
    range: SkillRange.Front2,
    accuracy: 95,
    description: "Zaps the target with an electric jolt.",
  },

  // ── Phase 72 Poison Skills ──
  gunkShot: {
    id: "gunkShot",
    name: "Gunk Shot",
    type: PokemonType.Poison,
    power: 18,
    pp: 8,
    range: SkillRange.Front2,
    accuracy: 80,
    effect: SkillEffect.Burn,
    effectChance: 30,
    description: "Hurls filthy garbage at the target.",
  },

  // ── Phase 73 Ground Skills ──
  highHorsepower: {
    id: "highHorsepower",
    name: "High Horsepower",
    type: PokemonType.Ground,
    power: 18,
    pp: 8,
    range: SkillRange.Front2,
    accuracy: 85,
    description: "Charges with tremendous force.",
  },

  // ── Phase 75 Rock Skills ──
  smackDown: {
    id: "smackDown",
    name: "Smack Down",
    type: PokemonType.Rock,
    power: 14,
    pp: 14,
    range: SkillRange.Front2,
    accuracy: 95,
    description: "Hurls a rock to knock the target down.",
  },

  // ── Phase 76 Bug Skills ──
  megahorn: {
    id: "megahorn",
    name: "Megahorn",
    type: PokemonType.Bug,
    power: 18,
    pp: 8,
    range: SkillRange.Front2,
    accuracy: 80,
    description: "Rams with a massive horn.",
  },

  // ── Phase 77 Fighting Skills ──
  superpower: {
    id: "superpower",
    name: "Superpower",
    type: PokemonType.Fighting,
    power: 20,
    pp: 6,
    range: SkillRange.Front1,
    accuracy: 85,
    description: "Attacks with tremendous power.",
  },

  // ── Phase 79 Steel Skills ──
  gearGrind: {
    id: "gearGrind",
    name: "Gear Grind",
    type: PokemonType.Steel,
    power: 16,
    pp: 10,
    range: SkillRange.Front2,
    accuracy: 85,
    description: "Grinds gears into the target twice.",
  },

  // ── Phase 80 Ghost Skills ──
  phantomForce: {
    id: "phantomForce",
    name: "Phantom Force",
    type: PokemonType.Ghost,
    power: 18,
    pp: 8,
    range: SkillRange.Front2,
    accuracy: 90,
    description: "Vanishes and strikes from the shadows.",
  },

  // ── Phase 81 Psychic Skills ──
  futuresight: {
    id: "futuresight",
    name: "Future Sight",
    type: PokemonType.Psychic,
    power: 18,
    pp: 8,
    range: SkillRange.Room,
    accuracy: 80,
    description: "Foresees an attack that strikes all in the room.",
  },

  // ── Phase 83 Ice Skills ──
  freezeDry: {
    id: "freezeDry",
    name: "Freeze-Dry",
    type: PokemonType.Ice,
    power: 14,
    pp: 12,
    range: SkillRange.Front2,
    accuracy: 90,
    description: "Super-effective freeze ray, even against Water types.",
  },

  // ── Phase 84 Dark Skills ──
  knockOff: {
    id: "knockOff",
    name: "Knock Off",
    type: PokemonType.Dark,
    power: 12,
    pp: 14,
    range: SkillRange.Front1,
    accuracy: 95,
    description: "Knocks away the target's held item.",
  },

  // ── Phase 85 Fairy Skills ──
  moonlight: {
    id: "moonlight",
    name: "Moonlight",
    type: PokemonType.Fairy,
    power: 0,
    pp: 8,
    range: SkillRange.Self,
    accuracy: 100,
    effect: SkillEffect.Heal,
    effectChance: 100,
    description: "Restores HP by bathing in moonlight.",
  },

  // ── Phase 87 Dragon Skills ──
  outrage: {
    id: "outrage",
    name: "Outrage",
    type: PokemonType.Dragon,
    power: 20,
    pp: 6,
    range: SkillRange.Around,
    accuracy: 85,
    description: "Rampages with draconic fury, hitting everything nearby.",
  },

  // ── Phase 88 Flying Skills ──
  aerialAce: {
    id: "aerialAce",
    name: "Aerial Ace",
    type: PokemonType.Flying,
    power: 10,
    pp: 16,
    range: SkillRange.Front2,
    accuracy: 100,
    description: "An unavoidable aerial slash.",
  },

  // ── Phase 89 Normal Skills ──
  workUp: {
    id: "workUp",
    name: "Work Up",
    type: PokemonType.Normal,
    power: 0,
    pp: 10,
    range: SkillRange.Self,
    accuracy: 100,
    effect: SkillEffect.AtkUp,
    effectChance: 100,
    description: "Raises Attack by getting pumped up.",
  },

  // ── Phase 96 Water 4th Skills ──
  waterfall: {
    id: "waterfall",
    name: "Waterfall",
    type: PokemonType.Water,
    power: 16,
    pp: 10,
    range: SkillRange.Front2,
    accuracy: 90,
    description: "Charges at the foe with a wall of water.",
  },

  // ── Phase 97 Fire 4th Skills ──
  fireWhip: {
    id: "fireWhip",
    name: "Fire Whip",
    type: PokemonType.Fire,
    power: 14,
    pp: 12,
    range: SkillRange.Front2,
    accuracy: 90,
    effect: SkillEffect.Burn,
    effectChance: 20,
    description: "Lashes the foe with a flaming whip.",
  },

  // ── Phase 98 Grass 4th Skills ──
  leafStorm: {
    id: "leafStorm",
    name: "Leaf Storm",
    type: PokemonType.Grass,
    power: 20,
    pp: 6,
    range: SkillRange.Room,
    accuracy: 80,
    description: "Whips up a storm of sharp leaves.",
  },

  // ── Phase 99 Electric 4th Skills ──
  electricTerrain: {
    id: "electricTerrain",
    name: "Electric Terrain",
    type: PokemonType.Electric,
    power: 0,
    pp: 8,
    range: SkillRange.Room,
    accuracy: 100,
    effect: SkillEffect.AtkUp,
    effectChance: 100,
    description: "Electrifies the ground, boosting Electric moves.",
  },

  // ── Phase 100 Poison 4th Skills ──
  poisonJab: {
    id: "poisonJab",
    name: "Poison Jab",
    type: PokemonType.Poison,
    power: 14,
    pp: 12,
    range: SkillRange.Front1,
    accuracy: 90,
    effect: SkillEffect.Burn,
    effectChance: 30,
    description: "Stabs with a toxic barb. May poison the target.",
  },

  // ── Phase 101 Ground 4th Skills ──
  scorchingSand: {
    id: "scorchingSand",
    name: "Scorching Sand",
    type: PokemonType.Ground,
    power: 14,
    pp: 10,
    range: SkillRange.Front2,
    accuracy: 90,
    effect: SkillEffect.Burn,
    effectChance: 30,
    description: "Hurls scorching sand. May burn the target.",
  },
};

/** Get default skills for a pokemon by sprite key */
export function getDefaultSkills(spriteKey: string): Skill[] {
  switch (spriteKey) {
    case "mudkip":
      return [
        createSkill(SKILL_DB.tackle),
        createSkill(SKILL_DB.waterGun),
        createSkill(SKILL_DB.waterPulse),
        createSkill(SKILL_DB.swordsDance),
      ];
    case "zubat":
      return [
        createSkill(SKILL_DB.wingAttack),
        createSkill(SKILL_DB.leechLife),
        createSkill(SKILL_DB.poisonSting),
        createSkill(SKILL_DB.supersonic),
      ];
    default:
      return [createSkill(SKILL_DB.tackle)];
  }
}
