/**
 * Skill (Move) system — PMD-style 4-skill slot system.
 * PP is consumed on use. 1 PP recovered per movement turn.
 */

import { PokemonType } from "./type-chart";

/** Targeting range of a skill */
export enum SkillRange {
  /** Adjacent 1 tile in facing direction */
  Front1 = "front1",
  /** 2 tiles in facing direction */
  Front2 = "front2",
  /** Straight line in facing direction (up to 10 tiles, piercing) */
  FrontLine = "frontLine",
  /** All 8 adjacent tiles around self */
  Around = "around",
  /** Entire room (or radius 3 in corridor) */
  Room = "room",
  /** Self only (buff/heal) */
  Self = "self",
}

/** Effect applied on hit */
export enum SkillEffect {
  None = "none",
  AtkUp = "atkUp",         // +50% ATK for 5 turns
  DefUp = "defUp",         // +50% DEF for 5 turns
  Heal = "heal",           // Restore HP
  Burn = "burn",           // DoT: 5 dmg/turn for 3 turns
  Paralyze = "paralyze",   // 50% chance to skip turn for 3 turns
}

export interface Skill {
  id: string;
  name: string;
  type: PokemonType;
  power: number;          // 0 = non-damaging (buff/heal)
  pp: number;             // max PP
  currentPp: number;      // current PP
  range: SkillRange;
  accuracy: number;       // 0-100, percentage
  effect?: SkillEffect;
  effectChance?: number;  // 0-100, percentage to apply effect
  description: string;
}

/** Create a fresh skill instance from a template */
export function createSkill(template: Omit<Skill, "currentPp">): Skill {
  return { ...template, currentPp: template.pp };
}

// ─── Skill Database ───

export const SKILL_DB: Record<string, Omit<Skill, "currentPp">> = {
  tackle: {
    id: "tackle",
    name: "Tackle",
    type: PokemonType.Normal,
    power: 8,
    pp: 25,
    range: SkillRange.Front1,
    accuracy: 95,
    description: "A basic charge attack.",
  },
  waterGun: {
    id: "waterGun",
    name: "Water Gun",
    type: PokemonType.Water,
    power: 12,
    pp: 18,
    range: SkillRange.FrontLine,
    accuracy: 90,
    description: "Shoots a stream of water in a line.",
  },
  waterPulse: {
    id: "waterPulse",
    name: "Water Pulse",
    type: PokemonType.Water,
    power: 15,
    pp: 12,
    range: SkillRange.Front2,
    accuracy: 85,
    description: "Sends out a pulse of water. 2-tile range.",
  },
  surf: {
    id: "surf",
    name: "Surf",
    type: PokemonType.Water,
    power: 18,
    pp: 8,
    range: SkillRange.Room,
    accuracy: 90,
    description: "Hits all enemies in the room with a wave.",
  },
  swordsDance: {
    id: "swordsDance",
    name: "Swords Dance",
    type: PokemonType.Normal,
    power: 0,
    pp: 10,
    range: SkillRange.Self,
    accuracy: 100,
    effect: SkillEffect.AtkUp,
    description: "Raises ATK by 50% for 5 turns.",
  },
  // Zubat skills
  wingAttack: {
    id: "wingAttack",
    name: "Wing Attack",
    type: PokemonType.Flying,
    power: 12,
    pp: 20,
    range: SkillRange.Front1,
    accuracy: 95,
    description: "Strikes with wings.",
  },
  leechLife: {
    id: "leechLife",
    name: "Leech Life",
    type: PokemonType.Bug,
    power: 10,
    pp: 12,
    range: SkillRange.Front1,
    accuracy: 90,
    description: "Drains HP from the target.",
  },
  poisonSting: {
    id: "poisonSting",
    name: "Poison Sting",
    type: PokemonType.Poison,
    power: 8,
    pp: 20,
    range: SkillRange.Front1,
    accuracy: 95,
    effect: SkillEffect.Burn,
    effectChance: 40,
    description: "Stings with toxic barb. May poison.",
  },
  supersonic: {
    id: "supersonic",
    name: "Supersonic",
    type: PokemonType.Normal,
    power: 0,
    pp: 15,
    range: SkillRange.FrontLine,
    accuracy: 70,
    effect: SkillEffect.Paralyze,
    effectChance: 100,
    description: "Confusing sound waves. May paralyze.",
  },
  // Rock
  rockThrow: {
    id: "rockThrow",
    name: "Rock Throw",
    type: PokemonType.Rock,
    power: 12,
    pp: 15,
    range: SkillRange.Front2,
    accuracy: 85,
    description: "Hurls a rock at the target.",
  },
  // Electric
  thunderShock: {
    id: "thunderShock",
    name: "ThunderShock",
    type: PokemonType.Electric,
    power: 10,
    pp: 20,
    range: SkillRange.FrontLine,
    accuracy: 90,
    effect: SkillEffect.Paralyze,
    effectChance: 30,
    description: "Shoots electricity. May paralyze.",
  },
  spark: {
    id: "spark",
    name: "Spark",
    type: PokemonType.Electric,
    power: 14,
    pp: 15,
    range: SkillRange.Front1,
    accuracy: 90,
    effect: SkillEffect.Paralyze,
    effectChance: 30,
    description: "Charges and tackles with electricity.",
  },
  thunderWave: {
    id: "thunderWave",
    name: "Thunder Wave",
    type: PokemonType.Electric,
    power: 0,
    pp: 15,
    range: SkillRange.Front2,
    accuracy: 80,
    effect: SkillEffect.Paralyze,
    effectChance: 100,
    description: "Sends a jolt to paralyze the target.",
  },
  sonicBoom: {
    id: "sonicBoom",
    name: "SonicBoom",
    type: PokemonType.Normal,
    power: 10,
    pp: 18,
    range: SkillRange.FrontLine,
    accuracy: 85,
    description: "Shockwave attack in a line.",
  },
  selfDestruct: {
    id: "selfDestruct",
    name: "Selfdestruct",
    type: PokemonType.Normal,
    power: 30,
    pp: 3,
    range: SkillRange.Around,
    accuracy: 100,
    description: "Explodes, hitting everything nearby.",
  },
  // Bug
  stringShot: {
    id: "stringShot",
    name: "String Shot",
    type: PokemonType.Bug,
    power: 0,
    pp: 20,
    range: SkillRange.Front2,
    accuracy: 85,
    effect: SkillEffect.Paralyze,
    effectChance: 100,
    description: "Slows down the target with silk.",
  },
  bugBite: {
    id: "bugBite",
    name: "Bug Bite",
    type: PokemonType.Bug,
    power: 10,
    pp: 18,
    range: SkillRange.Front1,
    accuracy: 95,
    description: "Bites the target with mandibles.",
  },
  // Flying
  gust: {
    id: "gust",
    name: "Gust",
    type: PokemonType.Flying,
    power: 10,
    pp: 20,
    range: SkillRange.Front2,
    accuracy: 90,
    description: "Whips up a gust of wind.",
  },
  quickAttack: {
    id: "quickAttack",
    name: "Quick Attack",
    type: PokemonType.Normal,
    power: 8,
    pp: 25,
    range: SkillRange.Front1,
    accuracy: 100,
    description: "A swift, sure-hit attack.",
  },
  // Fighting
  karateChop: {
    id: "karateChop",
    name: "Karate Chop",
    type: PokemonType.Fighting,
    power: 12,
    pp: 18,
    range: SkillRange.Front1,
    accuracy: 95,
    description: "A precise chopping attack.",
  },
  lowKick: {
    id: "lowKick",
    name: "Low Kick",
    type: PokemonType.Fighting,
    power: 10,
    pp: 20,
    range: SkillRange.Front1,
    accuracy: 90,
    description: "A low sweeping kick.",
  },
  focusPunch: {
    id: "focusPunch",
    name: "Focus Punch",
    type: PokemonType.Fighting,
    power: 22,
    pp: 6,
    range: SkillRange.Front1,
    accuracy: 80,
    description: "A devastating focused punch.",
  },
  meditate: {
    id: "meditate",
    name: "Meditate",
    type: PokemonType.Fighting,
    power: 0,
    pp: 15,
    range: SkillRange.Self,
    accuracy: 100,
    effect: SkillEffect.AtkUp,
    description: "Meditates to raise ATK.",
  },
  // Steel
  metalClaw: {
    id: "metalClaw",
    name: "Metal Claw",
    type: PokemonType.Steel,
    power: 12,
    pp: 20,
    range: SkillRange.Front1,
    accuracy: 90,
    description: "Slashes with metal claws.",
  },
  ironDefense: {
    id: "ironDefense",
    name: "Iron Defense",
    type: PokemonType.Steel,
    power: 0,
    pp: 10,
    range: SkillRange.Self,
    accuracy: 100,
    effect: SkillEffect.DefUp,
    description: "Hardens the body to raise DEF.",
  },
  headbutt: {
    id: "headbutt",
    name: "Headbutt",
    type: PokemonType.Normal,
    power: 14,
    pp: 15,
    range: SkillRange.Front1,
    accuracy: 90,
    description: "A charging headbutt attack.",
  },
  // Ghost
  shadowBall: {
    id: "shadowBall",
    name: "Shadow Ball",
    type: PokemonType.Ghost,
    power: 16,
    pp: 12,
    range: SkillRange.Front2,
    accuracy: 90,
    description: "Hurls a shadowy blob. 2-tile range.",
  },
  lick: {
    id: "lick",
    name: "Lick",
    type: PokemonType.Ghost,
    power: 8,
    pp: 20,
    range: SkillRange.Front1,
    accuracy: 90,
    effect: SkillEffect.Paralyze,
    effectChance: 30,
    description: "Licks the target. May paralyze.",
  },
  nightShade: {
    id: "nightShade",
    name: "Night Shade",
    type: PokemonType.Ghost,
    power: 12,
    pp: 15,
    range: SkillRange.FrontLine,
    accuracy: 85,
    description: "Eerie shadows strike in a line.",
  },
  // Psychic
  confusion: {
    id: "confusion",
    name: "Confusion",
    type: PokemonType.Psychic,
    power: 12,
    pp: 18,
    range: SkillRange.Front2,
    accuracy: 90,
    description: "Psychic attack. 2-tile range.",
  },
  psybeam: {
    id: "psybeam",
    name: "Psybeam",
    type: PokemonType.Psychic,
    power: 16,
    pp: 12,
    range: SkillRange.FrontLine,
    accuracy: 85,
    description: "Fires a peculiar ray in a line.",
  },
  hypnosis: {
    id: "hypnosis",
    name: "Hypnosis",
    type: PokemonType.Psychic,
    power: 0,
    pp: 12,
    range: SkillRange.Front2,
    accuracy: 70,
    effect: SkillEffect.Paralyze,
    effectChance: 100,
    description: "Puts the target to sleep (paralyze).",
  },
  // Ice
  iceBeam: {
    id: "iceBeam",
    name: "Ice Beam",
    type: PokemonType.Ice,
    power: 16,
    pp: 10,
    range: SkillRange.FrontLine,
    accuracy: 90,
    description: "Fires an icy beam in a line.",
  },
  iceShard: {
    id: "iceShard",
    name: "Ice Shard",
    type: PokemonType.Ice,
    power: 10,
    pp: 20,
    range: SkillRange.Front1,
    accuracy: 100,
    description: "An icy priority attack.",
  },
  // Fire
  ember: {
    id: "ember",
    name: "Ember",
    type: PokemonType.Fire,
    power: 10,
    pp: 20,
    range: SkillRange.Front2,
    accuracy: 90,
    effect: SkillEffect.Burn,
    effectChance: 20,
    description: "Spits flames. May burn.",
  },
  flamethrower: {
    id: "flamethrower",
    name: "Flamethrower",
    type: PokemonType.Fire,
    power: 18,
    pp: 10,
    range: SkillRange.FrontLine,
    accuracy: 90,
    description: "A powerful fire stream in a line.",
  },
  scratch: {
    id: "scratch",
    name: "Scratch",
    type: PokemonType.Normal,
    power: 8,
    pp: 25,
    range: SkillRange.Front1,
    accuracy: 100,
    description: "A basic scratching attack.",
  },
  bite: {
    id: "bite",
    name: "Bite",
    type: PokemonType.Normal,
    power: 12,
    pp: 18,
    range: SkillRange.Front1,
    accuracy: 95,
    description: "Bites the target with sharp fangs.",
  },
  swift: {
    id: "swift",
    name: "Swift",
    type: PokemonType.Normal,
    power: 12,
    pp: 15,
    range: SkillRange.Room,
    accuracy: 100,
    description: "Star-shaped rays hit all enemies in the room.",
  },
  sandAttack: {
    id: "sandAttack",
    name: "Sand Attack",
    type: PokemonType.Ground,
    power: 0,
    pp: 15,
    range: SkillRange.Front2,
    accuracy: 100,
    effect: SkillEffect.Paralyze,
    effectChance: 40,
    description: "Kicks up sand to reduce accuracy.",
  },
  // ── Ground Skills ──
  mudShot: {
    id: "mudShot",
    name: "Mud Shot",
    type: PokemonType.Ground,
    power: 12,
    pp: 15,
    range: SkillRange.Front2,
    accuracy: 85,
    description: "Hurls a blob of mud. 2-tile range.",
  },
  earthPower: {
    id: "earthPower",
    name: "Earth Power",
    type: PokemonType.Ground,
    power: 18,
    pp: 8,
    range: SkillRange.Around,
    accuracy: 90,
    description: "The earth erupts around the user.",
  },
  dig: {
    id: "dig",
    name: "Dig",
    type: PokemonType.Ground,
    power: 16,
    pp: 12,
    range: SkillRange.Front1,
    accuracy: 95,
    description: "Digs underground then strikes.",
  },
  sandTomb: {
    id: "sandTomb",
    name: "Sand Tomb",
    type: PokemonType.Ground,
    power: 10,
    pp: 18,
    range: SkillRange.Around,
    accuracy: 85,
    effect: SkillEffect.Burn,
    effectChance: 30,
    description: "Traps the foe in a sand vortex.",
  },
  // ── Additional Fire Skills ──
  fireBlast: {
    id: "fireBlast",
    name: "Fire Blast",
    type: PokemonType.Fire,
    power: 22,
    pp: 5,
    range: SkillRange.Front2,
    accuracy: 80,
    effect: SkillEffect.Burn,
    effectChance: 30,
    description: "A massive blast of fire.",
  },
  lavaSurf: {
    id: "lavaSurf",
    name: "Lava Plume",
    type: PokemonType.Fire,
    power: 16,
    pp: 10,
    range: SkillRange.Around,
    accuracy: 90,
    effect: SkillEffect.Burn,
    effectChance: 30,
    description: "Scorching lava hits all adjacent foes.",
  },
  bodySlam: {
    id: "bodySlam",
    name: "Body Slam",
    type: PokemonType.Normal,
    power: 16,
    pp: 12,
    range: SkillRange.Front1,
    accuracy: 90,
    effect: SkillEffect.Paralyze,
    effectChance: 30,
    description: "A heavy slam that may paralyze.",
  },
  // ── Dark Skills ──
  darkPulse: {
    id: "darkPulse",
    name: "Dark Pulse",
    type: PokemonType.Dark,
    power: 16,
    pp: 12,
    range: SkillRange.FrontLine,
    accuracy: 90,
    description: "A wave of dark energy in a line.",
  },
  feintAttack: {
    id: "feintAttack",
    name: "Feint Attack",
    type: PokemonType.Dark,
    power: 12,
    pp: 18,
    range: SkillRange.Front1,
    accuracy: 100,
    description: "A sneaky attack that never misses.",
  },
  nightSlash: {
    id: "nightSlash",
    name: "Night Slash",
    type: PokemonType.Dark,
    power: 14,
    pp: 15,
    range: SkillRange.Front1,
    accuracy: 95,
    description: "Slashes with dark energy.",
  },
  snarl: {
    id: "snarl",
    name: "Snarl",
    type: PokemonType.Dark,
    power: 10,
    pp: 15,
    range: SkillRange.Around,
    accuracy: 90,
    description: "A growling attack hitting all nearby foes.",
  },
  pursuit: {
    id: "pursuit",
    name: "Pursuit",
    type: PokemonType.Dark,
    power: 10,
    pp: 20,
    range: SkillRange.Front2,
    accuracy: 95,
    description: "Chases and hits with dark energy.",
  },
  // ── Grass Skills ──
  vineWhip: {
    id: "vineWhip",
    name: "Vine Whip",
    type: PokemonType.Grass,
    power: 10,
    pp: 20,
    range: SkillRange.Front2,
    accuracy: 90,
    description: "Strikes with vines. 2-tile range.",
  },
  razorLeaf: {
    id: "razorLeaf",
    name: "Razor Leaf",
    type: PokemonType.Grass,
    power: 14,
    pp: 15,
    range: SkillRange.FrontLine,
    accuracy: 90,
    description: "Launches sharp leaves in a line.",
  },
  seedBomb: {
    id: "seedBomb",
    name: "Seed Bomb",
    type: PokemonType.Grass,
    power: 16,
    pp: 10,
    range: SkillRange.Front2,
    accuracy: 85,
    description: "Explosive seeds. 2-tile range.",
  },
  absorb: {
    id: "absorb",
    name: "Absorb",
    type: PokemonType.Grass,
    power: 8,
    pp: 20,
    range: SkillRange.Front1,
    accuracy: 95,
    description: "Drains HP from the target.",
  },
  sleepPowder: {
    id: "sleepPowder",
    name: "Sleep Powder",
    type: PokemonType.Grass,
    power: 0,
    pp: 10,
    range: SkillRange.Front2,
    accuracy: 70,
    effect: SkillEffect.Paralyze,
    effectChance: 100,
    description: "Scatters powder to put foes to sleep.",
  },
  // ── Poison skills ──
  sludgeBomb: {
    id: "sludgeBomb",
    name: "Sludge Bomb",
    type: PokemonType.Poison,
    power: 16,
    pp: 12,
    range: SkillRange.Front2,
    accuracy: 85,
    effect: SkillEffect.Burn,
    effectChance: 30,
    description: "Hurls sludge. May poison the foe.",
  },
  acidSpray: {
    id: "acidSpray",
    name: "Acid Spray",
    type: PokemonType.Poison,
    power: 12,
    pp: 14,
    range: SkillRange.Front2,
    accuracy: 90,
    description: "Sprays corrosive acid at the foe.",
  },
  toxicSpikes: {
    id: "toxicSpikes",
    name: "Toxic Spikes",
    type: PokemonType.Poison,
    power: 10,
    pp: 15,
    range: SkillRange.Around,
    accuracy: 80,
    effect: SkillEffect.Burn,
    effectChance: 50,
    description: "Scatters toxic spikes around self.",
  },
  venoshock: {
    id: "venoshock",
    name: "Venoshock",
    type: PokemonType.Poison,
    power: 18,
    pp: 10,
    range: SkillRange.FrontLine,
    accuracy: 80,
    description: "Fires poison beam in a line.",
  },
  // ── Fairy skills ──
  moonblast: {
    id: "moonblast",
    name: "Moonblast",
    type: PokemonType.Fairy,
    power: 18,
    pp: 10,
    range: SkillRange.Front2,
    accuracy: 85,
    description: "Moonlight blast. High power fairy move.",
  },
  disarmingVoice: {
    id: "disarmingVoice",
    name: "Disarming Voice",
    type: PokemonType.Fairy,
    power: 10,
    pp: 18,
    range: SkillRange.FrontLine,
    accuracy: 100,
    description: "Charming cry that never misses.",
  },
  drainingKiss: {
    id: "drainingKiss",
    name: "Draining Kiss",
    type: PokemonType.Fairy,
    power: 12,
    pp: 14,
    range: SkillRange.Front1,
    accuracy: 90,
    effect: SkillEffect.Heal,
    effectChance: 100,
    description: "Drains HP with a kiss.",
  },
  fairyWind: {
    id: "fairyWind",
    name: "Fairy Wind",
    type: PokemonType.Fairy,
    power: 8,
    pp: 20,
    range: SkillRange.Around,
    accuracy: 90,
    description: "Stirs up fairy wind around self.",
  },
  dazzlingGleam: {
    id: "dazzlingGleam",
    name: "Dazzling Gleam",
    type: PokemonType.Fairy,
    power: 14,
    pp: 12,
    range: SkillRange.Room,
    accuracy: 80,
    description: "Dazzling light fills the room.",
  },
  // ── Dragon skills ──
  dragonBreath: {
    id: "dragonBreath",
    name: "Dragon Breath",
    type: PokemonType.Dragon,
    power: 12,
    pp: 16,
    range: SkillRange.Front2,
    accuracy: 90,
    effect: SkillEffect.Paralyze,
    effectChance: 30,
    description: "Exhales dragon breath. May paralyze.",
  },
  dragonClaw: {
    id: "dragonClaw",
    name: "Dragon Claw",
    type: PokemonType.Dragon,
    power: 16,
    pp: 12,
    range: SkillRange.Front1,
    accuracy: 90,
    description: "Slashes with sharp dragon claws.",
  },
  dragonPulse: {
    id: "dragonPulse",
    name: "Dragon Pulse",
    type: PokemonType.Dragon,
    power: 18,
    pp: 10,
    range: SkillRange.FrontLine,
    accuracy: 85,
    description: "Fires a shockwave of draconic energy.",
  },
  dracoMeteor: {
    id: "dracoMeteor",
    name: "Draco Meteor",
    type: PokemonType.Dragon,
    power: 24,
    pp: 5,
    range: SkillRange.Room,
    accuracy: 75,
    description: "Summons meteors to strike the room!",
  },
  twister: {
    id: "twister",
    name: "Twister",
    type: PokemonType.Dragon,
    power: 10,
    pp: 18,
    range: SkillRange.Around,
    accuracy: 90,
    description: "Whips up a vicious twister around self.",
  },

  // ── Steel Skills ──
  ironHead: {
    id: "ironHead",
    name: "Iron Head",
    type: PokemonType.Steel,
    power: 16,
    pp: 15,
    range: SkillRange.Front1,
    accuracy: 90,
    effect: SkillEffect.Paralyze,
    effectChance: 30,
    description: "Rams with a steel-hard head. May paralyze.",
  },
  flashCannon: {
    id: "flashCannon",
    name: "Flash Cannon",
    type: PokemonType.Steel,
    power: 16,
    pp: 12,
    range: SkillRange.FrontLine,
    accuracy: 90,
    description: "Fires a flash of light energy in a line.",
  },
  bulletPunch: {
    id: "bulletPunch",
    name: "Bullet Punch",
    type: PokemonType.Steel,
    power: 10,
    pp: 22,
    range: SkillRange.Front2,
    accuracy: 100,
    description: "Strikes with a quick punch of steel.",
  },
};

/** Get default skills for a pokemon by sprite key */
export function getDefaultSkills(spriteKey: string): Skill[] {
  switch (spriteKey) {
    case "mudkip":
      return [
        createSkill(SKILL_DB.tackle),
        createSkill(SKILL_DB.waterGun),
        createSkill(SKILL_DB.waterPulse),
        createSkill(SKILL_DB.swordsDance),
      ];
    case "zubat":
      return [
        createSkill(SKILL_DB.wingAttack),
        createSkill(SKILL_DB.leechLife),
        createSkill(SKILL_DB.poisonSting),
        createSkill(SKILL_DB.supersonic),
      ];
    default:
      return [createSkill(SKILL_DB.tackle)];
  }
}
